CHANGELOG.md, Gemfile, Gemfile.lock, README.md, app/controllers/application_controller.rb, app/controllers/concerns/sentryable.rb, config/initializers/sentry.rb
Sentry integration will help us trace bugs in both production and staging environments. Sentry integration can be turned on **only** in production environemtn by setting `SENTRY_DSN` env variable with details how to connect to sentry server. Additionally `SENTRY_ENVIRONMENT` can be set to customize entvironment errors will be reported (default set to `production`).
=> Sentry integration

CHANGELOG.md, config/routes.rb
Since marketplace will be 100% based on external IDP (configured using omniauth) no session related URLs should be defined. Here session routes are removed, only logout option remains.
=> Remove default session devise routes

.rubocop.yml, CHANGELOG.md, Gemfile, Gemfile.lock, app/controllers/categories_controller.rb, app/controllers/concerns/service/searchable.rb, app/controllers/services_controller.rb, app/models/category.rb, app/models/service.rb, app/models/service_category.rb, app/views/categories/_subcategories.html.haml, app/views/categories/_subcategory.html.haml, app/views/categories/show.html.haml, app/views/layouts/_navbar.html.haml, app/views/services/_left_menu.html.haml, app/views/services/_services.html.haml, app/views/services/index.html.haml, config/breadcrumbs.rb, config/routes.rb, db/migrate/20180607103156_create_categories.rb, db/migrate/20180607105149_create_service_categories.rb, db/schema.rb, lib/tasks/dev.rake, spec/factories/categories.rb, spec/factories/services.rb, spec/features/categories_spec.rb, spec/models/category_spec.rb, spec/models/service_spec.rb
This is initial categories implementation for services. Each service can belong to one or many categories but only one category is the main category. It is used to render breadcrumbs. 
There is logic for updating the main category after the category is destroyed or service is created. There are also dedicated `/categories/:id` routes and view to show services only from given category.
=> Service categories

CHANGELOG.md, Gemfile, Gemfile.lock, app/helpers/markdown_helper.rb, app/views/services/show.html.haml, db/migrate/20180621061901_add_terms_of_use_to_service.rb, db/schema.rb, lib/tasks/dev.rake, spec/factories/services.rb, spec/features/service_spec.rb, spec/helpers/markdown_helper_spec.rb
Service terms of use were added. Markdown renderer was configured to render this value. In the future, this renderer can be used to render other UI elements.
Fixes #36
=> 36 terms of use

app/models/service.rb, app/models/user.rb, spec/models/service_spec.rb, spec/models/user_spec.rb
Relations were added in DB and `belongs_to` relation was defined. Unfortunately, I forgot to add `has_many` to the second relation site (this traversing is not used yet but can be useful in the future and it is good to define what will happen when service or user will be deleted from the system).
Deletion of the user or service is something we need to discuss further - should we allow to do this or some kind of soft deletion technique (by using e.g [discard](https://github.com/jhawthorn/discard))
=> Add missing has_many orders into user and service

CHANGELOG.md, Gemfile.lock
See https://groups.google.com/forum/#!topic/ruby-security-ann/2S9Pwz2i16k for details
=> Upgrade Sprockets gem to avoid CVE-2018-3760

config/environments/production.rb, package.json
Turn on es6 features for uglifier and move production required dependencies (e.g. fontawesome, bootstrap) into production dependencies section instead of devDependencies.
=> Fix asset production build

CHANGELOG.md, README.md, db/seeds.rb
Introduced Service and Category database seeds. Updated readme and changelog. 
While running `/bin/setup` rake will seed the database with important data. However seeds can 
also be re-run with additional parameters allowing to specify e.g. number of services seeded
to the database.
Example use of the database seed:
```
rake db:seed services_size=100
```
=> Introduced Service and Category seeds

CHANGELOG.md, app/helpers/service_helper.rb, app/javascript/stylesheets/_bootstrap-customizations.scss, app/javascript/stylesheets/_variables.scss, app/jobs/order/ready_job.rb, app/models/service.rb, app/policies/backoffice/service_policy.rb, app/services/order/create.rb, app/services/order/ready.rb, app/validators/url_validator.rb, app/views/backoffice/services/_form.html.haml, app/views/backoffice/services/show.html.haml, app/views/services/_description.html.haml, db/migrate/20180711140914_add_connected_url_to_services.rb, db/migrate/20180719071704_add_open_access_to_service.rb, db/schema.rb, lib/tasks/dev.rake, spec/factories/services.rb, spec/features/backoffice/services_spec.rb, spec/features/orders_spec.rb, spec/models/service_spec.rb, spec/services/order/ready_spec.rb
User can add to 'my service' open access service.
Open access service is available for all logged users.
User can go to open access service website from service details view 
If user add open access service to "my services" order will change status to ready(i dont know is this good status @roksanaer ???)
User can add open access service in backoffice.
If service is open access then connected url is required. 
Fix #113
=> [#113] User can add open access services to my services

app/helpers/service_helper.rb, app/javascript/packs/application.js, package.json, spec/helpers/service_helper_spec.rb, yarn.lock
* Uprgade FA, to the new library dropping depreciated `@fortawesome/fontawesome-free-*`
* Fix `app/helpers/service_helper.rb:print_rating_stars` to use correct icons from FA 5.2
1. Navigate to services, if all stars are displayed then this PR works
Fixes #125
=> [#125] Upgrade Font Awesome to fix stars

CHANGELOG.md, README.md, db/data.yml, db/seeds.rb
Add categories and services to the marketplace from production.
Add loops for creating services, categories and service_categories.
Filling the database is done by parsing yaml.
Fixes: #136, #138, #139
=> [#136, #138, #139] Fill categories and services in database

Gemfile, Gemfile.lock, README.md, app/controllers/carts_controller.rb, app/controllers/orders_controller.rb, app/policies/cart_policy.rb, app/views/carts/_cart.html.haml, app/views/carts/_order_item.html.haml, app/views/carts/show.html.haml, app/views/services/_description.html.haml, config/environments/test.rb, config/initializers/session_store.rb, config/routes.rb, spec/features/carts_spec.rb, spec/features/orders_spec.rb
Ordering Button is visible for logged in and unlogged users. 
Added cart as page with order summary(only service  title). This solve the problem with redirection back after login in to the created order. When user click on "Order" service_id is saved in to the session and redirected to cart_path where mus be logged in.
Set Redis as session store.  
"Rack_session_access" gem is for session management in tests.
Fixed #160 #161
=> [#160 #161] Added additionaly step to order creation process 

CHANGELOG.md, README.md, app/controllers/api/webhooks/jiras_controller.rb, app/helpers/orders_helper.rb, app/services/jira/comment_created.rb, app/services/jira/issue_updated.rb, app/views/orders/_order_change.html.haml, spec/requests/rest/webhooks/jira_spec.rb, spec/services/jira/comment_created_spec.rb, spec/services/jira/issue_updated_spec.rb
When a new message is added in Jira it is also registered in MP as service provider message.
To make webhooks more generic (for the status update and messages) `issue_id` query param need to be defined. Otherwise, it was tricky to get issue id for new comment (url regexp was needed). This query param fixes problem (described in the `README.md`).
Fixes #199
=> Order change with service provider message

spec/features/backoffice/services_spec.rb
This problem was connected with the situation when other providers were already created in DB. Fix is to use real new created provider name.
=> Fix random failing test

app/controllers/services/summaries_controller.rb
This avoids user to reload summary page and order service once again.
=> Clear order session after ordering service

CHANGELOG.md, app/controllers/categories_controller.rb, app/controllers/concerns/paginable.rb, app/controllers/services_controller.rb, app/views/services/_services.html.haml, config/brakeman.ignore, db/schema.rb, spec/features/categories_spec.rb, spec/features/service_spec.rb
Links for defining a number of shown services per page are working.
=> Show 10, 20 or 30 services per page

CHANGELOG.md, app/controllers/services/offers_controller.rb, app/models/offer.rb, db/migrate/20181022085713_create_offers.rb, db/migrate/20181022113319_add_offer_ref_to_project_item.rb, db/migrate/20181022113346_remove_service_ref_from_project_item.rb, db/migrate/20181025095520_add_offers_count.rb, db/schema.rb, lib/tasks/counter_cache.rake, spec/features/order_spec.rb
@wziajka after this PR is merged following rake task need to be invoked manually once
```
rails service_counter 
```
this will generate counter cache for existing service offers
=> Skip offer selection when only one offer

CHANGELOG.md, app/controllers/services/configurations_controller.rb, spec/features/order_spec.rb
When a project is selected and order (project item) is valid user is redirected directly to the summary order page.
=> Autoselect default project for open access service order

CHANGELOG.md, app/controllers/services/summaries_controller.rb, app/controllers/services_controller.rb, app/models/service.rb, app/models/service_relationship.rb, app/views/services/_related.html.haml, app/views/services/_service_box.html.haml, app/views/services/show.html.haml, app/views/services/summaries/confirmation.html.haml, db/migrate/20181024093203_create_service_relationships.rb, db/schema.rb, spec/features/service_spec.rb, spec/models/service_relationship_spec.rb, spec/models/service_spec.rb
Related services are shown on service show view and in the service order confirmation page. n-n relation between `Services` is modeled using `ServiceRelationship` model. It can be used to model additional
relationships between services. E.g. additional field `relation_type` can be added to `ServiceRelationship`, next `where` condition can be added into `Service` `has_many` relation between services.
This PR solves everything described in #223 except:
* formatting (nice css which deals with multiple related services need to be created - there can be 1 or 10 related services thus some grid layout need to be applied)
* showing elements which are not yet available in the service model (`Area (scientific discipline)`)
This is how it looks like right now:
To create relation between services …
=> Related services

app/models/jira/checker.rb, spec/models/jira/checker_spec.rb
Jira check was not updated after mandatory `issue_id` query param was added to webhook return url. Here this situation if fixed.
=> Fix jira check after adding issue_id

CHANGELOG.md, Gemfile, Gemfile.lock, Procfile, Procfile.dev, app/controllers/admin/application_controller.rb, app/controllers/admin/jobs_controller.rb, app/controllers/admins_controller.rb, app/javascript/stylesheets/admin/_jobs.scss, app/javascript/stylesheets/application.scss, app/jobs/project_item/ready_job.rb, app/jobs/project_item/register_job.rb, app/jobs/project_item/register_question_job.rb, app/models/user.rb, app/policies/admin/admin_policy.rb, app/views/admin/jobs/index.html.haml, app/views/admins/show.html.haml, app/views/layouts/_navbar.html.haml, app/views/layouts/admin.html.haml, app/views/layouts/admin/_navbar.html.haml, config/application.rb, config/initializers/active_job.rb, config/initializers/session_store.rb, config/initializers/sidekiq.rb, config/routes.rb, spec/features/admin/version_spec.rb, spec/policies/admin/admin_policy_spec.rb
Sidekiq is configured to process all background jobs. Currently, we have `orders` and `mailers` queues. Status of delayed jobs can be monitored using administration panel (`/admin/jobs`).
Some screenshots of new UI:
\cc @wziajka  After this PR is merged additional container with sidekiq should be started. Take a look into `Procfile` for details.
=> Sidekiq for background jobs

CHANGELOG.md, app/controllers/services_controller.rb, app/views/services/_about.html.haml, app/views/services/_offer.html.haml, app/views/services/_offers.html.haml, app/views/services/offers/_offer.html.haml, app/views/services/offers/index.html.haml, app/views/services/show.html.haml, spec/features/order_spec.rb
Preliminary version for showing service offers using bootstrap cards. Offers cards require work from UX team (cc @kosmidma, @abacz), but I believe this is a good start. 
What needs to  be done by UX team:
* Better styling
* small JS for adding active class into the card (than some additional border and button icon can be added) - @michal-szostak can you help with this issue? 
Sample screenshots showing how it looks like right now:
=> Show offers as cards

app/views/layouts/_footer.html.haml
Since MP version is shown in the administration panel it can be removed from the footer where it looks very ugly.
=> Remove MP version from footer

CHANGELOG.md, Gemfile, Gemfile.lock, Procfile, Procfile.dev, README.md, app/models/service.rb, app/policies/backoffice/service_policy.rb, app/views/backoffice/services/_form.html.haml, app/views/backoffice/services/show.html.haml, app/views/services/_about.html.haml, app/views/services/_header.html.haml, app/views/services/_related.html.haml, app/views/services/_service.html.haml, app/views/services/_service_box.html.haml, app/views/services/_services.html.haml, app/views/services/index.html.haml, app/views/services/show.html.haml, config/storage.yml, db/migrate/20181030074128_create_active_storage_tables.active_storage.rb, db/schema.rb, spec/features/categories_spec.rb, spec/features/service_spec.rb
Following elements were added/improved:
* service logo can be added to the service
* services list redesigned
* service header redesigned
* related service partial prototype using bootstrap cards
Screenshots from the current version:
=> Service view redesigned

CHANGELOG.md, app/controllers/categories_controller.rb, app/controllers/concerns/service/searchable.rb, app/controllers/services_controller.rb, app/javascript/packs/sort_filter.js, app/views/categories/_subcategories.html.haml, app/views/services/_filters.html.haml, app/views/services/_search.html.haml, app/views/services/index.html.haml, spec/features/service_spec.rb, spec/models/service_relationship_spec.rb
* Extension of `Searchable` concern to handle new filters in the future
* Added handling of select controls to `syncQueryForm` in JS
* Fixed `action` attribute in filter forms to be `""` (so searching in categories would work as expected)
Fixes: #83
=> [#83] Extend Searchable

app/controllers/profiles/affiliations_controller.rb
The affiliation status was forcefully set to :active on creation instead
of :created.
The hack was introduced to be able to test the ordering process while
the delivery of mail (which is necessary to obtain the activation
token) didn't work.
=> Revert setting new affiliation status to :active

app/views/services/configurations/show.html.haml
If a user is ordering service and active affiliation is not created yet than order cannot be finished. Affiliation needs to be created and activated (through a link sent by email).                                                                       
Here we are only adding hint into configuration form with new affiliation link to simplify navigation into required new affiliation form.        
Fixes #266
=> Add hint with new affiliation link

app/javascript/stylesheets/_header.scss, app/views/layouts/_navbar.html.haml
The dropdowns are hidden when toggler is clicked and expanded on header
click (in screen widths < lg). "Services & Resources" dropdown is
always expanded.
=> Fix navbar in smaller browser windows

CHANGELOG.md, Gemfile, Gemfile.lock, app/models/affiliation.rb, app/models/user.rb, app/views/layouts/_flash.html.haml, db/migrate/20181107143358_add_active_affiliations_count.rb, db/schema.rb, lib/tasks/counter_cache.rake, spec/features/alerts_spec.rb, spec/models/user_spec.rb
Alert is shown for logged in user when there is no active affiliation
After this is deployed and there are active affiliations count cache should be updated by invoking this command (/cc @wziajka):
```
rails active_affiliation_counter
```
=> Show alert for logged in user when no active affiliation

app/controllers/services/offers_controller.rb, app/views/services/offers/_offer.html.haml, app/views/services/offers/index.html.haml
`ActionController::ParameterMissing` exception was thrown because there was nothing to put into post `project_item` hash. To sole it instead of `require`, `fetch` is used according to [this](https://stackoverflow.com/questions/17354053/rails-4-strong-parameters-handling-missing-model-params-hash) recommendation.
=> Fix offer selection empty

app/models/affiliation.rb
Fix for issue discovered by @roksanaer in https://github.com/cyfronet-fid/marketplace/pull/299#pullrequestreview-173170738 - email word is duplicated in affiliation validation.
=> Fix email word duplication in affiliation validation

CHANGELOG.md, app/javascript/stylesheets/_bootstrap-customizations.scss, app/javascript/stylesheets/_variables.scss, app/views/home/index.html.haml, app/views/layouts/_breadcrumb.html.haml, app/views/playground/home-view.html.haml, app/views/profiles/_profile.html.haml, app/views/profiles/affiliations/_affiliation.html.haml, app/views/profiles/affiliations/_form.html.haml, app/views/profiles/affiliations/_index.html.haml, app/views/profiles/show.html.haml, app/views/project_items/_project_item.html.haml, app/views/projects/_empty_project.html.haml, app/views/projects/_project.html.haml, app/views/projects/index.html.haml
- Remove placeholders from affiliation list view and replace them with
actual field values.
Correct affiliations view in line with prefkas.
Don't use .btn-group in affiliation edit view's footer.
- Redefine .display-* with variables rather than selector redefinitions.
- Try to switch to using Bootstrap for breadcrumbs, but gretel doesn't
support Bootstrap4 yet.
=> Improve affiliations and projects views

CHANGELOG.md, app/models/service_category.rb, lib/tasks/counter_cache.rake, spec/models/category_spec.rb
Previously only services directly assigned to the category was taken while calculating services count. After this change services directly assigned to the category and all its subcategories are taken into account.
=> Hierarchic categories count

CHANGELOG.md, app/helpers/order_nav_helper.rb, app/views/layouts/order/_nav.html.haml
After @agpul presentation yesterday it was clear that the next nav button should be clickable and behave the same as "Next" button. Here this feature is added. I needed to use js to submit a form because button with submit type cannot be used in navbar (it looks ugly and behave very strange).
=> Clickable next order nav step

CHANGELOG.md, app/models/project_item.rb, config/initializers/simple_form_validation.rb
This was done as advised in https://github.com/plataformatec/simple_form/issues/250#issuecomment-5855384. `||=` was added into `ProjectItem` class to avoid multiple checks if ordered service is an open-access service.
The problem was visible on order configuration view when normal service was ordered.
=> Simple form checks validation if conditions

app/controllers/application_controller.rb, app/controllers/categories_controller.rb, app/views/layouts/application.html.haml, app/views/services/_search.html.haml, spec/features/home_spec.rb
* Search by text will by default go to `/services`, this form
submission path can be overriden in specific controller by
overriding `set_search_submit_path` method which should set
`@search_submit_path` variable
Fixes: #323
=> [#323] Fix Search

app/services/affiliation/create.rb
There is something strange on doker environment that leads to generating empty token when `has_secure_token` is used. To fix this issue before affiliation is saved we are forcing to generate token (something which should be also done in before create callback).
=> Force token generation before saving affiliation

app/services/affiliation/create.rb
There is something strange on doker environment that leads to
generating empty token when has_secure_token is used. To fix this
issue before affiliation is saved we are forcing to generate token
(something which should be also done in before create callback).
=> Force affiliation token generation

app/models/affiliation.rb, app/services/affiliation/create.rb
This is a source of all problems with affiliation creation. Validation is invoked before `before_create` callback which generates token.
=> Remove token uniques validation from model

CHANGELOG.md, app/views/services/_about.html.haml, app/views/services/configurations/show.html.haml, app/views/services/offers/_offer.html.haml, app/views/services/offers/index.html.haml, app/views/services/summaries/show.html.haml
* Rename order step's headers to match nav bar captions
* Reorder form fields in configuration step, and in summary step according to #344
* Rename "Some Header" in `services/_about.html.haml` to "Documents"
* Hide Technical Parameters in offer selection
Fixes: #344, #346
=> [#344] Reorder form parts in ordering

CHANGELOG.md, app/views/services/_about.html.haml
* Hide Service Offers in service's about page if no offers are
available
Fixes: #347
=> [#347] Hide Service Offers

app/models/affiliation.rb, spec/models/affiliation_spec.rb
The domain validation doesn't properly handle edge cases such as
inputting "domain.org/" (with slash), and properly others.
So disable it altogether for now.
Fixes: #370
=> [#370] Disable affiliation email domain validation

app/controllers/categories_controller.rb, spec/features/categories_spec.rb
`ancestry` method returns parent `id` not object itself.
Fixes #338
=> Fix siblings find when not in root category

app/views/projects/show.js.erb
This guarantee correct option rendering (no more "a%#36a" when the new project "a'a" is created).
Fixes #371
=> Use rails helper to render new project option

CHANGELOG.md, README.md, app/views/layouts/_google_analytics.html.haml, app/views/layouts/_head.html.haml, spec/features/admin/version_spec.rb
This is the first attempt to integrate google analytics into MP. Since this can be problematic to work with turbolinks (as described in #405 issue) this need to be carefully tested if no duplicated entries or no entries are reported.  
Fixes #405
=> Google analytics integration

CHANGELOG.md, Gemfile, Gemfile.lock, app/controllers/backoffice/services_controller.rb, app/controllers/categories_controller.rb, app/controllers/services/application_controller.rb, app/controllers/services/opinions_controller.rb, app/controllers/services/questions_controller.rb, app/controllers/services_controller.rb, app/models/category.rb, app/models/service.rb, config/initializers/friendly_id.rb, db/migrate/20181114222220_create_friendly_id_slugs.rb, db/migrate/20181114224426_add_slug_to_service.rb, db/migrate/20181114224431_add_slug_to_category.rb, db/schema.rb, lib/tasks/friendly_id.rake
[`friendly_id`](https://github.com/norman/friendly_id) gem was used to add friendly URLs for services and categories. 
When this PR is pushed into an environment where categories and services are already defined in DB friendly ids need to be generated. To do that run the following task (cc @wziajka):
```
rails friendly_id:generate
```
Fixes #30
=> Friendly urls for services and category

CHANGELOG.md, app/controllers/application_controller.rb, app/controllers/categories_controller.rb, app/javascript/controllers/search_controller.js, app/views/layouts/application.html.haml, app/views/services/_search.html.haml, spec/features/home_spec.rb, spec/features/search_spec.rb
This PR extends search bar to include category select: 
* Category select box will automatically set itself based on URL's
category id (or lack therof)
* Changing category will change form action attribute
* All of this is achieved by some JS magic (via stimulus)
Fixes: #376
=> [#376] Add category select in text search

app/views/project_items/_project_item.html.haml, spec/features/my_services_spec.rb
Display link to service webpage when service is ready 
Fix #357
=> [#357] Link to website when serice is active

CHANGELOG.md, app/javascript/packs/sort_filter.js, spec/features/service_spec.rb
* Page query param is not synced from query params now, filtering
should reset page on which user was prior to filtering
Fixes: #430
=> [#430] Page is retained when filtering

app/controllers/application_controller.rb, config/locales/pundit.en.yml, spec/features/affiliations_spec.rb
The previous not authorized error message could be ambiguous for users,
so now it is possible to set a custom one based on policy and query.
* Messages for edit? and destroy? queries for Affiliation are added.
Fixes: #433
=> [#433] Custom error messages for policies

CHANGELOG.md, app/controllers/categories_controller.rb, app/controllers/concerns/service/searchable.rb, app/models/platform.rb, app/models/provider.rb, spec/controllers/concerns/searchable_spec.rb, spec/features/service_spec.rb
* Fix `dedicated_for_options`, `provider_options`,
`related_platform_options` to count number of services with respect
to selected category
* create new unit test spec for `Searchable`
Fixes: #368
=> [#368] Fix service count in filter multiselects

app/controllers/concerns/service/searchable.rb
Right now we are doing a log of additional db queries - simply we have n+1 queries problems. One of n+1 problem is connected with loading services logos. This PR solves this problem.
Before:
```
23:32:11 web.1       |   Service Load (0.6ms)  SELECT  "services".* FROM "services" LIMIT $1 OFFSET $2  [["LIMIT", 10], ["OFFSET", 0]]
23:32:11 web.1       |   ↳ app/views/services/index.html.haml:31
23:32:11 web.1       |   ResearchArea Load (0.4ms)  SELECT "research_areas".* FROM "research_areas" INNER JOIN "service_research_areas" ON "research_areas"."id" = "service_research_areas"."research_area_id" WHERE "service_research_areas"."service_id" = $1  [["service_id", 15]]
23:32:11 web.1       |   ↳ app/views/services/_categorization.html.haml:2
23:32:11 web.1       |   Provider Load (0.3ms) …
```
=> Eliminate n + 1 queries for services logos

CHANGELOG.md, app/controllers/services/summaries_controller.rb, app/helpers/service_helper.rb, app/models/confirmation.rb, app/views/services/summaries/show_normal.html.haml, config/locales/simple_form.en.yml, spec/features/order_spec.rb
Terms and condition are taken from service.terms_of_use_url. 
Fix #358
=> [#358] Terms and condition hint have dynamic url

CHANGELOG.md, app/views/project_items/show.html.haml, app/views/services/summaries/show_normal.html.haml
* Add a section with connected affiliation data in project view details.
* Don't show affiliation fields which don't have values in project item
order summary step.
Fixes: #446
=> [#446] Show affiliation in project item view

README.md, app/views/home/_products.html.haml, app/views/layouts/_footer.html.haml, config/application.rb
Add missing "For providers" footer link.
EOSC portal base URL was also extracted into the configuration (you can access it using `Mp::Application.config.portal_base_url`). This value can be overridden if needed by setting `PORTAL_BASE_URL` env variable (cc @wziajka).
=> Add for providers section to footer

CHANGELOG.md, app/controllers/profiles/affiliations_controller.rb, config/routes.rb
After affiliation is created and user press f5 ugly 404 page was shown. This situation occurred because `index` action was not defined in routes. To improve this situation redirect from `GET /affiliations` to `GET
/profile` was added.
=> Redirect user from affiliations to profile

CHANGELOG.md, app/views/affiliation_confirmations/index.html.haml, app/views/profiles/affiliations/consent.html.haml
Order confirmation view was used as a template for affiliation create "last step" and affiliation confirmation views
Was:
Now:
Was:
Now:
=> Unify confirmation views

app/views/affiliation_confirmations/index.html.haml, app/views/profiles/affiliations/consent.html.haml, app/views/services/summaries/confirmation_normal.html.haml
It is needed for buttons to loos nice on small devices
=> Bottom margin for confirmation first button

spec/features/service_spec.rb
I have no idea how it didn't get selected for commit in PR #469 
* Add feature test for #442 (default sort order of services)
Fixes: #442
=> [#442] Add feature test for default sort order

CHANGELOG.md, Gemfile, Gemfile.lock, app/controllers/categories_controller.rb, app/controllers/concerns/service/searchable.rb, app/controllers/services_controller.rb, app/models/service.rb, app/policies/backoffice/service_policy.rb, app/views/backoffice/services/_form.html.haml, app/views/categories/show.html.haml, app/views/services/_filters.html.haml, app/views/services/_index.html.haml, app/views/services/_tags.html.haml, app/views/services/index.html.haml, app/views/services/show.html.haml, config/initializers/act_as_taggable_on.rb, config/locales/simple_form.en.yml, db/migrate/20181121094056_acts_as_taggable_on_migration.acts_as_taggable_on_engine.rb, db/migrate/20181121094057_add_missing_unique_indices.acts_as_taggable_on_engine.rb, db/migrate/20181121094058_add_taggings_counter_cache_to_tags.acts_as_taggable_on_engine.rb, db/migrate/20181121094059_add_missing_taggable_index.acts_as_taggable_on_engine.rb, db/migrate/20181121094060_change_collation_for_tag_names.acts_as_taggable_on_engine.rb, db/migrate/20181121094061_add_missing_indexes_on_taggings.acts_as_taggable_on_engine.rb, db/schema.rb, db/seeds.rb, spec/features/filter_spec.rb, spec/features/service_spec.rb
Service tags can be seen on 2 views:
To add tag in `seeds` add tags information into `db/data.yml` (cc @roksanaer, @goreck888, @agpul):
```yml
service_name:
...
tags: a, b, c
```
or
```yaml
service_name:
...
tags:
- a
- b
- c
```
Fixes #215
=> Service tags

CHANGELOG.md, app/models/jira/checker.rb, app/services/project_item/ready.rb, lib/jira/console_checker.rb, spec/lib/jira/console_checker_spec.rb, spec/services/project_item/ready_spec.rb
* Transition in ready service is now based on configured
workflow done state id, instead of hardcoded state.
* Add check to `jira:check` rake task which checks whether jira's
workflow has direct transition from `todo` to `done` state
Fixes: #483
=> [#483] Ready service JIRA Issue transition

config/initializers/constants.rb, spec/helpers/project_items_helper_spec.rb
https://github.com/cyfronet-fid/marketplace/issues/539
change time period after which user can rate and mail is sending to 3 months. also fixed test so that they use only variable periods of time.
=> Setup rate period for 3 months

CHANGELOG.md, app/jobs/project_item/register_job.rb, app/models/jira/client.rb, app/services/project_item/ready.rb, app/services/project_item/register.rb, config/jira.yml, spec/jobs/project_item/ready_job_spec.rb, spec/models/jira/client_spec.rb, spec/services/project_item/ready_spec.rb, spec/services/project_item/register_spec.rb
* `ProjectItem::RegisterJob` did not recast exceptions, so if something went wrong sidekiq did not try to restart job, and no errors were logged, exception handles were retained, but error reraising has been added.
* It turned out that `CP-CustomerTypology` field in production JIRA's custom field scheme has "select" type, which requires very specific value handling. It has been added, with appropriate tests.
* Jobs and Services connected to JIRA issues had their tests expanded with failure scenarios
As far as I know accessing field available option metadata is not possible, at least if you do not
have JIRA admin priviledges.
The issue for that has been created separately here #548 
Fixes: #546
=> [#546] Support for SELECT options for custom fields

app/models/jira/client.rb, spec/models/jira/client_spec.rb
* Fix issue, where in open access services customer typology field
generation would crash
* Add test for `client_spec.rb` for open access service
Fixes: #546
=> [#546] Fix Open Access Service issue creation

CHANGELOG.md, app/views/backoffice/services/_form.html.haml, app/views/services/_filters.html.haml
#544 
couldn't replicate situation with wrong input -> db record
fix problem with commas during editing service entry.
=> Fix tag_list input for Service form in backoffice

Gemfile, Gemfile.lock, app/models/project_item.rb, spec/features/order_spec.rb
Before going to the last step (summaries) service are checked if it's already added to selected project.   
If it's already added it's shown message and user are redirected to the configuration page
Fix #555
=> [#555] Every open access service can be added to project only once 

CHANGELOG.md, app/views/admin/jobs/index.html.haml, app/views/admins/show.html.haml, app/views/backoffice/services/edit.html.haml, app/views/backoffice/services/index.html.haml, app/views/backoffice/services/new.html.haml, app/views/backoffice/services/show.html.haml, app/views/backoffices/show.html.haml, config/breadcrumbs/admin.rb, config/breadcrumbs/backoffice.rb, config/breadcrumbs/marketplace.rb
Next unification step - breadcrumbs for Backoffice and Admin sections.
=> Backoffice and Admin sections breadcrumbs

CHANGELOG.md, app/controllers/backoffice/services_controller.rb, app/models/service.rb, app/models/service_user_relationship.rb, app/models/user.rb, app/policies/backoffice/backoffice_policy.rb, app/policies/backoffice/service_policy.rb, app/views/backoffice/services/_form.html.haml, db/migrate/20190110095634_remove_owner_from_service.rb, db/migrate/20190110103051_create_service_user_relationships.rb, db/migrate/20190110111453_add_owned_services_count_to_user.rb, db/schema.rb, lib/tasks/dev.rake, spec/features/backoffice/services_spec.rb, spec/features/backoffice_spec.rb, spec/models/service_spec.rb, spec/models/service_user_relationship_spec.rb, spec/models/user_spec.rb, spec/policies/backoffice/backoffice_policy_spec.rb, spec/policies/backoffice/service_policy_spec.rb, spec/requests/backoffice/services_spec.rb, spec/services/service/create_spec.rb, spec/services/service/update_spec.rb
In the scope of this PR roles model was refactored:
* `service_owner` roles was renamed into `service_portfolio_manager`. The conclusion of this role renaming is that existing service owners (@agpul and @roksanaer) will become members of the service portfolio management team :smile: 
* N-N relation was added between `Service` and `User` (using `ServiceUserRelationship` join table). This relation is used to dynamically calculate `service_owner` role (using `owned_services_count` counter cache)
`ServiceUserRelationship` joining table is a generic type and can be used to model much more than service ownership. Take a look at this commit comment https://github.com/cyfronet-fid/marketplace/commit/6696eed4bc1717fe615409cc12716361cf4f9b0a for details.
Fixes #586
=> [#586] many service owners

CHANGELOG.md, app/models/jira/client.rb, config/jira.yml, spec/models/jira/client_spec.rb
* Add custom field support for `SO-ProjectName`. The field is filled as
follows: `<project_nanme> (<project_id>)`
Fixes: #593
=> [#593] Add custom field with project name to created issue

CHANGELOG.md, app/models/jira/client.rb, config/jira.yml, spec/models/jira/client_spec.rb
This PR adds JIRA mapping for the following fields:
* Add `CP-UserGroupName`
* Add `CP-ProjectInformation`
Fixes: #582
=> [#582] Add CP-UserGroupName & CP-ProjectInformation mappings to JIRA

CHANGELOG.md, app/helpers/research_areas_helper.rb, app/models/jira/client.rb, app/models/project_item.rb, app/models/research_area.rb, app/policies/project_item_policy.rb, app/views/project_items/show.html.haml, app/views/services/configurations/show_normal.html.haml, app/views/services/summaries/show_normal.html.haml, config/jira.yml, db/migrate/20190114121032_add_research_area_ref_to_project_item.rb, db/schema.rb, docs/jira_integration.md, spec/factories/project_items.rb, spec/features/order_spec.rb, spec/helpers/research_area_helper_spec.rb, spec/models/jira/client_spec.rb, spec/models/project_item_spec.rb
While ordering normal service user needs to select mandatory "Research area" value (only research areas leafs can be selected). This value is shown on order summary view, on `project_item#show` and the value is sent to jira as a custom field while registering the service order.
References #589 
After this is merged following steps are needed:
* @wziajka needs to set following variable in the dev and prod environments: 
```
export MP_JIRA_FIELD_CP_ScientificDiscipline=10706
```
* @goreck888 or @agpul should create research areas hierarchy and reassign services into new hierarchy.
=> Select research area while ordering the service

CHANGELOG.md, spec/models/service_relationship_spec.rb
\`` is used in ruby to invoke shell command. This should not be used to define string or comment something.
=> Remove shell command invocation in one of the test

CHANGELOG.md, app/models/jira/client.rb, config/jira.yml, spec/models/jira/client_spec.rb
Tree additional fields for voucher added to jira 
CP-Platforms (string, optional)
CP-INeedAVoucher (boolean, optional)
CP-VoucherID (string, optional)
Fix #621
=> [#621] Additional custom fields for voucher in jira

CHANGELOG.md, app/mailers/project_item_mailer.rb, app/models/service.rb, app/services/jira/issue_updated.rb, app/views/project_item_mailer/aod_accepted.html.haml, app/views/project_item_mailer/aod_accepted.text.haml, app/views/project_item_mailer/aod_voucher_accepted.html.haml, app/views/project_item_mailer/aod_voucher_accepted.text.haml, app/views/project_item_mailer/created.html.haml, app/views/project_item_mailer/created.text.haml, spec/mailers/previews/project_item_preview.rb, spec/mailers/project_item_spec.rb, spec/services/jira/issue_updated_spec.rb
Two emails connected witch vouchers
When the Operator of the EGI Applications on Demand service approves a service-order request with AoDs = True and voucher = False the Marketplace will notify the user with the email:
When the Operator of the EGI Applications on Demand service approves a service-order request with AoDs = True and voucher = True the Marketplace will notify the user with the email:
Fixed #617
=> [#617] Vouchers emails

CHANGELOG.md, app/javascript/controllers/service_offer_controller.js, app/views/backoffice/services/offers/_form.html.haml, app/views/backoffice/services/offers/_offer.html.haml, app/views/services/_offer.html.haml, spec/features/backoffice/services_spec.rb, spec/features/service_spec.rb
Higher offer description textarea on edit view
Offers on views (backoffice and portal) are displayed in markdown  
Fix #662
=> [#662] Offers improvements

.tool-versions, CHANGELOG.md, README.md, db/schema.rb
This is useful to install correct `elasticsearch` version for the
project.
You can now type:
```
asdf install
```
and correct version of the `ruby`, `nodejs` and `elasticsearch` is installed.
=> Add elasticsearch version to .tool-versions

CHANGELOG.md, app/controllers/services/offers_controller.rb, app/models/offer.rb, app/policies/backoffice/offer_policy.rb, app/services/project_item/create.rb, app/views/backoffice/services/offers/_form.html.haml, app/views/services/_offer.html.haml, config/locales/en.yml, db/migrate/20190215114245_add_offer_type_to_offer.rb, db/schema.rb, spec/features/order_spec.rb, spec/models/offer_spec.rb
Starting from now offer can define customized ordering type (one of `normal`, `open_access`, `catalog`). If a type is `nil` in the offer than default is taken from the `Service::service_type`. On the first order wizard view (offer selection) only `normal` and `open_access` offers are presented - `catalog`ues are filtered out.
After this was added it was possible to add dedicated select offer buttons directly on `service#show` view:
For now, the first ordering step is not removed (so we have responsibility duplication!). I did not remove this view because it is required for "main" `Order` button to work. This is task for @abacz, @roksanaer and @toszep to agree if this should stay of some redesign of this button will be performed.
Fixes #687
=> Offer type with service type taken as default

CHANGELOG.md, app/views/project_items/show.html.haml, spec/features/my_services_spec.rb
* If `project_item.status == 'ready'` some old and no more needed
information about voucher / rating were visible - it has been removed
* Make Your review button work, replace static timelapse
('You have been using this service for 8 days. ') text to dynamic one
based on `project_item.crated_at`
Check `http://localhost:5000/project_items/<id>` view after accepting voucherable service in jira. 
If there are no double voucher / rating entries then it's all good.
After accepting service in jira check timelapse counter in 'Your review' section (it should be dynamic)
Fixes #716
=> [#716] Fix project_item details view

CHANGELOG.md, app/controllers/backoffice/services/offers_controller.rb, app/inputs/array_input.rb, app/inputs/attributes_input.rb, app/javascript/controllers/offer_controller.js, app/models/attribute.rb, app/models/offer.rb, app/models/project_item.rb, app/policies/backoffice/offer_policy.rb, app/validators/attribute_id_unique_validator.rb, app/views/backoffice/services/offers/_form.html.haml, spec/features/backoffice/services_spec.rb, spec/features/service_spec.rb, spec/models/attribute_spec.rb
SPM can add offer parameters in backoffice. 
Exemplary json to tests:
{
"id":"id1",
"type":"select", 
"label":"Number of CPU Cores",
"config":{"mode":"buttons", "values":[1, 2, 4, 8]},	
"value_type":"integer",
"description":"Select number of cores you want"
}
Fix: #653
=> [#653] Offer attribute in backoffice

CHANGELOG.md, db/schema.rb
These old tables were introduced most probably by mistake in the scope of #713, now it is time to remove it once again :smile:
=> Remove unused `orders` and `order_changes` from schema

CHANGELOG.md, app/controllers/backoffice/providers_controller.rb, app/models/provider.rb, app/models/provider_source.rb, app/policies/backoffice/provider_policy.rb, app/views/backoffice/providers/_form.html.haml, app/views/backoffice/providers/show.html.haml, app/views/backoffice/services/_form.html.haml, db/migrate/20190326203609_create_provider_sources_table.rb, db/schema.rb, spec/factories/provider_sources.rb, spec/features/backoffice/providers_spec.rb, spec/models/provider_source_spec.rb
* Add DB table storing provider's external IDs
* Add form controls to provider's backoffice form allowing setting of
external sources
* Update backoffice provider form's buttons styling to match services
* Add information about external sources to backoffice provider's detail
view
**NOTE** this feature is a blocker for #658 
Closes: #779
=> [#779] Provider external ID

CHANGELOG.md, Gemfile, Gemfile.lock, app/controllers/backoffice/services_controller.rb, app/controllers/concerns/service/searchable.rb, app/controllers/concerns/service/sortable.rb, app/controllers/services_controller.rb, app/helpers/service_helper.rb, app/javascript/controllers/order_controller.js, app/models/service.rb, app/views/services/_order.html.haml, config/initializers/elasticsearch.rb, lib/tasks/elasticsearch.rake, spec/features/service_spec.rb, spec/spec_helper.rb
Added searchkick as gem to elasticsearch. 
In elastic search are stored title, descriprion, status and rating. 
Services are searched based on title and description. Title is boosted.
Misspelling is set by default. Also added search by substring. 
Changed order of filtering and searching. Now services are firstly filtered.  
Fixed: #756, #757, #758
=> Initial usage of searchkick

CHANGELOG.md, app/views/services/nav/_categories.html.haml
Filter query params were removed by @jarekzet during #775, here I'm restoring original behavior.
=> Link to all services should contain all filter params

app/models/project_item.rb
`validates_associated :property_values` was moved to `Customization` concern but was not removed from `ProjectItem` class.
No changelog entry because this is a fix for the change already mentioned in changelog.
=> Remove duplicated validates_associated

CHANGELOG.md, app/controllers/profiles/affiliations_controller.rb
From now query for user affiliations includes user id.
Before this fix query for edit and delete affiliation included just iid which is counted from 1 for every user, so query has returned all affiliations with current iid.
=> [#803] Fix edit and delete affiliation

CHANGELOG.md, spec/features/service_spec.rb
When a filter is selected it is by default opened, clicking on the collapse button will close it. This triggers an error in the spec (what worse this was random failing test - it seems like from time to time JS was not quick enough to add hide class and this test passed).
=> Don't close filter in the test

CHANGELOG.md, app/controllers/backoffice/services_controller.rb, app/controllers/concerns/service/searchable.rb, app/controllers/services_controller.rb, spec/controllers/concerns/searchable_spec.rb
Results were duplicated in the following scenario:
* only the filter was used (no elasticsearch) to limit shown services
* service belongs to 2 or more selected elements in the multi-select filter
`distinct` solves this issue.
=> Do not duplicate presented services

app/javascript/controllers/autocomplete_controller.js
When user choose category url are changing in search_url_controller.js. That's why autocomplete url looked like  .../services/c/service_autocomplete not .../service_autocomplete and that's why search tips didn't work
Fix #852
=> [#852] Fixed url createion in autocomplete_controller.js

CHANGELOG.md, app/views/projects/_empty_project.html.haml
Right now it looks like that
Fixes #839
=> Improve empty project description

CHANGELOG.md, app/javascript/packs/application.js, app/javascript/packs/sort_filter.js, app/views/services/_filters.html.haml, app/views/services/index.html.haml
The bug was connected with a difference in how rails and js escaping query params. This issue was solved by simplifying the way how hidden query value param is added to the filtering section. Previously it was done using JS, not it is done while rendering the page.
Fixes #826
=> Fix spaces included instead of spaces when filtering

CHANGELOG.md, app/controllers/concerns/service/filterable.rb, spec/features/service_spec.rb
It was removed because we don't have enough service ratings yet.
Fixes #858
=> Remove rating filter from the view

CHANGELOG.md, app/controllers/concerns/service/autocomplete.rb, app/models/service.rb, app/views/backoffice/services/_search.html.haml, config/routes.rb
The pundit scope was used instead of searchkick scope to resolve problems with not showing draft services after search in backoffice. That's why, the autocomplete concer was turned into a helper.
=> Deleted elasticsearch scope_import and use pundit scope

CHANGELOG.md, app/controllers/services_controller.rb, app/policies/service_policy.rb, config/locales/pundit.en.yml, spec/features/service_spec.rb
**What's in this PR?**
This PR fixes bug which is described in https://app.zenhub.com/workspaces/cyfronet-fid-5b1e4b786c29461038c37df5/issues/cyfronet-fid/marketplace/891 
Changes:
Add authorization for services
Add policy blocking access to the draft if user isn't service_portfolio_manager, 
because this is a kind of sample service view and I won't block to allow managers to get this view.
=> [#891] Block access to the draft service

CHANGELOG.md, app/views/services/_filters.html.haml
When a filter is applied sort order is maintained. 
Fixes #922
=> Maintaining sort order when filters are applied

CHANGELOG.md, app/views/projects/_project.html.haml
By default, all projects are expanded now on projects index view.
Fixes #924
=> Expand all projects on projects index view

CHANGELOG.md, app/controllers/projects_controller.rb, spec/features/order_spec.rb
Redirection to project edit view on project creation failure while ordering is fixed. User stays in this modal after fix:
Fixes #919
=> [#919] Stay in project modal when project empty while ordering

CHANGELOG.md, app/controllers/users/omniauth_callbacks_controller.rb, spec/support/helpers/omniauth_helper.rb
Fixes redirect to the root page after logging in
Fixes #798
=> [#798] omniauth.origin is used when applicable to redirect

CHANGELOG.md, app/controllers/backoffice/services_controller.rb, app/models/service.rb, app/policies/backoffice/offer_policy.rb, app/policies/backoffice/service_policy.rb, app/views/backoffice/services/show.html.haml, spec/features/backoffice/services_spec.rb, spec/models/service_spec.rb, spec/policies/backoffice/offer_policy_spec.rb, spec/policies/backoffice/service_policy_spec.rb
Service draft can be now edited by the owner. I'm waiting for decision if the owner should be able to edit service draft offers as well.
Fixes #983
=> Service owner can edit service draft

app/views/projects/_details.html.haml
Old field name was used instead of new one
=> Fix field naming problem

app/models/jira/client.rb, lib/jira/project_migrator.rb, lib/tasks/projects_migrate_from_affiliation.rake
This is needed since we did it wrong and after the release, we will have nil values in the place where such values should not occur. This missing information should be filled in by the project owner, but until this happened we need to perform a set of migrations (migrated data from affiliation to project, register project in Jira). To make it happened we need to update not valid (yet) project. This is the reason why
validation is turned on on these migration tasks.
=> Turn off model validation on project migration tasks

CHANGELOG.md, app/controllers/home_controller.rb, spec/features/home_spec.rb
Quick fix for not public services that are currently shown (eIC services are not visible in catalogue but homepage shows them even though they are Drafts)
=> Showing only published services at the homepage

CHANGELOG.md, app/controllers/concerns/project/authorize.rb, app/controllers/projects/adds_controller.rb, app/controllers/projects/archives_controller.rb, app/controllers/projects/conversations_controller.rb, app/controllers/projects/services_controller.rb
Fetching project and checking if the project can be displayed by the user logic was duplicated in many controllers. By reusing `Project::Authorize` concern we can avoid duplication.
=> Reuse `Project::Authorize` concern

CHANGELOG.md, app/policies/backoffice/service_policy.rb, app/views/backoffice/services/_form.html.haml, app/views/backoffice/services/show.html.haml, db/migrate/20190816135743_remove_terms_of_use_in_service.rb, db/schema.rb, lib/tasks/dev.rake, spec/factories/services.rb, spec/features/backoffice/services_spec.rb
Delete terms_of_use field in the service forms, models and views
Fixes #954
=> [#954] Delete "terms of use" from form in backoffice

CHANGELOG.md, app/models/categorization.rb, app/models/service.rb, db/migrate/20190919073353_remove_services_count_from_category.rb, db/schema.rb, spec/models/category_spec.rb, spec/models/service_spec.rb
Category `counter_cache` is not used anymore. Instead, counters are calculated using elasticsearch. This was the reason for deleting this field and all the code connected with calculating counters for
categories.
=> Remove categories counter cache

CHANGELOG.md, app/models/category.rb, app/models/research_area.rb, db/migrate/20190919085356_change_category_name_uniq_scope.rb, db/migrate/20190919090322_change_research_area_name_uniqueness_scope.rb, db/schema.rb, spec/models/category_spec.rb, spec/models/research_area_spec.rb
Starting from now we will be able to create following structure:
```
- foo
- foo
- bar
- bar
```
but still it will be forbidden to create:
```
- foo
- foo
```
Fixes #1115
=> Category and ResearchArea name is parent scoped

CHANGELOG.md, app/controllers/backoffice/services/publishes_controller.rb, app/controllers/backoffice/services_controller.rb, app/helpers/backoffice/services_helper.rb, app/models/filter/status.rb, app/models/service.rb, app/policies/backoffice/service_policy.rb, app/policies/service_policy.rb, app/services/service/publish.rb, app/views/backoffice/services/show.html.haml, config/locales/simple_form.en.yml, spec/features/backoffice/services_spec.rb, spec/models/filter/status_spec.rb, spec/policies/backoffice/service_policy_spec.rb, spec/policies/service_policy_spec.rb, spec/services/service/publish_spec.rb
The new state was added to service: `unverified`. It means that service is published (it is visible to end-user) but is not confirmed by onboarding team.
Fixes #1103
=> Publish service as unverified service

CHANGELOG.md, app/models/attribute.rb
If user pass url in to attribute input JSON::Schema::JsonParseError was returned([bug](https://sentry.dev.cyfronet.pl/fid/marketplaceproduction/issues/8643/)). It happened because during validation url was changed to html from this page. For now all strings was parsed to URI during data initialization([code](https://github.com/ruby-json-schema/json-schema/blob/ab1253a874f05a811fdb3280ca1f77ebc9af2902/lib/json-schema/validator.rb#L569)) 
This could be the cause of future attacks.
=> Disable parsing during data validation

app/controllers/backoffice/services_controller.rb, app/policies/backoffice/service_policy.rb, app/views/backoffice/services/_form.html.haml, spec/features/backoffice/services_spec.rb, spec/policies/backoffice/service_policy_spec.rb
When upstream in service is set to EIC some fields (which are updated from EIC should be disabled)
The list of fields which should be disabled:
* `logo`
* `title`
* `description`
* `tagline`
* `connected_url`
* `places`
* `languages`
* `dedicated_for`
* `terms_of_use_url`
* `access_policies_url`
* `sla_url`
* `webpage_url`
* `manual_url`
* `helpdesk_url`
* `tutorial_url`
* `phase`
* `service_type`
* `providers`
Closes: #1123
=> [#1123] Disable fields in service's edit with eid

CHANGELOG.md, spec/features/search_spec.rb, spec/features/service_question_spec.rb, spec/features/service_spec.rb
Deep cleanup for all specs related to service browsing. Specs related to concrete features (e.g. search, filter, ask a question) were moved to dedicated files. Some tests which test case was duplicated by other tests were removed. Also, all `sleep` was eliminated from the spec code.  This was possible thanks to this simple trick:
https://stackoverflow.com/questions/41854537/capybara-poltergeist-wait-for-javascript-completions
=> Clean service browsing specs

app/javascript/controllers/multicheckbox_controller.js
Fuzzy search distance is set to 1. This allows us to have an exact match for providers.
No changelog entry, because it is a modification of the feature already mentioned in this sprint changelog.
=> Exact match in filter search

CHANGELOG.md, app/javascript/stylesheets/_preview.scss, app/views/backoffice/services/preview.html.haml
Add css class "preview" to the preview disabling order buttons
Fixes #1182
=> Disable order button in service preview

CHANGELOG.md, app/controllers/application_controller.rb, app/controllers/concerns/devise/store_location.rb, app/controllers/services/offers_controller.rb, app/controllers/users/omniauth_callbacks_controller.rb, config/environments/development.rb, spec/features/order_spec.rb, spec/support/helpers/omniauth_helper.rb
Offers selection is made available for anonymous users. There is one problem: while the user is clicking on a specific offer then after checkin login session is cleared and the selected offer is not available. This only happened in the development environment. The solution to this issue was to change the development `cache_store` to `memory_store`. 
There is another change connected with redirecting user after a successful login. Before ` request.env["omniauth.origin"]` was used and it was done in the PR #941 as a solution for #798. After going back to the default implementation (method `after_sign_in_path_for` was removed from `app/controllers/users/omniauth_callbacks_controller.rb`) I was not able to reproduce the issue described in #798 but is require to double-check (@bwilk can you do …
=> Offer selection available for anonymous user

CHANGELOG.md, Gemfile, Gemfile.lock, app/models/jira/client.rb, app/models/project.rb, app/models/service.rb, app/validators/mp_url_validator.rb, spec/features/service_spec.rb, spec/models/service_spec.rb, spec/validators/mp_url_validator_spec.rb
Fixed url validation occured https://sentry.dev.cyfronet.pl/fid/marketplaceproduction/issues/8645/
Checking if spaces are in the url except in parameters.
Feel free to propose other names for MpUrlValidator
Its solution before merge this pr https://github.com/perfectline/validates_url/pull/85 after that MpUrlValidator can be replaced to validates_url
=> Fix validation url

CHANGELOG.md, lib/import/eic.rb
* Fix EIC import - in case of model validation errors log them, and
don't import that particular service, instead of crashing whole task
=> [HOTFIX] EIC Import, invalid EIC urls

CHANGELOG.md, db/seeds.rb
Before there was `nil` as a result all order views have corrupted translations.
=> Use service type as order type while seeding data

CHANGELOG.md, app/controllers/services/application_controller.rb, app/controllers/services/configurations_controller.rb, app/controllers/services/information_controller.rb, app/controllers/services/offers_controller.rb, app/controllers/services/summaries_controller.rb, app/helpers/order_nav_helper.rb, app/models/project_item/wizard.rb, app/views/layouts/order/_nav.html.haml, app/views/services/configurations/show.html.haml, app/views/services/information/show.html.haml, app/views/services/offers/show.html.haml, app/views/services/summaries/show.html.haml, config/locales/en.yml, config/routes.rb, db/schema.rb, spec/features/add_item_to_project_spec.rb, spec/features/order_spec.rb
The code responsible for deciding if a step should be visible was moved to the wizard step class. This leads to wizard, controllers, and views refactoring. As a conclusion now we can easily add new steps to the wizard, add visibility logic, etc.
This PR should be merged after #1226 is merged.
=> Hide service order configuration step when no data to be configured

CHANGELOG.md, app/controllers/concerns/service/searchable.rb
Change highlights from bold to mark
Add showing highlights to the tagline
Fixes #1095
=> [#1095] Change highlights in search results

CHANGELOG.md, app/controllers/services/cancels_controller.rb
For non logged-in user order cancel link was redirecting
to the login page. This commit fixes it.
=> Fix cancel order redirection

app/views/services/information/show.html.haml, config/brakeman.ignore, spec/features/order_spec.rb
If the service was ordered and the website was not blank, "Link" was displayed
Now link to external service is displayed only when offer is not orderable and offer.website is not blank.
=> Fix displaying link to external services

CHANGELOG.md, app/services/jira/comment_created.rb, spec/services/jira/comment_created_spec.rb
This is an extraction (and small improvements) of  "don't register internal messages" feature from #1276. Basically it skips internal messages reported by Jira.
=> Don't register internal messages

CHANGELOG.md, app/javascript/controllers/paragraph_controller.js, app/views/services/_offer.html.haml, app/views/services/offers/_description.html.haml, app/views/services/offers/_offer.html.haml, app/views/services/offers/_parameters.html.haml
Added _description template (/app/views/services/offers/_description.html.haml) with one unified service description.
Fix for #1284
=> 1284 unify offer view

CHANGELOG.md, app/helpers/attributes_helper.rb
In the offer view disabled all input attributes, because they haven't minimum and maximum values, so they can be treated the same way like string attribute.
Fixes #1285
=> [#1285] Disable visibility of input type attribute

CHANGELOG.md, app/models/jira/client.rb
If the service does not have a category, job registration in jira fails. Its connected with fact that Category is not required. 
In this PR if If the service does not have a category, null is send to jira.
=> Jira client. Return nil if service doesn't have category

app/models/usage_report.rb
After testing statistics on production data I discovered that some of
the projects do not have a country of origin filled in. To solve this
issue additional reject filter was added.
No changelog entry because this is a fix to feature not yet released which has dedicated changelog entry.
=> Reject projects without country in usage statistic

CHANGELOG.md, app/controllers/designsystem_controller.rb, app/views/designsystem/demo.html.haml, app/views/designsystem/index.html.haml, app/views/layouts/designsystem.html.haml, config/brakeman.ignore, config/routes.rb
This introduces way to create static pages available only in development
mode where UI team can work on components which will be used in
marketplace.
To enter this section visit: `http://localhost:5000/designsystem`. If
you want to create new static page in this scope just create file in
`app/views/designsystem` directory (take a loot at
`app/views/designsystem/demo.html.haml` which is accessable using
`http://localhost:5000/designsystem/demo`).
=> Design system static pages

CHANGELOG.md, app/controllers/application_controller.rb, app/controllers/backoffice/categories_controller.rb, app/controllers/home_controller.rb, app/models/category.rb, app/models/research_area.rb, app/policies/backoffice/category_policy.rb, app/policies/backoffice/research_area_policy.rb, app/views/backoffice/categories/_form.html.haml, app/views/backoffice/categories/index.html.haml, app/views/backoffice/categories/show.html.haml, app/views/backoffice/research_areas/_form.html.haml, app/views/backoffice/research_areas/index.html.haml, app/views/backoffice/research_areas/show.html.haml, app/views/home/_products.html.haml, lib/tasks/whitelabel.rake
First feature connected with Whitelabel: category and research area logos were moved to active storage. A logo is not mandatory, if not present than default one is used. 
As a part of this PR I'm delivring 2 rake tasks: 
* `rails whitelabel:migrate_category_logos`
* `rails whitelabel:migrate_research_area_logos`
these tasks need to be invoked on production to attach existing logos to record. 
I will create also follow up PR (something like `whitelabel-cleanup`) where logos and outdated tasks will be removed from the repository. This PR will be merged into the `master` branch after the release.
=> Category and research area logos in active storage

CHANGELOG.md, Gemfile.lock
New version is not compatible with `redis-rack` yet.
=> Downgrade rack to 2.0.7

app/javascript/packs/designsystem.js, app/javascript/stylesheets/designsystem.scss, app/views/layouts/designsystem.html.haml
For the design system, @jswk and @abacz want to have separate js and csses. This PR introduces a dedicated webpack `designsystem` pack for this purpose.
No changelog entry because there is already one connected with design system.
=> Dedicated pack for design system

app/javascript/designsystem/index.js
During webpack cleanup, the design system definition was not moved. Here I'm fixing this issue.
No changelog entry, since the design system, has its changelog entry already.
=> Restore configuration for designsystem assets build

CHANGELOG.md, app/controllers/api/services_controller.rb, config/routes.rb
Add api endpoint for downloading services information
for ARGO monitoring tool
JSON is available from #{root_path}/api/services
Fixes #1365
=> [#1365] Services information for monitoring tool

CHANGELOG.md, app/controllers/home_controller.rb, app/models/project_item.rb, app/models/service.rb, db/migrate/20200128142804_add_project_items_count_to_services.rb, db/schema.rb, lib/tasks/counter_cache.rake
Change the way of sorting services by popularity
After the fix it is populated based of number of orders
Fixes #1049
After merge and deploy in a production instance I'll ask to run task `rake service_counter` to get proper counter values.
=> [#1049] Service popularity based on number of orders

CHANGELOG.md, README.md, config/application.rb, config/webpack/environment.js
Thanks to @michal-szostak we have now a way to customize CSS files. This PR contains this change and 2 additions elements:
* Starting from now we can use one ENV variable (`$CUSTOMIZATION_PATH`) to point to the directory where customization is located
* Not that obvious bug with hierarchical locales was fixed. We need to add
```ruby
config.i18n.load_path += Dir[Rails.root.join('config', 'locales', '**', '*.{rb,yml}')]
```
even if the customization directory is defined. What is more it need to be added before customization dir is defined.
=> Custom scss loader and unified way to define customization directory

CHANGELOG.md, README.md
Readme description for outdated `playground` mechanism was updated in favour of
`designsystem` mechanism.
=> Update outdated playground description in favour of designsystem section

CHANGELOG.md, app/controllers/admin/lead_sections_controller.rb, app/helpers/lead_section_helper.rb, app/javascript/stylesheets/_bootstrap-customizations.scss, app/models/lead_section.rb, app/policies/lead_section_policy.rb, app/views/home/index.html.haml, app/views/leads/_error.html.haml, config/locales/simple_form.en.yml, spec/features/home_spec.rb
Displayed lead-error (Cannot find lead_section with slug) for admin user. Plain user cannot see this message.
=> Display "lead-error" only to admin user

CHANGELOG.md, app/views/backoffice/services/index.html.haml, app/views/services/_filters.html.haml, app/views/services/_index.html.haml, app/views/services/index.html.haml
On the main services view, we had some outdated variables which were not used anymore (not even defined). Here I'm doing the simple cleanup.
=> Remove outdated filter variables

CHANGELOG.md, app/views/services/_index.html.haml, app/views/services/_service.html.haml, config/breadcrumbs/marketplace.rb
This is an alternative implementation of the #1398. The difference here is that we are not storing anything in the user session, but query param is used to give a hint about the category which was used to access this service. This has this advantage, that problems with entering services from pasting service URL does not exist (the service category breadcrumb is URL dependent). What is more, I'm checking if selected service has this category (if not default one is shown).
Fixes #1099
=> Use category used used to enter service in breadcrumbs

CHANGELOG.md, app/controllers/api/services_controller.rb
Change titles of fields for JSON services api
This is necessary because the tools using this api have parsers set to the old values.
=> Back to the old json services api schema

CHANGELOG.md, app/helpers/backoffice/services_helper.rb, app/views/backoffice/services/_service.html.haml, app/views/backoffice/services/show.html.haml, lib/import/eic.rb, spec/features/backoffice/services_spec.rb, spec/lib/import/eic_spec.rb
Add automatic offer creating by service import from external sources.
Add warnings on the backoffice services view and backoffice service view about offers statuses.
Fixes #945
=> [#945] automatic offer creating

CHANGELOG.md, app/controllers/concerns/service/searchable.rb, app/views/services/nav/_categories.html.haml, config/breadcrumbs/marketplace.rb, spec/features/filter_spec.rb
Back to the services view from service using breadcrumbs
keeps filters and query settings
Fixes #914
=> [#914] Service breadcrumbs allow filters settings

CHANGELOG.md, app/views/layouts/_navbar.html.haml, app/views/layouts/_sections.html.haml
Change name from `Info` to `Portal Home`
=> Change link description for portal home

CHANGELOG.md, config/routes.rb
Add redirects for report and question modal,
which don't have pure html view:
- root path for report modal
- service path for question
=> Fix modal routes

CHANGELOG.md, app/controllers/backoffice/services/offers_controller.rb, app/controllers/backoffice/services_controller.rb, app/controllers/concerns/service/autocomplete.rb, app/controllers/services_controller.rb, app/javascript/app/controllers/autocomplete_controller.js, app/javascript/stylesheets/_header.scss, app/models/offer.rb, app/models/service.rb, app/views/backoffice/services/_search.html.haml, app/views/backoffice/services/offers/_offer.html.haml, app/views/services/_offer.html.haml, app/views/services/_search.html.haml, app/views/services/autocomplete/_offer_item.html.haml, app/views/services/autocomplete/_service_item.html.haml, app/views/services/autocomplete/list.html.haml, spec/features/search_spec.rb, spec/spec_helper.rb
Added offers to autocomplete results.
After click on displayed offers users are redirected to offer on service page by anchor.
Only published offers are indexed and if the service has more than two offers.
=> Offers in autocomplete

app/views/backoffice/services/_service.html.haml
Without changelog because its fix to previous unrealised feature
=> Fix highlight of service title and tagline in backoffice

CHANGELOG.md, app/views/services/sidebar/_links.html.haml, app/views/services/sidebar/_text.html.haml
Fix displaying empty links, in particular helpdesk e-mail
Fixes #1422
=> [#1422] Fix displaying details in service description

app/models/parameter.rb, app/models/parameter/constant.rb, app/policies/backoffice/offer_policy.rb, app/views/parameters/template/_attribute.html.haml, config/locales/views/parameters/template.en.yml, spec/factories/parameters.rb, spec/models/parameter/constant_spec.rb
Missing parameter type - Constant added. It is serialized to `attribute` type.
No changelog since there is already changelog connected with parameter UI.
=> Constant parameter type

CHANGELOG.md, db/data.yml, lib/tasks/dev.rake
The problem was connected with the situation that parameters are now converted into the model.
=> Fix `dev:prime` after introducing offer parameters

CHANGELOG.md, app/models/service.rb, app/models/service/search.rb
This is another try to fix the research area issue in the filter zone. The issue
is connected with the research area tree-like structure. The intuition says
that parents should count also its children.
Here I'm trying to do exactly this by adding all parents to service
research areas elaticsearch record.
Closes #1230
=> Fix research area counter issue

CHANGELOG.md, app/controllers/projects/services/opinions_controller.rb, app/controllers/services/summaries_controller.rb, app/jobs/matomo/send_request_job.rb, app/services/matomo/create_event.rb, app/views/layouts/_head.html.haml, app/views/layouts/_matomo.html.haml, app/views/services/show.html.haml, config/application.rb, config/google_api_key.json, config/sidekiq.yml
This PR contains integration with PC matomo tracking service.
Service pages visits, orders and ratings are marked as matomo events:
- Category of events => "Service"
- Order/AddToProject => "AddToProject"
- Service rate => "Rate"
- Page visit => "Visit"
With event name => service ID recognizable by PC applications
For rating event value is `ServiceOpinion.service_rating`
For test case you need:
- visit a few services pages
- add to project service
- rate a service
Then I'll check if all cases make events for matomo
=> Add matomo tracker for marketplace

CHANGELOG.md, app/controllers/concerns/service/searchable.rb
Allow highlights only when query phrase has at least 3 signs
Fixes #1471
=> [#1471] Fix highlights in queries

CHANGELOG.md, app/views/backoffice/services/show.html.haml, app/views/comparisons/show.html.haml, spec/features/backoffice/services_spec.rb
Fix displaying empty fields like service phase
and service_type in comparison view
Fixes #1514
=> [#1514] Fix empty fields in comparison view

CHANGELOG.md, app/models/project.rb, db/migrate/20200521150023_change_project_default_timestamp.rb, db/schema.rb
Project creation_at isn't automatically overridden because have default on db.
=> Fix project timestamp

CHANGELOG.md, README.md, bin/server
[overmind](https://github.com/DarthSim/overmind) is much more powerful than `foreman` to start multiple processes during development. It uses tmux to start each process. As a result, you can attach/detach/restart each process separately. What is more, it works nicely with the `byebug` (no more starting `rails s` separately when debugging).
`overmind` will be used only when it is defined in the classpath, otherwise `foreman` is used as it used to be.
=> Use overmind instead of foreman in present in the classpath

CHANGELOG.md, app/controllers/services/application_controller.rb, app/views/layouts/order.html.haml
Remove offer title if there's just one offer
Fixes #1572
=> [#1572] Remove tagline and offer title in ordering form

CHANGELOG.md, app/models/service.rb
In the service view change "support" section title
to links
Fixes #1574
=> [#1574] Change "support" section title to "links" in service

CHANGELOG.md, app/views/backoffice/services/_search.html.haml, app/views/services/_search.html.haml
Remove duplicated "sort" ids in services index
Fixes #1424
=> [#1424] Remove duplicated ids on services page

app/helpers/backoffice/services_helper.rb, app/jobs/service/delete_job.rb, app/models/service.rb, app/policies/backoffice/offer_policy.rb, app/policies/backoffice/service_policy.rb, app/services/jms/manage_message.rb, app/services/service/delete.rb, app/views/backoffice/services/show.html.haml, spec/factories/jms_xml_provider.rb, spec/factories/jms_xml_service.rb, spec/jobs/service/delete_job_spec.rb, spec/policies/backoffice/offer_policy_spec.rb, spec/policies/backoffice/service_policy_spec.rb, spec/services/jms/manage_message_spec.rb, spec/services/service/delete_spec.rb
Service can be deleted only by JMS
Service deletion mean that Service status is set to "deleted"
Deleted service cannot be edited, published and offers cannot be edited, deleted, published/draft or added.
Deleted service isn't shown for users. In bacoffice are displayed with badge "deleted"
=> JMS service deletion

app/jobs/service/pc_create_or_update_job.rb, app/services/jms/manage_message.rb, app/services/service/pc_create_or_update.rb, lib/import/eic.rb, spec/factories/eic_services_response.rb, spec/factories/services.rb, spec/lib/import/eic_spec.rb, spec/services/jms/manage_message_spec.rb, spec/services/service/pc_create_or_update_spec.rb
Only accept the latest changes from jms.
Changed eic import of last_update to date format because we receiving int 
For provider this changes can be appied if Porvider model will be 
To merge after  #1601
=> Update message order 

app/controllers/pages_controller.rb, app/views/home/_communities.haml, app/views/pages/target_users.html.haml, config/breadcrumbs/marketplace.rb, config/locales/views/pages/en.yml, config/routes.rb
Added page with listed target_users:
Changed "target groups" to "target users" in link
=> Added target_users page to home

CHANGELOG.md, app/helpers/forms_helper.rb, app/inputs/array_input.rb, app/javascript/app/controllers/service_controller.js, app/models/service.rb, app/views/backoffice/services/_array_field.html.haml, app/views/backoffice/services/_form.html.haml, config/locales/simple_form.en.yml
In the backoffice service form added remove link for array fields: multimedia, use_cases_url, changelog, related_platforms etc.
=> Add `remove array element` in forms

CHANGELOG.md, app/helpers/backoffice/services_helper.rb, app/models/service.rb, app/services/service/pc_create_or_update.rb, config/locales/simple_form.en.yml, lib/import/eic.rb
When resource has validation errors it saves as resource
with errored state
PR to fixes branch, copy of PR #1687
=> Add `errored` status to the imported resources

CHANGELOG.md, app/services/service/pc_create_or_update.rb
Deactivation in PC doesn't update resource,
so flag is_newer_update was set to false.
x !> x
Changed condition to x >= x
=> Fix change resource to draft via JMS

CHANGELOG.md, app/controllers/services_controller.rb, app/views/services/_index.html.haml
Disable split experiment in recommendations view.
May fix possible problem with puma memory use increasing and overflow
=> [HOTFIX] Disable split experiments

CHANGELOG.md, app/views/comparisons/show.html.haml, spec/features/comparison_spec.rb
- added more fields
- using https://docs.cyfronet.pl/display/FID/RDT+%28ERV%29+Resource+Profile as a reference point for fields labels after slack conversation with @bwilk 
Closes #1716
=> [#1716] Add more fields to the comparison view

CHANGELOG.md, Procfile, Procfile.dev, config/application.rb, config/sidekiq.yml
Add missing ActiveStorage analysis and purge queues
to sidekiq jobs and add queues names to config before update
rails to 6.1
Fixes #1731
=> [#1731] Add ActiveStorage queues to sidekiq configuration

CHANGELOG.md, lib/import/eic.rb, spec/lib/import/eic_spec.rb
Run import:eic task with `resource` api
instead of deprecated `service` api
Fixes #1746
=> [#1746] Move from deprecated service to resource API in PC

CHANGELOG.md, app/helpers/recommender_system_helper.rb, app/views/services/_index.html.haml, config/initializers/split.rb, spec/features/service_recommendations_spec.rb, spec/helpers/recommender_system_helper_spec.rb
- make tests green
Closes #1725
=> [#1725] Fix split rspec issues

CHANGELOG.md, app/views/backoffice/services/index.html.haml, app/views/backoffices/show.html.haml, app/views/services/_index.html.haml
This PR closes #1726  issue that include turning off recommendations in the backoffice.
* **Old behaviour**
Recommendations are visible in `services catalog` and in `Owned resources` view at backoffice.
* **New behaviour**
Now recommendations are displayed only in `services catalog` - not in backoffice `Owned resources` view.
On master turn on recommendations and go to both `/services` and `/backoffice/services`. You should see recommendations on services lists in both cases.
On this branch turn on recommendations and  go to both `/services` and `/backoffice/services`. You should see recommendations on services list only in the first case.
PS.: **How to turn on recommendations**: go to `Admin` -> `AB experiments`, choose version `v1` or `v2` and click `Force for current user` button.
=> [#1726] remove recommendations from services list at backoffice

Gemfile, Gemfile.lock, config/puma.rb
- set up the gem to:
- kill largest worker
- prevent cyclic kill of all workers
**PUMA_KILLER_ENABLE**
Default: false
_Turn on `Puma workers killer`_
**PUMA_KILLER_MACHINE_RAM_MB**
Default: 7168 (MB)
_All available RAM in MB for Machine_
**PUMA_KILLER_RAM_UTILIZATION_PERCENT**
Default: 0.07 (500MB)
_Percent of all available RAM that can be in use by `Puma`_
**PUMA_KILLER_CHECK_FREQ**
Default: 10 sec
_Frequency of `Puma worker killer` RAM usage checkout_
On each worker kill:
_"Worker {@cluster.largest_worker.nr} (pid: {@cluster.largest_worker.pid}) - will be terminated"_
=> [#1767] Add and configure Puma Killer

CHANGELOG.md, app/helpers/service_helper.rb, app/javascript/stylesheets/_bootstrap-customizations.scss, app/models/country.rb, app/views/services/details/_array.html.haml, spec/helpers/service_helper_spec.rb
On local instance: Resource with geographical_availabilities: {EZ,AT,EU,PL,FR,EO,WW,UK,DK}
Closes #1800
=> 1800 details view countries order

CHANGELOG.md, app/controllers/backoffice/services_controller.rb, app/controllers/services/details_controller.rb, app/controllers/services/opinions_controller.rb, app/controllers/services/ordering_configurations_controller.rb, app/controllers/services_controller.rb, app/views/backoffice/services/preview.html.haml, app/views/services/_related.html.haml, app/views/services/details/index.html.haml, app/views/services/opinions/index.html.haml, app/views/services/ordering_configurations/show.html.haml, app/views/services/show.html.haml
Change the title of related resources section
in details and opinions
from "Suggested compatible resources"
to "Related resources"
Closes #1749
=> [#1749] Change title for related_resources in details

CHANGELOG.md, app/views/layouts/common_parts/services/_default_parameters.html.haml, app/views/layouts/common_parts/services/_offer.html.haml, app/views/layouts/common_parts/services/_parameters.html.haml
Add information when no parameters added in offer box in ordering_configuration and in backoffice
=> [HOTFIX] Fix no parameters info in offer box

CHANGELOG.md, app/helpers/service_helper.rb, app/javascript/stylesheets/_bootstrap-customizations.scss, app/models/service.rb, app/views/services/_about.html.haml, app/views/services/_categorization.html.haml, app/views/services/_header.html.haml, app/views/services/_index.html.haml, app/views/services/_paginate_simple.haml, app/views/services/_recommendation_panel_v1.html.haml, app/views/services/_recommendation_panel_v2.html.haml, app/views/services/_search.html.haml, app/views/services/_service.html.haml, app/views/services/_service_details.html.haml, app/views/services/_tabs.haml, app/views/services/index.html.haml, app/views/services/nav/_category.html.haml
Resource with RO and RP's
Resource only with RO
Closes #1833
=> Representation of the RO and RP in the resource / resource list

CHANGELOG.md, app/services/importers/service.rb, spec/factories/eic_services_response.rb, spec/fixtures/files/eic_import_output.json, spec/lib/import/eic_spec.rb
- duplicated providers were crashing update of the resource
requires:
bundle exec import:eic
before import
after import
Closes #1841
=> [#1841] Fix duplicated providers in import:eic

CHANGELOG.md, app/models/service/search.rb, spec/controllers/concerns/searchable_spec.rb
Filtering by providers includes `resource_organisation`
and `providers` associations
Fixes #1826
=> [#1826] Include `resource_organisation` in provider's filter

CHANGELOG.md, app/views/services/details/_array.html.haml
Geographical availabilities in the resource details are
links to filters now instead of plain text
Fixes #1829
=> [#1829] Change Geographical availabilities to filters links

CHANGELOG.md, app/controllers/concerns/service/categorable.rb, app/controllers/home_controller.rb, app/helpers/service/sidebar_helper.rb, app/models/concerns/importable.rb, app/models/service.rb, app/models/vocabulary/pc_category.rb, app/services/importers/service.rb, app/views/backoffice/services/_form.html.haml, app/views/comparisons/show.html.haml, app/views/home/products/_cards.html.haml, app/views/layouts/_footer.html.haml, app/views/profiles/_form.html.haml, app/views/services/nav/_category.html.haml, db/schema.rb, db/vocabulary.yml, docs/upgrade/3.9.0.md, lib/tasks/rdt.rake, spec/factories/vocabularies/pc_categories.rb, spec/features/backoffice/services_spec.rb, spec/lib/import/eic_spec.rb, spec/services/service/pc_create_or_update_spec.rb
Change `rake rdt:add_vocabularies` pc_categories to categories
Change pc_categories to categories in importers
Remove model `Vocabulary::PcCategory`
Fix counters for categories
Fix duplicated "Other" ScientificDomain
Add docs for upgrade
Closes #1774, #1860
=> [#1774] Migrate PC categories to MP categories

CHANGELOG.md, app/policies/service_policy.rb, app/services/service/pc_create_or_update.rb, app/views/backoffice/services/show.html.haml, app/views/services/_errors.html.haml, app/views/services/ordering_configurations/show.html.haml, app/views/services/show.html.haml, db/migrate/20210316161711_add_errored_to_service_source.rb, db/schema.rb
Change logic, now errored resources
are displayed on resources list
Errors are saved in service_source as errored field.
Fixes #1803
=> [#1803] Display sync error for errored resources

app/javascript/app/controllers/multicheckbox_controller.js, spec/features/comparison_spec.rb
- Offset of searching word is 100 letters
- Search algorithm now looking for words more strictly
- Min length of matching sub-string is 3
What was expected?
Provider `test-cyfronet` should be found by searching phrase `cyfronet`
=> [#1828] Improve all search fileds at services page in sidebar

CHANGELOG.md, app/components/services/inline_order_url_component.rb, app/models/concerns/offerable.rb, app/models/usage_report.rb, app/policies/backoffice/offer_policy.rb, app/services/service/create.rb, app/services/service/update.rb, app/views/backoffice/services/offers/_form.html.haml, app/views/components/services/information_description_component/_external.html.haml, spec/components/services/information_description_component_spec.rb, spec/components/services/inline_order_url_component_spec.rb, spec/factories/offers.rb, spec/features/order_spec.rb, spec/models/usage_report_spec.rb
Fix conditions for external ordering type
Fix query in executive panel
Add hidden `internal` field to the Offer's form
Fixes #1859
=> [#1859] Fix externally ordered resources

CHANGELOG.md, app/controllers/concerns/service/categorable.rb, app/controllers/home_controller.rb, app/views/home/index.html.haml, app/views/services/_search.html.haml, spec/features/categories_spec.rb, spec/features/search_spec.rb
* If non existent category link would result in 404 it's
redirected to :services
* In navbar search "Other" is always at the end
Fixes #1872, fixes #1886
=> [#1872, #1886] Handle old categories

app/javascript/stylesheets/_ref_designsystem.scss, app/views/services/_recommendation_v1.html.haml, app/views/services/_recommendation_v2.html.haml
Bug:
when searching with multiple words that will be highlighted the end result isn't pretty :) 
Final solution:
remove highlights from the recommended section.
no changelog.
Closes #1908
-------------------------------
Search two worded highlights:
v1:
v2:
=> Fix html tags in recommendation boxes

CHANGELOG.md, app/views/services/_recommendation_panel_v1.html.haml, app/views/services/_recommendation_v2.html.haml, spec/features/service_recommendations_spec.rb
Change 'RECOMMENDED' to 'SUGGESTED' for recommendation boxes.
Reason for change https://infographics.sli.do/?i=MDdhNTcxNzAtM2ZlNy00YTkwLTg4OTYtMDEwODBiMzcwNWZj
Closes #1909
=> Change recommendation header

app/models/usage_report.rb
Change logic:
external if offer is `order_required && !internal && order_url.present?`
internal in any other case of `order_required` offer
(it means `!internal && order_url.blank?` or just `internal`)
Executive statistics have unified query
In PRODUCTION data there should be only 3 services with external flag:
["InAcademia", "GÉANT Clouds Service ", "GÉANT Testbeds Service"]
=> [HOTFIX] Fix logic of resource order wizards

CHANGELOG.md, Procfile, Procfile.dev, app/controllers/concerns/service/recommendable.rb, app/controllers/user_action_controller.rb, app/javascript/app/index.js, app/javascript/app/user-action.js, app/jobs/probes/probes_job.rb, app/views/layouts/_breadcrumb.html.haml, app/views/services/_header.html.haml, app/views/services/_index.html.haml, app/views/services/_recommendation_v1.html.haml, app/views/services/_recommendation_v2.html.haml, config/sidekiq.yml, spec/controllers/concerns/recommendable_spec.rb, spec/features/recommended_spec.rb, spec/features/user_action_spec.rb
IMPORTANT!!! In case of unique_id clean cookies store before testing data
---
- Update /recommendations and /user_actions endpoints body
- unique_id is integer
- timestamp is in UTC iso8601 format
- visit_id is integer
- logged_user appear always, not only for logged user
- Change filters placements from filters field to search_data in /user_actions
- Add probe job to queue configuration
- Change JS fetch body field from action to user_action to prevent overwriting by Ruby
- Fix double triggering of `Add comparison` in service details panel
- /recommendations endpoint body changes
- Extend resource availability filter with regions
- Extend tree structure like filters to send also child nodes
- Fix response body parsing
- Improve recommender error handling #1889
- Services ids should be …
=> [#1865] Recommendation API adjustments

CHANGELOG.md, app/controllers/concerns/service/autocomplete.rb, app/controllers/concerns/service/searchable.rb, app/helpers/service_helper.rb, app/models/provider.rb, app/models/service.rb, app/models/service/search.rb, app/views/backoffice/services/_header.html.haml, app/views/services/_categorization.html.haml, app/views/services/_header.html.haml, app/views/services/_service_details.html.haml, app/views/services/autocomplete/_provider_item.html.haml, app/views/services/autocomplete/list.html.haml, app/views/services/ordering_configurations/_header.html.haml, docs/upgrade/3.9.0.md, spec/features/search_spec.rb
- Services can be found by provider or resource organisation
On search `cyfronet` in top searchbar, all resources of `Test-Cyfronet #10` should appear (3 of them).
Closes #1827
=> [#1827] Extend finding resource in main searchbar

CHANGELOG.md, Gemfile.lock, app/controllers/concerns/service/autocomplete.rb, app/controllers/concerns/service/categorable.rb, app/controllers/concerns/service/searchable.rb, app/controllers/home_controller.rb, app/helpers/service_helper.rb, app/models/category.rb, app/models/concerns/offerable.rb, app/models/provider.rb, app/models/service.rb, app/models/service/search.rb, app/models/usage_report.rb, app/services/service/pc_create_or_update.rb, app/services/service/update.rb, app/views/backoffice/services/_header.html.haml, app/views/home/index.html.haml, app/views/services/_categorization.html.haml, app/views/services/_header.html.haml, app/views/services/_search.html.haml, app/views/services/_service_details.html.haml, app/views/services/autocomplete/_provider_item.html.haml, app/views/services/autocomplete/list.html.haml, app/views/services/ordering_configurations/_header.html.haml, docs/upgrade/3.9.0.md, lib/tasks/rdt.rake, spec/features/categories_spec.rb, spec/features/search_spec.rb, spec/services/service/pc_create_or_update_spec.rb
Include all fixes from 3.9.x branch:
- [HOTFIX] Fix number of resources in executive statistics
- [#1872, #1886] Handle old categories
- [#1904] Fix categories slugs
- [HOTFIX] Fix logic of resource order wizards
- [#1902] Fix upstream set for resources from jms
- [#1827] Extend finding resource in main searchbar
- [HOTFIX] Bump mimemagic to 0.3.6
=> Fixes from 3.9.x to master

db/vocabulary.yml, lib/tasks/rdt.rake
Fix error with bad routing in categories
Error caused by a category slug `configuration`
because it is similar to service configuration path
`{root_path}/services/c/configuration` is a path to category
but rails recognize it like resource with slug `c`
and redirects to order configuration path of resource
instead of category_path
=> [HOTFIX] Fix category slug

Gemfile.lock, app/helpers/project_items_helper.rb, app/mailers/project_item_mailer.rb, app/models/jira/client.rb, app/models/project_item.rb, app/models/status.rb, app/services/jira/issue_updated.rb, app/services/project_item/create.rb, app/services/project_item/ready.rb, app/services/project_item/register.rb, app/views/projects/services/_layout.html.haml, app/views/projects/services/_project_item.html.haml, app/views/statuses/_status.html.haml, db/migrate/20210323162816_generalize_project_item_statuses.rb, db/schema.rb, spec/factories/order_changes.rb, spec/factories/project_items.rb, spec/factories/statuses.rb, spec/features/my_services_spec.rb, spec/features/projects_spec.rb, spec/helpers/project_items_helper_spec.rb, spec/mailers/project_item_spec.rb, spec/models/project_item_spec.rb, spec/models/status_spec.rb, spec/policies/project_policy_spec.rb, spec/requests/api/webhooks/jira_spec.rb, spec/services/jira/comment_activity_spec.rb, spec/services/project_item/create_spec.rb, spec/services/project_item/ready_spec.rb, spec/services/project_item/register_spec.rb
Make project_item have a status and a status_type.
The current status is renamed to status_type and it is kept as enum,
so that SOMBO-JIRA can relate to it.
Other than that, a status will now be managed by the primary OMS - it
just has to specify the associated status_type as well.
For now, keep the current SOMBO-JIRA integration, mapping
the status_type to status directly, ensuring it continues to work.
Purge forgotten project_item_changes model from the DB and factories.
Closes: #1881.
=> [#1881] Generalize project_item status

app/models/offer.rb, app/models/oms.rb, app/models/oms_administration.rb, app/models/oms_provider.rb, app/models/provider.rb, app/models/service.rb, app/models/user.rb, config/initializers/inflections.rb, db/migrate/20210324140221_create_oms.rb, db/migrate/20210324141046_create_oms_administrations.rb, db/migrate/20210324141438_create_oms_providers.rb, db/migrate/20210325120212_add_oms_to_offer.rb, db/schema.rb, lib/ordering_api/add_sombo.rb, lib/tasks/ordering_api.rake, spec/factories/offers.rb, spec/factories/oms.rb, spec/factories/services.rb, spec/lib/ordering_api/add_sombo_spec.rb, spec/models/jira/client_spec.rb, spec/models/offer_spec.rb, spec/models/oms_spec.rb, spec/models/provider_spec.rb, spec/models/service_spec.rb, spec/models/user_spec.rb
Closes #1879 
**What has been changed**: 
- Add OMS, OmsAministration, OmsProviders and OmsOffer models
- Add primary_oms to Offer, add validations
- Add default OMS logic
- Add SOMBO OMS (along with its admin) creation migration
- Add OMS/Offer model specs
=> [#1879] Add OMS to DB

app/controllers/concerns/project/authorize.rb, app/controllers/projects/conversations_controller.rb, app/controllers/projects/services/conversations_controller.rb, app/models/message.rb, app/models/project_item.rb, app/policies/message_policy.rb, app/services/jira/comment_activity.rb, app/services/project_item/ready.rb, app/services/project_item/register.rb, db/migrate/20210329084503_add_scope_and_role_to_message.rb, db/schema.rb, spec/factories/messages.rb, spec/jobs/message/register_message_job_spec.rb, spec/mailers/previews/webhook_jira_preview.rb, spec/models/message_spec.rb, spec/policies/message_policy_spec.rb, spec/requests/api/webhooks/jira_spec.rb, spec/services/jira/comment_activity_spec.rb, spec/services/message/create_spec.rb, spec/services/project_item/ready_spec.rb, spec/services/project_item/register_spec.rb
The author_role extends the Message typology, so that Messages
which come from providers and ops-team can be differentiated
(author_role=user|provider|mediator).
On the other hand, scope allows the providers and ops-team to exchange
Messages private to user between OMSes (scope=internal) and allows
providers to send Messages privately to user (scope=user_direct).
Before, when a Message wasn't sent by an MP user, it only had the
author_id==nil. I take it into account when migrating data.
Yet unused, but I add author_name and author_email columns, so that
OMSes can provide them when creating messages, making it easier for user
and other participating providers and ops-team members to discern the
Message origin.
Update the conversation_controllers, so that only scope_public? and …
=> Add author_role and scope to Message

app/controllers/concerns/service/recommendable.rb
Access from Provider
http://localhost:5000/services?providers=851
Access from homepage - Scientific
http://localhost:5000/services?scientific_domains=589
Filters
http://localhost:5000/services?scientific_domains-filter=&scientific_domains-all=&scientific_domains%5B%5D=589&scientific_domains%5B%5D=590&providers-filter=&providers-all=&providers%5B%5D=736&providers%5B%5D=737&target_users-all=&related_platforms-filter=&related_platforms-all=&rating=&order_type=&geographical_availabilities=
Closes #1930
=> [#1873] Fix providers and scientific domain params

app/helpers/project_items_helper.rb, app/javascript/app/controllers/project_item_controller.js, app/mailers/project_item_mailer.rb, app/models/project_item.rb, app/policies/message_policy.rb, app/views/projects/services/_voucher.html.haml, app/views/projects/services/show.html.haml, db/migrate/20210331110641_add_user_secrets_to_project_item.rb, db/schema.rb, spec/features/my_services_spec.rb, spec/mailers/project_item_spec.rb, spec/models/project_item_spec.rb, spec/rails_helper.rb, spec/requests/api/webhooks/jira_spec.rb, spec/services/jira/issue_updated_spec.rb
Add project_item.user_secrets column, which will store secrets passed
for a user by the resource (service) provider.
It is validated to only be a "simple" hash, i.e. it should only store
strings as values.
When rendering VoucherID, then take project_item.voucher_id if present,
otherwise, project_item.user_secrets["voucher_id"].
When accepting VoucherID updates from a provider, store it in
user_secrets instead of voucher_id, as the latter should only store
user-entered value (the case when user already has a voucher).
Correct typos in voucher spelling (i.e. vaucher).
Make some methods, which needn't be public, in project_item private.
Correct the MessagePolicy::Scope to use symbols.
Make rendering condition in _voucher.html.haml more readable by using
if instead of a convoluted unless. …
=> Add project_item.user_secrets and handle voucherable

app/controllers/api/v1/oms/projects/project_items_controller.rb, app/policies/api/v1/oms/project_item_policy.rb, app/serializers/ordering_api/v1/event_serializer.rb, app/serializers/ordering_api/v1/project_item_serializer.rb, spec/requests/api/v1/oms/project/project_items_controller_spec.rb, spec/serializers/ordering_api/v1/event_serializer_spec.rb, spec/serializers/ordering_api/v1/project_item_serializer_spec.rb, swagger/v1/ordering/project/project_item/project_item_update.json, swagger/v1/ordering/swagger.json
The user_secrets hash values are obfuscated, excluding the ones which
were updated by the call (i.e. in method update).
Setting `user_secrets: {}` in policy's permitted_attributes allows any
key.
The obfuscation is done in controller on purpose, to allow
non-obfuscation of some keys in case of update.
Closes: #1966.
=> [#1966] Expose user_secrets in ordering API

README.md, lib/tasks/recommender.rake
Created recommender:serialize_db_to_file task. It allows to save DB dump into json file. Closes #1993
=> Create serialize_db_to_file task

lib/ordering_api/add_sombo.rb, spec/lib/ordering_api/add_sombo_spec.rb
Previous implementation assumed that every offer has a service.
That was was not the case in one of the testing environments, so the
`offer.service.order_target` part failed. Right now we are updating
`oms_params` only in offers which indeed have a service.
=> Fix ordering_api:add_sombo task

Gemfile, Gemfile.lock, app/jobs/oms/call_trigger_job.rb, app/models/event.rb, app/models/message.rb, app/models/project.rb, app/models/project_item.rb, app/services/event/call_triggers.rb, app/services/oms/call_trigger.rb, bin/rspec, lib/ordering_api/triggers_test_setup.rb, lib/tasks/ordering_api.rake, spec/factories/event.rb, spec/jobs/oms/call_trigger_job_spec.rb, spec/models/event_spec.rb, spec/models/message_spec.rb, spec/models/project_item_spec.rb, spec/models/project_spec.rb, spec/serializers/ordering_api/v1/event_serializer_spec.rb, spec/services/event/call_triggers_spec.rb, spec/services/oms/call_trigger_spec.rb
Triggers are to be run after an Event creation, so on the Event's
after_commit hook I execute Event::CallTriggers.
In turn for each event.omses it enqueues an Oms::CallTriggerJob, which
then calls Oms::CallTrigger service, executing the actual HTTP request.
The method event.omses returns all the OMSes authorized for an event,
adding the default_oms if necessary.
On the other hand, event.omses calls eventable.eventable_omses to get
the list of authorized OMSes for an eventable.
Each type of eventable implements it:
- project_item: just returns its offer primary_oms,
- project: gathers eventable_omses from its project_items and returns a
compiled, deduplicated list,
- message: delegates to its messageable.eventable_omses (all
messageable are also eventable).
It allows to more efficiently …
=> [#1983] Execute OMS triggers on Event creation

app/controllers/api/v1/oms/messages_controller.rb, app/serializers/ordering_api/v1/event_serializer.rb, app/serializers/ordering_api/v1/message_serializer.rb, spec/requests/api/v1/oms/messages_controller_spec.rb, spec/serializers/ordering_api/v1/event_serializer_spec.rb, spec/serializers/ordering_api/v1/message_serializer_spec.rb
Closes #2014 
How to test @Marcelinna (mostly copied from https://github.com/cyfronet-fid/marketplace/pull/1982#issuecomment-823921757):
We will artificially create a following situation:
- SOMBO (default), OMS2 and OMS3 omses and their admins
- Project1 (p1) which doesn't have any project_items, but has 2 messages (message1_1 (author: user, scope: public), message1_2 (author: mediator, scope: public))
- Project2 (p2) which has 1 project_item (project_item2_1 (assigned to OMS2)) and no messages
- Project3 (p3) which has 2 project_items (project_item3_1 (assigned to OMS2), project_item3_2 (assigned to OMS3)) and 2 messages (**message3_1 (author: provider, scope: public), message3_2 (author: provider, scope: user_direct)**)
Run
```
rails db:drop db:create db:migrate
rails dev:prime # …
```
=> [#2014] Obfuscate user_direct message content

CHANGELOG.md, app/components/services/inline_order_url_component.rb, app/helpers/project_items_helper.rb, app/helpers/service_helper.rb, app/mailers/project_item_mailer.rb, app/models/concerns/offerable.rb, app/models/jira/client.rb, app/models/service.rb, app/services/project_item/on_status_type_updated.rb, app/services/project_item/ready.rb, spec/javascript/offer_spec.js, spec/mailers/project_item_spec.rb, spec/services/project_item/on_status_type_updated_spec.rb, spec/services/project_item/ready_spec.rb
In conversation with @Marcelinna we decided that improving on what is in this PR is something out of scope of #2002 (#1941) but worth doing anyway, as currently hardly any emails are sent for project_item changes (i.e. most mails are only sent when `service.order_url.blank?`, and it's mostly populated (at least on PR DB) and it's populated for AoD services too, so no emails for voucherable are sent **AT ALL**).
----------------------------
The legacy Jira adapter email sending logic was based on
service.external, which was in some place in project's history migrated
from service to offerable (i.e. offer and project_item).
This caused an inconsitency between mailer and ordering wizard behaviour
(i.e. the mailer hardly sent any mails).
To correct this, switch the …
=> Improve Offerable logic and use it in OnStatusTypeUpdated

app/models/offer.rb, spec/models/offer_spec.rb
Fixes an issue where an offer without oms_params would fail validation against an OMS which does have custom params, but none of them are mandatory.
Closes #2026
=> [#2026] Default Offer creation fix

config/robots.production.txt
- allowed: Bing, Google, Yahoo, Duck duck, other
- increase the time between indexing up to 3 minutes
---
To verify properly working roobots.txt file for certain search engines, please check:
https://technicalseo.com/tools/robots-txt/
Required actions before verification: upload of robots.txt file to certain URL
Required fields:
URL: https://marketplace.eosc-portal.eu/
User-agent: a bot you are looking for to verify if it's allowed or not
=> Prevent non-search-engines bots from indexing

app/controllers/api/v1/resources/offers_controller.rb, app/models/offer.rb, app/policies/api/v1/offer_policy.rb, app/serializers/api/v1/offer_serializer.rb, db/migrate/20210427113134_set_internal_in_offers.rb, db/schema.rb, spec/models/offer_spec.rb, spec/requests/api/v1/resources/offers_controller_spec.rb, spec/serializers/api/v1/offer_serializer_spec.rb, swagger/v1/offer/offer_read.json
- Added `internal` and `order_type` dependent serialization
- Added before_validation hooks to Offer model to ensure `internal`, `primary_oms`, `oms_params` are set accordingly
- Added migration that sets `internal` to false when `order_type != order_required`
Addresses point 3. in https://github.com/cyfronet-fid/marketplace/issues/2012 (https://github.com/cyfronet-fid/marketplace/issues/2012#issuecomment-828385718).
Addresses 1.iii, 1.iv and point 3. in https://github.com/cyfronet-fid/marketplace/issues/1988 (https://github.com/cyfronet-fid/marketplace/issues/1988#issuecomment-828387266).
How to test locally @Marcelinna:
**Setup**
1. Run this in the terminal:
```
rails db:drop db:create db:migrate && rails dev:prime && rails ordering_api:add_sombo
```
2. Go to `localhost:5000` and log in …
=> [#1988][#2012] Offers API adjustments

app/views/layouts/order/_nav.html.haml
The nav component assumed that step_names were strings instead of
symbols, which changed with recent rails hotfix.
=> Nav active-state regression fix

Gemfile.lock, yarn.lock
Bump hosted-git-info from 2.8.8 to 2.8.9
Bumps [hosted-git-info](https://github.com/npm/hosted-git-info) from 2.8.8 to 2.8.9.
- [Release notes](https://github.com/npm/hosted-git-info/releases)
- [Changelog](https://github.com/npm/hosted-git-info/blob/v2.8.9/CHANGELOG.md)
- [Commits](https://github.com/npm/hosted-git-info/compare/v2.8.8...v2.8.9)
Signed-off-by: dependabot[bot] <support@github.com>
Bump lodash from 4.17.20 to 4.17.21
Bumps [lodash](https://github.com/lodash/lodash) from 4.17.20 to 4.17.21.
- [Release notes](https://github.com/lodash/lodash/releases)
- [Commits](https://github.com/lodash/lodash/compare/4.17.20...4.17.21)
Signed-off-by: dependabot[bot] <support@github.com>
Bump url-parse from 1.4.7 to 1.5.1
Bumps [url-parse](https://github.com/unshiftio/url-parse) from 1.4.7 …
=> Dependabot updates

app/views/services/_header.html.haml
Provider can navigate from the Resource Presentation Page to the resource dashboard of the Provider Component
no changelog because there already is entry that covers this change:
- Resource provider can navigate to the Provider Component from the Resource Presentation Page (@kmarszalek, @jarekzet)
-> https://beta.providers.eosc-portal.eu/resource-dashboard/west-life/west-life.3dbionotes/stats
=> [#1986] Provider can navigate from RPP to PC

CHANGELOG.md, app/controllers/users/auth_mock_controller.rb, app/helpers/provider_helper.rb, app/services/importers/logo.rb, app/views/backoffice/providers/show.html.haml, docs/upgrade/3.12.0.md, lib/tasks/add_extensions_to_images.rake
- Fix all models containing logo field
- Providers
- Services
- Categories
- Scientific Domains
- Add task migrating images without extension in a name to have one
- Add the image extension to the file name on load
- Set slug as image name on missing pid field
---
Fixing existing images requires migration. Although it's needed to run it with param `ROOT_URL` as for instance domain URL
Example:
`rake add_extension_to_images["http://localhost:5000"]`
---
Before
After
- Extention on Auth Mock endpoint to add roles to user
=> [#1836] Fix img background on resize

app/controllers/concerns/service/recommendable.rb, app/serializers/recommender/service_serializer.rb
This PR solves issue #1998 on the marketplace side. Should be considered together with cyfronet-fid/recommender-system#51 (that solves this issue on the recommender side).
Now, services sent by a recommender are checked for status before displaying in recommendation panel. If some of them has status other than "published" the recommendation panel isn't displayed.
=> Don't recommend unpublished services

CHANGELOG.md, app/models/parameter/multiselect.rb, app/views/parameters/template/_multiselect.html.haml, spec/features/backoffice/parameters_spec.rb
- Change minimum value of selected
items to default 1 instead of 0
- Add validation for min < max
Fixes #1952
=> [#1952] Fix validation of min max values in multiselect

CHANGELOG.md, app/controllers/backoffice/services/offers_controller.rb, app/controllers/services/ordering_configuration/offers_controller.rb, app/javascript/app/controllers/ordering_controller.js, app/models/offer.rb, app/models/offer/oms_params.rb, app/policies/backoffice/offer_policy.rb, app/policies/ordering_configuration/offer_policy.rb, app/views/backoffice/services/offers/_form.html.haml, app/views/backoffice/services/offers/_one_offer_edit_form.html.haml, app/views/backoffice/services/offers/_primary_oms_form.haml, app/views/backoffice/services/offers/edit.html.haml, app/views/services/ordering_configuration/offers/edit.html.haml, config/locales/simple_form.en.yml, lib/tasks/test_bootstrap.rake, lib/test_bootstrap/add_role_to_user.rb, lib/test_bootstrap/omses_with_different_custom_params.rb, spec/features/backoffice/services_spec.rb, spec/features/ordering_configuration_spec.rb
Partly address #2012 and #1988.
Make the offer ordering form show/hide fields as dictated by the
business logic.
Also, add OMS selection to the form. The possible values are taken from
available_omses, and oms_params are emitted in HTML for all the OMSes.
The stimulus controller changes their visibility and disabled state
according to the chosen OMS.
1. As a logged-in user go to Backoffice space.
2. Select any resource for editing.
3. Click "Add new offer" in " Parameters and offers "
4. For order_type not equal to `order_required` you should see no "Use EOSC Portal as an order management platform" checkbox, no "Order / access URL" nor OMS selection. Note that you will still see "Offer website" field, it will be removed in the scope of other PR.
5. Select order_type=`order_required`, a …
=> [#1880] Improve offer ordering configuration

CHANGELOG.md, README.md, app/views/projects/_customer_typology_fields.html.haml, config/initializers/application_controller_renderer.rb, config/locales/simple_form.en.yml, spec/features/backoffice/services_spec.rb, spec/models/jira/client_spec.rb
Before, in some places domain.com was used, which is a hosting company,
and in another webpage.org, which is also a domain parked by another
company.
Instead, use the generic IANA-reserved domain for examples, see
https://www.iana.org/domains/reserved.
1. Go to a new project (or existing one) form and verify that fields have correct hints:
1. email: "Email address in your institute's domain [e.g. email@example.com]"
2. when selected "Customer typology" = "Representing a project"
1. Project website url: "Url should start with http or https [e.g. https://example.com] "
2. when selected "Customer typology" = "Single user"
1. Webpage: "Url should start with http or https [e.g. https://example.com] "
2. when selected "Customer typology" = "Representing a private company"
1. Company website …
=> Use consistent exemplary domain and move hints to yml file

CHANGELOG.md, app/models/jira/client.rb, app/models/service.rb, app/policies/backoffice/service_policy.rb, app/views/backoffice/services/_form.html.haml, config/locales/simple_form.en.yml, db/migrate/20210518101302_remove_service_order_target.rb, db/schema.rb, lib/ordering_api/add_sombo.rb, spec/factories/services.rb, spec/features/backoffice/services_spec.rb, spec/lib/ordering_api/add_sombo_spec.rb, spec/models/jira/client_spec.rb, spec/models/service_spec.rb, spec/policies/backoffice/service_policy_spec.rb
Migrate the values of service.order_target to existing
`order_required && internal` offers' oms_params and remove the column.
In legacy Jira integration, get the SO-ServiceOrderTarget value from the
offer. Make sure that in case no such value is found an empty string is
emitted, matching the existing solution.
Remove the order_target logic from add_sombo rake task, and make sure
that the task handles case when SOMBO OMS already exists, but
sombo_admin doesn't (see #2079).
Fixes: #2012. Fixes: #2079.
There should be no "Resource order target" field in service edit form.
When ordering "B2ACCESS", see that Jira receives field `SO-ServiceOrderTarget=support@eudat.eu`.
=> [#2012] Remove service.order_target

swagger/v1/offer/offer_definitions.json, swagger/v1/offering_swagger.json
The field webpage wasn't properly removed when removing webpage from the
model in #2070.
Also, run `rails rswag` to bring API description up to date. 
See that webpage field doesn't appear anymore in the Offering API swagger.
=> Remove webpage from Offering API

CHANGELOG.md, app/services/service/draft.rb, spec/services/service/draft_spec.rb
Change the behavior of set status of resource to draft
Now offers don't disappear after click
"Stop showing in the MP"
Fixes #2034
=> [#2034] Don't remove offers by drafting resource

app/models/parameter/minmax.rb, app/models/parameter/multiselect.rb, spec/features/backoffice/parameters_spec.rb
Min and Max values implemented in parameters
had wrong message: "must be grater/lesser..."
From now it's correct "must be greater/lesser or equal..."
=> [HOTFIX] Fix validator messages for MinMax parameter

app/models/parameter/minmax.rb, app/models/parameter/multiselect.rb, spec/features/backoffice/parameters_spec.rb
Min and Max values implemented in parameters
had wrong message: "must be grater/lesser..."
From now it's correct "must be greater/lesser or equal..."
=> [HOTFIX] Fix validator messages for MinMax parameter (backport to master)

CHANGELOG.md, app/helpers/comparisons_helper.rb, app/helpers/project_items_helper.rb, app/models/service.rb, app/views/comparisons/show.html.haml, app/views/projects/services/_details.html.haml, app/views/services/_categorization.html.haml
Add separation for `resource_organisation`
and `providers` in the `comparison`
and `project_item` views
Closes #1891
=> [#1891] Fix providers in comparison and project_item

README.md, lib/ordering_api/add_provider_oms.rb, lib/tasks/ordering_api.rake, spec/lib/ordering_api/add_provider_oms_spec.rb
The task creates an OMS for provider and its admin if needed.
It can be tested by running from the rails console with loaded dev db:
```
Provider.first.update!(pid: "test.pid")
```
It's necessary, as in dev providers don't have PIDs by default.
Then, run from the shell:
```
rake ordering_api:add_provider_oms ARG_OMS_NAME="extra_provider" ARG_PROVIDER_PID="test.pid"
rake ordering_api:add_provider_oms ARG_OMS_NAME="extra_provider" ARG_PROVIDER_PID="test.pid" ARG_AUTHENTICATION_TOKEN="test_token"
```
=> Add task to create OMS for provider

CHANGELOG.md, app/models/service.rb, spec/lib/ordering_api/add_provider_oms_spec.rb, spec/models/offer_spec.rb, spec/models/service_spec.rb, spec/requests/api/v1/resources_controller_spec.rb
Provider group OMSes were visible to all services, which have one of the
OMSes providers in the service.providers relation.
This behaviour was deemed incorrect, resource_organisation relation
should have been used.
Providers from the service.providers relation don't configure offer and
ordering, the provider from service.resource_organisation does that.
Moreover, the resource_organisation provider may not be present in the
providers relation, causing such provider not to be able to correctly
select such OMS.
Add tests for service.available_omeses.
The instance has two extra provider_group OMSes named: "For DIH" (for DIH provider) and "For EUDAT" (for EUDAT provider).
Service `Piloting and co-design of Business Pilots` has resource_organisation set to DIH and has EUDAT in its providers …
=> [#2135] Make OMS visibility depend on resource_organisation

CHANGELOG.md, app/controllers/api/v1/omses/messages_controller.rb, app/policies/api/v1/message_policy.rb, app/serializers/api/v1/message_serializer.rb, app/serializers/api/v1/project_serializer.rb, db/migrate/20210614131726_add_author_uid_to_message.rb, db/schema.rb, spec/requests/api/v1/omses/messages_controller_spec.rb, spec/serializers/api/v1/message_serializer_spec.rb, spec/serializers/api/v1/project_serializer_spec.rb, swagger/v1/message/message_read.json, swagger/v1/message/message_write.json, swagger/v1/ordering_swagger.json, swagger/v1/project/project_read.json
Extend the Ordering API by adding `uid` property to author: both for
project and messages.
Allow to specify the extra field for provider and mediator messages as
well. Add it as an optional field in POST request to /messages endpoint.
Add missing GET /api/v1/oms/{oms_id}/messages/{m_id} ref.
SOMBO token: `LBPcykf7dpzi_GmfXLzs`.
Create a project and a project item. Add messages to both.
Using Ordering API:
Verify that when you GET a project then the field `owner` now has the field `uid`.
Verify that when you GET any of your messages, then the field `author` has the field `uid`.
Verify that if you POST a message to project or project_item and specify field `uid` in `author` then its value is persisted and returned in this message GET responses.
Closes: #2144.
=> [#2144] Add UID to author in Ordering API

CHANGELOG.md, app/controllers/backoffice/providers_controller.rb, app/views/backoffice/providers/form/_classification.html.haml, app/views/backoffice/services/_form.html.haml, app/views/profiles/_form.html.haml, app/views/projects/_customer_typology_fields.html.haml, app/views/projects/_form.html.haml
Remove unnecessary `include_hidden: false` attribute in the forms.
It causes submitted form doesn't have information, that field is empty.
Fixes #2029
=> [#2029] remove elements from choices in the forms

CHANGELOG.md, app/controllers/api_docs_controller.rb, app/models/user.rb, app/views/api_docs/show.html.haml, config/routes.rb, spec/factories/users.rb, spec/features/api_docs_spec.rb, spec/models/user_spec.rb
Setting authorization_token to `revoked` made authorizing as such user
possible in the API. Having a unique constraint on that column also
prevented several users to have the token revoked simulataneously.
Remove possibility to revoke token altogether, leaving only the ability
to regenerate it.
Nevertheless, handle the case of blank? token, as it will appear for
users which created their accounts before simple_token_authorization was
added to the project.
Fixes: #2176.
=> [#2176] Only allow to regenerate API token

app/views/services/filters/_multiselect_level.html.haml, app/views/services/filters/_select.html.haml, test/system/cypress.json, test/system/cypress/integration/regression_tests/servce-page/filters/dedicated_for.spec.ts, test/system/cypress/integration/regression_tests/servce-page/filters/infrastructutes_platforms.spec.ts, test/system/cypress/integration/regression_tests/servce-page/filters/order_type.spec.ts, test/system/cypress/integration/regression_tests/servce-page/filters/providers.spec.ts, test/system/cypress/integration/regression_tests/servce-page/filters/rating.spec.ts, test/system/cypress/integration/regression_tests/servce-page/filters/resource_availability.spec.ts, test/system/cypress/integration/regression_tests/servce-page/filters/scientific_domains.spec.ts
Add e2e tests for filters on services page 
Add test for scientific domains, providers, dedicated for, platforms, order type, rating, resource availability filters
tests select the first element of each filter and check the filter has been turned on and the url is correct
=> Add e2e tests for filters on services page

CHANGELOG.md, app/controllers/api_docs_controller.rb, app/javascript/app/controllers/token_controller.js, app/javascript/stylesheets/_bootstrap-customizations.scss, app/views/api_docs/show.html.haml, spec/features/api_docs_spec.rb
Allow unlogged users to get the api_docs page
After log in api docs shows only '*' signs
Added button to reveal the token
Closes #2171
=> [#2171] Hide token on API docs page

CHANGELOG.md, app/helpers/backoffice/services_helper.rb, app/models/provider.rb, app/models/service.rb, app/policies/provider_policy.rb, app/views/backoffice/services/offers/_one_offer_edit_form.html.haml, app/views/backoffice/services/offers/_primary_oms_form.haml, app/views/providers/_header.html.haml, app/views/providers/header/_drop_down_menu.html.haml, spec/features/provider_spec.rb, spec/policies/provider_policy_spec.rb
Provider can navigate from the Provider Presentation Page
to the provider dashboard of the Provider Component
To test you need to be provider data_admin.
Add yourself in backoffice as data_admin then go to providers presentation page.
Closes #2186
=> [#2186] Provider can navigate from PPP to PC

CHANGELOG.md, app/controllers/home_controller.rb, app/views/home/_opinions.html.haml, spec/features/home_spec.rb
Recent opinions for unpublished resources
are not displayed on the home page
Fixes #1956
=> [#1956] Hide opinions for unpublished resources

CHANGELOG.md, app/views/projects/_form.html.haml, spec/features/projects_spec.rb
Show scientific domains to choose as a tree structure
as it is in providers and resources forms
Fixes #2182
=> [#2182] Fix choices of scientific domains in the project form

CHANGELOG.md, app/controllers/pages_controller.rb
As a part of ticket #2047 there was a need to move
"Other" target user at the end of list
available at `/target_users/` page
Fixes #2047
=> [#2047] Move "Other" target user at the end of a list

CHANGELOG.md, app/controllers/services/ordering_configurations_controller.rb, app/views/services/ordering_configurations/_about.html.haml, spec/features/ordering_configuration_spec.rb
Fix a possibility to create an offer in the ordering_configuration
panel when a resource has no offers
Fixes #2103
=> [#2103] Fix creating offers in ordering configuration

README.md, app/views/admins/show.html.haml, app/views/layouts/_version.html.haml, config/initializers/constants.rb, spec/features/admin/version_spec.rb
Before, only ENV["MP_VERSION"] was accessed for the version value,
requiring the deployer to set the constant on each run.
Now, the constant still takes precedence if set, but by default the
VERSION file's content is used, making it less error-prone, but allowing
for flexibility in case other behaviour is desired.
In the view, it's no longer necessary to check for the constant's
existence, since if the VERSION file doesn't exist then error is raised
during app initialization.
Fixes: #2063.
=> [#2063] Read version from VERSION file

CHANGELOG.md, app/views/projects/services/_details.html.haml, config/locales/views/project_items/en.yml, spec/features/project_services_spec.rb
The labels' keys generated using map_view_to_order_type helper got out
of sync with defined translation keys, leading to erroneous display.
For !open_access? project_items, instead of an expected text (i.e.
"Added to the project" or "Order date") the order_type was rendered as a
fallback (for example "Fully Open Access", when the value was a date,
making no sense).
Correct the behaviour to be handled in the view and remove unnecessary
translation entries.
Fixes: #2082.
=> [#2082] Correct project_item created date label display

CHANGELOG.md, app/views/projects/services/_rating.html.haml, app/views/projects/services/opinions/new.haml, config/locales/views/project_items/en.yml, spec/features/opinions_spec.rb
Fixes displayed "Question1" and "Question2" in the form
Remove dynamic translation from i18n and use GetText
Fixes #1984
=> [#1984] Fix questions in the resource opinion form

app/controllers/services/ordering_configurations_controller.rb, spec/features/ordering_configuration_spec.rb
Change the policy for Resource authorization
in `ordering_configurations_controller`
Pundit used default `ServiceContextPolicy`
instead of correct
`OrderingConfiguration::ServiceContextPolicy`
Fixes #2255
=> [#2255] Fix unauthorized access to ordering_configuration

CHANGELOG.md, app/controllers/backoffice/services_controller.rb, app/policies/backoffice/service_policy.rb, spec/features/backoffice/services_spec.rb, spec/policies/backoffice/service_policy_spec.rb
=> [#2075] Backoffice user cannot edit categories in an eosc_registry resource

CHANGELOG.md, app/controllers/services_controller.rb, app/javascript/app/controllers/autocomplete_controller.js, spec/factories/providers.rb, spec/features/search_spec.rb
Fix reloading autocomplete list
after clicking on an item
After page reload search input
is filled with previously clicked item label
**NOTICE**
Fixed redirect_to `/null` isn't merged into master yet.
Fixes #2236
=> [#2236] Fix autocomplete unnecessary reloading

CHANGELOG.md, app/controllers/backoffice/services_controller.rb, app/controllers/concerns/service/sortable.rb, app/controllers/services_controller.rb, app/models/service/search.rb, spec/controllers/concerns/sortable_spec.rb, spec/features/service_spec.rb
- Fixed sorting by name
- Added test that checks sorting with lower/upper cases
Elasticsearch follows ASCII sort order, the bytes that represent
capital letters have lower ASCII values than that of lowercase letters.
By changing name to name.downcase in search_data we can sort resources
in alphabetical order regardless of their ASCII codes.
Closes #1961
=> [#1961] Fix sorting for resources

CHANGELOG.md, app/controllers/comparisons_controller.rb, app/controllers/concerns/service/searchable.rb, app/views/backoffice/services/index.html.haml, app/views/comparisons/show.html.haml, app/views/services/_filters.html.haml, app/views/services/_index.html.haml, app/views/services/_order.html.haml, app/views/services/index.html.haml, spec/features/backoffice/providers_spec.rb
When user navigates from resources list
to the comparison view, query params are saved now
Fixes #2005
=> [#2005] Store query params in comparison view

CHANGELOG.md, app/serializers/api/v1/project_item_serializer.rb, spec/factories/offers.rb, spec/factories/project_items.rb, spec/serializers/api/v1/project_item_serializer_spec.rb
The voucher_id value must be passed in open text to OMS somehow to
implement the pre-existing voucher use-case: there is a CP-VoucherID
field in Jira.
Create project item with (I) and without (II) voucher ID specified.
It shouldn't matter, if (II) is from a voucherable offer or not.
Once the project items are created, inspect the Ordering API (oms_id=`1`, token=`vJkCgAA153VYx8yBNnYb`) for the created project items.
The output of (I) should have an attribute named `supplied_voucher_id` and output of (II) shouldn't contain it.
If you update (I) to set a different voucher_id in its user_secrets, i.e. send a PATCH with `{"user_secrets":{"voucher_id":"some_other_value"}}`, then the `supplied_voucher_id` should still show the original value and not `some_other_value`. 
Closes: #2278.
=> [#2278] Add supplied_voucher_id to project_item attributes

CHANGELOG.md, app/controllers/backoffice/services/offers_controller.rb, app/helpers/service_helper.rb, app/models/service/search.rb, app/policies/backoffice/offer_policy.rb, app/services/offer/create.rb, app/services/offer/destroy.rb, app/services/offer/update.rb, app/services/service/update.rb, spec/features/backoffice/services_spec.rb, spec/lib/import/resources_spec.rb, spec/requests/api/v1/resources/offers_controller_spec.rb, spec/services/service/update_spec.rb
Add resources reindexing by offer update/remove
(needed for valid `order_type` queries in ES)
Add changing resource order type
after multiple offers deletion
Fixes #1965 
@jswk this is information for offers logic update
- Add a new offer with different order_type as in service causes change labels to the "various types", filters are searching by order_type of offers and a service
- Set default offer by removing other offers will update offer order_type from a service
- Create the first offer will update offer order_type from a service
If we remove default offer (offer with the same order_type as in a service) and we have a few offers with different types, existing offers will be not updated for compatibility with the service order_type.
=> [#1965] Reindex resource by offer update

CHANGELOG.md, app/services/offer/create.rb, app/views/backoffice/services/offers/_form.html.haml, app/views/backoffice/services/offers/edit.html.haml, app/views/services/ordering_configuration/offers/edit.html.haml, spec/features/backoffice/services_spec.rb, spec/features/ordering_configuration_spec.rb
Issue cause by unnecessary double saving an offer in `Offer::Create` service.
(first save and then copy order_type from not updated resource)
Removed order_type's update and disabled `order_type` field with the service.order_type value set.
Fixes #2299
=> [#2299] Fix default offer's order_type bad mapping

CHANGELOG.md, app/models/usage_report.rb, spec/models/usage_report_spec.rb
Method `Service.joins(:offers)` doesn't include
resources without offers,
which causes they were not included
in order_type statistics.
Use `Service.left_outer_joins` instead.
Fixes #1975
=> [#1975] Include resources without offers in statistics

CHANGELOG.md, app/javascript/stylesheets/_ref_mobile.scss
fix for mobile menu in specific 990px screen size (double navigation in header).
Was
Now
=> 990 breakpoint mobile menu fix

CHANGELOG.md, app/javascript/app/tours.js, spec/features/tours/query_param_spec.rb
The `tour` query param wasn't cleared on tour completion for tours with
query param activation strategy.
It was discovered in https://github.com/cyfronet-fid/marketplace/pull/2311#issuecomment-926471672, but was out of the virtual tour scope itself.
Go to https://marketplace-13.docker-fid.grid.cyf-kr.edu.pl/services/egi-cloud-compute?tour=query_param_1 and complete both parts of the tour.
After the last step, the `tour` query param should disappear from URL and the feedback modal should be visible.
Fixes: #2316.
=> [#2316] Clear query param on tour complete

CHANGELOG.md, app/controllers/application_controller.rb, spec/features/access_denied_spec.rb, spec/requests/backoffice/services_spec.rb
Bug happens due to the behaviour of 302 HTTP Redirect, which persists the anchor tag (#offers in our case) in the url after the redirection (https://stackoverflow.com/questions/5283395/url-hash-is-persisting-between-redirects). Due to losing permission to see the page, the user is being redirected by `pundit` (to the previous page if possible ("referer" header value), or to the root_url if not) - and the anchor persists, causing the bug.
My solution includes replacing the `redirect_back` with `redirect_to root_page(anchor: "")`. This is acceptable, because in MP we have a policy that the users cannot click the links or buttons that they aren't authorized to see (@marcelinna - please check this), thus making the `redirect_back` redundant - the only way to access unauthorized resources is …
=> [#2092] Fix anchor tag persistence on denied permission

test/system/cypress/integration/regression_tests/backoffice/resources/owned_resources.spec.ts
The rails/ruby upgrade PR wasn't rebased on the current master, leading
to the test failure.
=> Correct owned_resources failing test

CHANGELOG.md, app/controllers/backoffice/providers_controller.rb, app/controllers/concerns/service/searchable.rb, app/controllers/providers/details_controller.rb, app/controllers/providers_controller.rb, app/helpers/service_helper.rb, app/models/filter/backoffice_provider.rb, app/models/filter/multiselect.rb, app/models/filter/provider.rb, app/models/provider.rb, app/policies/backoffice/provider_policy.rb, app/policies/provider_policy.rb, app/services/provider/destroy.rb, app/views/backoffice/services/_form.html.haml, app/views/services/_categorization.html.haml, db/data.yml, db/migrate/20211025064757_add_status_to_providers.rb, db/schema.rb, lib/tasks/dev.rake, spec/factories/providers.rb, spec/policies/backoffice/provider_policy_spec.rb, spec/policies/provider_policy_spec.rb, spec/requests/backoffice/providers_spec.rb
=> [#2354] Implement providers soft delete

CHANGELOG.md, app/controllers/backoffice/services_controller.rb, app/helpers/backoffice/services_helper.rb, app/helpers/image_helper.rb, app/helpers/service_helper.rb, app/javascript/app/controllers/preview_controller.js, app/views/backoffice/services/_form.html.haml, app/views/backoffice/services/preview.html.haml, app/views/services/_about.html.haml, app/views/services/_ask_question.html.haml, app/views/services/_categorization.html.haml, app/views/services/_details.html.haml, app/views/services/_header.html.haml, app/views/services/_offer.html.haml, app/views/services/_offers.html.haml, app/views/services/_related.html.haml, app/views/services/_service_box.html.haml, app/views/services/_tabs.haml, app/views/services/details/_array.html.haml, app/views/services/details/_links.html.haml, app/views/services/details/_object.html.haml, app/views/services/sidebar/_simple_links.html.haml, app/views/taggable/_details_section.html.haml, spec/features/backoffice/services_spec.rb, test/system/cypress/support/resources.ts
Add all hidden buttons and links in preview
and disable them via js controller
Closes #2273
---
=>  [#2273] Improve preview functionality

CHANGELOG.md, app/controllers/backoffice/services_controller.rb
Clear session after go back to the
edit form from a preview mode.
Stored session data caused overwriting
data edited after go back to the form
Fixes #2265
=> [#2265] Store resource's parameters from a form

CHANGELOG.md, app/controllers/providers/questions_controller.rb, app/controllers/services/questions_controller.rb, app/services/provider/question/deliver.rb, app/services/service/question/deliver.rb, spec/factories/provider_sources.rb, spec/factories/service_sources.rb, spec/features/provider_question_spec.rb, spec/features/service_question_spec.rb
Don't do it for non :eosc_registry services and providers, as they won't
exist on the EOSC Registry side.
Closes: #2390.
=> [#2390] Push new questions to outbound JMS queue

CHANGELOG.md, app/models/offer.rb, app/models/project_item/project_validation.rb, app/models/project_item/wizard.rb, spec/factories/services.rb, spec/features/order_spec.rb
open_access/fully_open_access/other offer can be added only once.
order_required - external can be added only once.
order_required - internal can be added multiple times.
bundled offer (parent and child) can be added multiple times.
child of the bundled offer can be added once if it is oa/foa/oo/or-e offer if it is ordered solo.
Closes #2066
=> [#2066] Fix logic of adding offers to a project

CHANGELOG.md, app/services/application_service.rb, app/services/project_item/create.rb, app/services/project_item/on_created/publish_addition.rb, app/services/project_item/on_created/publish_coexistence.rb, spec/services/project_item/create_spec.rb, spec/services/project_item/on_created/publish_addition_spec.rb, spec/services/project_item/on_created/publish_coexistence_spec.rb
Don't do it for non :eosc_registry services, as they won't exist on the EOSC Registry side.
Closes: #2389.
=> [#2390] Push resource (co)existence info to outbound JMS queue

app/models/project_item.rb
Remove ProjectValidation from project item.
Add Project presence validation.
Now, ProjectValidation is used only on ordering wizard (create)
and not on updating project_item.
=> [#2066] Clearing project and project item validation logic

app/services/jms/publisher.rb
Remove the trailing `.>`, which hold no meaning when publishing.
When subscribing it matches all topic hierarchy.
=> [#2412] Correct publisher outbound topic name

CHANGELOG.md, app/models/project_item/project_validation.rb, spec/features/order_spec.rb
Add condition that enables ordering of bundled offer
irrespectively of the offer type.
You can order bundle offer and then order bundled offer
separately regardless of her type
=> Making offer ordering bulletproof

app/jobs/jms/publish_job.rb, app/services/jms/publish.rb, app/services/jms/publisher.rb, lib/jira/console_checker.rb, lib/jms/subscriber.rb, spec/lib/jira/console_checker_spec.rb
Don't pass a static client-name/id, so that multiple concurrent
connections to the server can take place. Otherwise JMS connections get
corrupted (leaving repeating on_miscerr in logs, or crash the
application if the connection is switched to reliable=false).
Add connect_timeout and max_reconnect_attempts to JMS::Subscriber too,
as having a failed process is more meaningful than a hanged one.
The stomp gem doesn't use a common custom subclass for its Errors,
instead it's necessary to catch RuntimeError to handle them all.
Typo fixes.
=> [#2412] Use default client-id generation scheme and other improvements

app/controllers/services/configurations_controller.rb
Add missing `@offer` variable in the update method, 
from which layout choose the Cancel link label
=> [HOTFIX] Fix cancel button label in configuration's step

CHANGELOG.md, app/controllers/backoffice/services_controller.rb, app/models/service.rb, spec/services/service/pc_create_or_update_spec.rb
This PR fixes adding providers to the resource
even if chosen provider has improper data
Fixes #2446
=> [#2446] Fix updating resources with invalid providers

CHANGELOG.md, app/controllers/backoffice/services_controller.rb, spec/features/backoffice/services_spec.rb
Click on a `Preview` button when the form is empty
caused saving empty attributes in a session.
Then after filling the form and click on
"Create Resource" the priority was in session attributes
Fixes #2472
=> [#2472] Fix clearing a resource form

CHANGELOG.md, app/controllers/backoffice/services_controller.rb
Fix problem with contact fields
when clicked preview on an empty resource template
Fixes #2330
=> [#2330] Fix contact fields in the resource form

README.md, config/storage.yml, docs/upgrade/3.29.0.md
Add `S3_ACCESS_KEY_ID` and `S3_SECRET_ACCESS_KEY_ID` as
configurable ENV's for S3 ACtiveStorage.
Closes #2488
=> [2488] Add more configurable ENV's for s3 ActiveStorage

app/models/offer.rb, app/models/service.rb, app/services/service/create.rb, app/services/service/update.rb, db/migrate/20220120112130_set_blank_order_type_in_service.rb, db/schema.rb, spec/features/backoffice/services_spec.rb
Problem caused by hidden field which is blank
when no order_type is chosen in a service.
Add default "other" order_type in this case
Fixes #2505 #2302
=> [#2505] Fix adding parameters to the default offer

CHANGELOG.md, app/helpers/application_helper.rb, app/policies/ordering_configuration/service_context_policy.rb, app/views/providers/_header.html.haml, app/views/services/_header.html.haml, spec/features/ordering_configuration_spec.rb, spec/features/provider_spec.rb, spec/features/service_spec.rb, test/system/cypress/integration/regression_tests/backoffice/providers/providers.spec.ts
Show button 'Manage the..' o Resource and Provider views only when
upstream is set to 'eosc_registry'
Fixes #2525
=> [#2525] Show manage button on Resource and Provider views

CHANGELOG.md, app/controllers/api/v1/omses/events_controller.rb, app/helpers/date_helper.rb, spec/helpers/date_helper_spec.rb, spec/requests/api/v1/omses/events_controller_spec.rb, swagger/v1/ordering_swagger.json
Fix parsing date for /events endpoint
date format: 
* 2021-04-07T15:31:46Z
* 2001-02-03T04:05:06.123456Z
* 2017-09-27T23:46:46.003Z
no acceptable:
* asd
* 100
* -100
* -2021-04-07T15:31:46+02:00
* 2022-02-10T08:13
Fixes #2220
=> [#2220] Fix date in /events OMS API

CHANGELOG.md, README.md, app/controllers/concerns/service/recommendable.rb, config/application.rb, spec/controllers/concerns/recommendable_spec.rb
closes #2498 
By using "engine_version" we can specify which algorithm should be used to serve recommendations.
Changes:
- "engine_version" in the body of the /recommendations request,
- "engine_version" field is set to the environmental variable: RECOMMENDATION_ENGINE if it exists;
otherwise, it's set to "RL".
=> [#2498] Add "engine_version" field in the body of the /recommendations request

CHANGELOG.md, app/models/concerns/offerable.rb, app/views/services/_analytics.html.haml
Add `orderable` scope for `offers` and `project_items`
for proper displaying and counting ordered (only internal `order_required`) resources.
Fixes #2549
=> [#2549] Fix resources statistics for executive

CHANGELOG.md, app/components/presentable/description_component.html.haml, spec/features/backoffice/services_spec.rb, spec/features/ordering_configuration_spec.rb
Add missing direct path to the `notebook_openaire_explore`
partial. Now it's impossible to see EGI Notebooks page
in the backoffice
=> [HOTFIX] Fix EGI Notebooks backoffice page

CHANGELOG.md, app/services/jms/manage_message.rb, app/services/provider/pc_create_or_update.rb, spec/factories/jms_providers_response.rb, spec/services/jms/manage_message_spec.rb, spec/services/provider/pc_create_or_update_spec.rb
All providers in all statuses should be in mp db, with proper mp status for showing them in FO.
Fixes #2597
=> [#2597] Rewrite jms handle of Provider msgs

.rubocop.yml, CHANGELOG.md, lib/import/providers.rb, lib/import/resources.rb, spec/factories/eosc_registry_providers_response.rb, spec/lib/import/providers_spec.rb, spec/lib/import/resources_spec.rb
*change API endpoint to newer that consist of status
and active flag in response
*adapt code to diff return value
USE:
* import resource/resources
bundle exec rake import:resources IDS=<RESOURCE_IDS> MP_IMPORT_TOKEN=<TOKEN>
* import provider/providers
bundle exec rake import:providers IDS=<RESOURCE_IDS> MP_IMPORT_TOKEN=<TOKEN>
IDS => comma separated PC ids
TOKEN => token with epot role.
Fixes #2590
=> [#2590] Fix REST import of Providers and Resources

app/controllers/backoffice/vocabularies_controller.rb, app/policies/backoffice/vocabulary/hosting_legal_entity_policy.rb, app/views/backoffice/vocabularies/_nav.html.haml, config/routes.rb
Add Hosting Legal entity to the backoffice
No additional changelog entry,
it's missing part of adding Hosting Legal Entity
to vocabularies
Closes #2686
=> [#2686] Add Hosting Legal entity to the BO

CHANGELOG.md, Gemfile, Gemfile.lock, app/jobs/test/thread_time_test_job.rb, config/sidekiq.yml, lib/tasks/sidekiq.rake
Add limit to 1 worker for `pc_subscriber` sidekiq queue.
According to the documentation https://github.com/deanpcmad/sidekiq-limit_fetch
configuration in this PR should solve the problem.
Fixes #2685
=> [#2685] Configuration for pc_subscriber queue

app/models/vocabulary.rb, db/migrate/20220615201039_change_not_null_from_eid_in_vocabularies.rb, db/schema.rb, spec/models/access_mode_spec.rb, spec/models/access_type_spec.rb, spec/models/funding_body_spec.rb, spec/models/funding_program_spec.rb
Remove not null constraint in the database
and in the vocabulary model
Fixes #2643
=> [#2643] Remove presence validation in vocabularies `eid`

config/locales/en.yml
Date parameter format code `%e` isn't interpretted
as a one digit number (1 instead of 01) day
Changed `%e` to `%d`
=> [HOTFIX] Date parameter format

CHANGELOG.md, app/views/layouts/_navbar.html.haml
Add link to the `/api_docs` page under the
right `My EOSC Marketplace` menu
Closes #1785
=> [#1785] Add MP API link

config/initializers/devise.rb
Added new environmental variables for CheckIn configuration:
- `CHECKIN_ISSUER_URI` - full address of issuer
or `https://#{checkin_host}/oidc/`
- `CHECKIN_AUTHORIZATION_ENPOINT` - path, default: `/oidc/authorize`
- `CHECKIN_TOKEN_ENDPOINT` - path, default: `/oidc/token`
- `CHECKIN_USERINFO_ENDPOINT` - path, default: `/oidc/userinfo`
- `CHECKIN_JWKS_ENDPOINT` - path, default: `/oidc/jwk`
=> Add CheckIn configuration options

CHANGELOG.md, app/helpers/service_helper.rb, app/views/components/presentable/header_component/_provider_drop_down_menu.html.haml, app/views/components/presentable/header_component/_service_drop_down_menu.html.haml
Generate links to the Provider/Service dashboard
in PC depending on the catalogue
Fixes #2727
=> [#2727] Add catalogue specific links to PC

app/models/project.rb, app/serializers/recommender/project_serializer.rb, lib/recommender/serialize_db.rb, spec/lib/recommender_lib/serialize_db_spec.rb, spec/models/project_spec.rb, spec/models/publishable.rb, spec/serializers/recommender/project_serializer_spec.rb
As the title says. Added project_id, user_id and ids of services used in a project to the serializer.
NOTE: If a service is included more than one time in a project, (for example it has two offers with the same service), it is serialized as many times as it appears in the project - this is to provide additional data to the recommender team.
=> [#2716] Add project to recommender dump

CHANGELOG.md, Gemfile, app/controllers/concerns/service/recommendable.rb, app/controllers/services_controller.rb, config/application.rb, spec/features/service_spec.rb
Add recommendations to the service `show` page
You can set similar_services_host
using SIMILAR_SERVICES_HOST env variable
Closes #2754
=> [#2754] Add similar services recommendations

lib/tasks/migration.rake
Add task `rake migration:remove_unused_services`
with services given in `SERVICES_TO_DELETE` env variable
eg. 
```
SERVICES_TO_DELETE="eudat.b2share","eudat.b2safe"...
```
Task for removing services moved
to the datasources collection
=> Add task remove unused services

docs/upgrade/3.43.0.md, lib/tasks/migration.rake
Add migration task `rake migration:catalogue_data` 
for import missing catalogue for existing services and providers 
NOTICE!
Task depends on `MP_IMPORT_EOSC_REGISTRY_URL` env variable
=> [HOTFIX] `catalogue_data` task

app/javascript/app/user_action.js, app/views/comparisons/_service.html.haml, app/views/comparisons/show.html.haml, app/views/components/presentable/header_component/_order_buttons.html.haml, app/views/components/presentable/header_component/_service_drop_down_menu.html.haml, app/views/favourites/_service.html.haml, app/views/layouts/order.html.haml, app/views/services/_bundle_box.html.haml, app/views/services/_offer.html.haml, app/views/services/_offers_box.html.haml, app/views/services/_service.html.haml, app/views/services/_tabs.haml
Closes #2769.
Not every user-action probe sends information about the service id. It's not how the user actions were originally designed. The original use case involved constructing a tree out of user acitons where the service id would be in the root user action. We do not have access to service object in each of the views or sometimes it is not clear which service.id should be sent.
Alternative approach would be to redesign user action system, where each user action would be independent. "root" key in "source" would be changed to context, to add information about what situation the user action was clicked
=> [#2769] Adjust user actions

CHANGELOG.md, Gemfile.lock, README.md, config/application.rb, config/initializers/devise.rb, spec/mailers/project_item_spec.rb, spec/models/publishable.rb
Change endpoints in omniauth config
for AAI
Add new ENV `OIDC_AAI_OLD_API` to use old endpoints Closes #2856
=> [#2856] Set AAI to the new endpoints

app/views/components/presentable/sidebar_component/_monitoring.html.haml
Change text from "Read full monitoring on ARGO" to "Show more details"
in the link to the ARGO website
=> Change text for ARGO report link

app/serializers/recommender/provider_serializer.rb, app/serializers/recommender/service_serializer.rb, app/serializers/recommender/vocabulary/research_step_serializer.rb, lib/recommender/serialize_db.rb, spec/serializers/recommender/service_serializer_spec.rb
closes #2880 
This PR adds to the RS dump:
1) research_steps and horizontal,
2) providers' pids.
=> [#2880] research steps, horizontal, providers pid  in the rs dump

README.md, app/helpers/landing_page_helper.rb, app/views/pages/landing_page.html.haml, config/application.rb, docs/upgrade/3.47.0.md
Change hardcoded link to
customizable by ENV `USER_DASHBOARD_URL`
and default `https://my.eosc-portal.eu/`
Closes #2926
=> [#2926] Change link to the User Dashboard

app/helpers/application_helper.rb, app/views/layouts/_navbar.html.haml, app/views/layouts/_sections.html.haml, test/system/cypress/integration/regression_tests/service-page/favourites/favourites.spec.ts, test/system/cypress/integration/regression_tests/service-page/my_eosc_marketplace/my-profile.spec.ts, test/system/cypress/integration/regression_tests/service-page/my_eosc_marketplace/my-project.spec.ts
* Add queryiest to back to search link in navbar, so category and query is preserved
* Update commons header params to use default eosc-commons links
=> feat: Back to search query

app/helpers/landing_page_helper.rb, app/helpers/presentable/details_helper.rb, app/javascript/stylesheets/_bootstrap-customizations.scss
Added guidelines link to landing page. Size of the font had to be changed in order not to have line wrapping in link buttons.
Also - changed name of the guidelines in service's details
=> feat: Guidelines link from external landing

app/controllers/services/ordering_configuration/bundles_controller.rb, app/helpers/search_links_helper.rb, app/models/service.rb, app/policies/ordering_configuration/bundle_policy.rb, app/views/layouts/common_parts/services/_bundle_box.html.haml, app/views/layouts/common_parts/services/_offers.html.haml, app/views/services/ordering_configuration/bundles/edit.html.haml, app/views/services/ordering_configuration/bundles/new.html.haml, config/routes.rb
Remove link to add new bundle
in the ordering_configuration path
Closes #2979
=> fix:[#2979] Remove "Add new bundle" from OC

CHANGELOG.md, README.md, app/models/bundle.rb, app/models/offer.rb, app/models/provider.rb, app/models/service.rb, app/services/application_service.rb, app/services/bundle/ess/add.rb, app/services/bundle/ess/delete.rb, app/services/ess/update.rb, app/services/offer/ess/add.rb, app/services/offer/ess/delete.rb, app/services/provider/ess/add.rb, app/services/provider/ess/delete.rb, app/services/service/ess/add.rb, app/services/service/ess/delete.rb, config/ess_update.yml, docs/upgrade/3.47.0.md, docs/upgrade/3.48.0.md, lib/tasks/ess.rake, spec/features/backoffice/services_spec.rb, spec/models/service_spec.rb
Add task rake ess:dump["#{collection}"] to get collections in json dump. Possible options:
- all
- providers
- services
- offers
- bundles and arrays like `ess:dump["services datasources"]
@wziajka description of connecting to the transformation API described in docs. The variables should be set on the worker container.
=> feat:[] Create task to create SOLR dumps

CHANGELOG.md, app/views/services/_bundled_offer.html.haml, app/views/services/configurations/_bundled_offers.html.haml, app/views/services/configurations/show.html.haml, app/views/services/summaries/_bundle_technical.html.haml
Change "Provided by" fields from service name
to resource organisation name
Closes #2996
=> fix:[#2996]Change provided by to resource organisation

README.md, app/controllers/api/v1/ess/application_controller.rb, config/application.rb
Change cache ttl to be configurable via env variable, changed default to `60 seconds`.
Testing changes should be done in `60 seconds` intervals, are within that time data is being cached.
=> feat: Resource cache ttl can be defined via env variable

app/controllers/providers/logos_controller.rb, app/controllers/services/logos_controller.rb, config/routes.rb
* Add logo redirect endpoint to services and providers
How to test - `/logo` endpoint has been added to services and providers - so on the details page of the service / provider add `/logo` to the link. You should be redirected to the image.
Eg. `https://marketplace-11.docker-fid.grid.cyf-kr.edu.pl/services/eosc.egi-fed.cloud_compute/logo`
(Provider) eg. `https://marketplace-11.docker-fid.grid.cyf-kr.edu.pl/providers/eosc.upv-es/logo`
=> feat: add logo redirect endpoint

CHANGELOG.md, app/controllers/concerns/service/recommendable.rb, app/models/bundle.rb, app/models/offer.rb, app/policies/backoffice/bundle_policy.rb, app/policies/backoffice/offer_policy.rb, app/serializers/ess/bundle_serializer.rb, app/serializers/ess/offer_serializer.rb, app/views/backoffice/services/bundles/_form.html.haml, app/views/backoffice/services/form/_classification.html.haml, app/views/backoffice/services/offers/_form.html.haml, swagger/v1/ess/bundle/bundle_read.json, swagger/v1/ess/offer/offer_read.json
Add tags (keywords) to the backoffice forms for offers and bundles. It allows sending tags to the SOLR directly from an offer/bundle.
This PR Is created upon @roksanaer's request.
We can also change a schema for SOLR in this PR, but it should be discussed with @Michal-Kolomanski
=> feat:[] Add tags to offers and bundles

app/helpers/search_links_helper.rb, app/models/service.rb
This PR fixes provider filter links
from the marketplace to the Search Service
Closes #3038
=> fix:[#3038] Provider filter links in Search Service

app/controllers/backoffice/services/offers/drafts_controller.rb, app/models/offer.rb, app/services/offer/application_service.rb, app/services/offer/create.rb, app/services/offer/destroy.rb, app/services/offer/draft.rb, app/services/offer/publish.rb, app/services/offer/update.rb, spec/services/offer/draft_spec.rb
Unify behavior of drafting and deleting offers
Now it removes just the current offer regardless
of the action changing the offer's status
Closes #3057
=> fix:[#3057] Removing offer from bundle by draft/delete

app/controllers/services/summaries_controller.rb, app/models/project_item.rb, app/models/project_item/wizard.rb, app/services/project_item/create.rb, app/views/services/configurations/_bundled_offers.html.haml, app/views/services/configurations/_voucher.html.haml, app/views/services/configurations/show.html.haml, app/views/services/summaries/show.html.haml
Fix displaying unnecessary box
and change showing main_offer.name
instead of bundle.name
Closes #3072, #3078
=> fix:[#3072] Bundle configuration's step regression

CHANGELOG.md, app/components/presentable/header_component.rb
This PR fixes "Ask a question about this resource" link in the datasource details page
Closes #3091
=> [#3091] Fix datasources question link

app/services/jms/manage_message.rb
This PR fixes an error caused by a change in the JMS message schema.
Removed `resourceExtras` from the `serviceBundle` entity.
=> fix: Fix JMS import

CHANGELOG.md, app/views/taggable/_details_section.html.haml
Remove interoperability patterns in the
tag_list in the bottom of the service view
Closes #3141
=> fix:[#3141] Remove interoperability patterns from tags

app/helpers/landing_page_helper.rb
Change link label from `All catalogs`
to `All resources`
Closes #3142
=> fix:[#3142] Change `all_catalogs` to `all_resources`

CHANGELOG.md, app/views/catalogues/show.html.haml, app/views/components/presentable/header_component/_provider_buttons.html.haml, app/views/providers/details/index.html.haml, app/views/providers/show.html.haml, spec/features/ordering_configuration_spec.rb
Add `suspended` grey view for `Provider`
and `Catalogue`
Closes
- #3201
- #3212
=> feat:[#3201, #3212] Handle `suspended` status in importable

CHANGELOG.md, app/controllers/catalogues/logos_controller.rb, config/routes.rb
Logo for catalogue is available under /catalogues/:id/logo
=> feat:[]Add logos endpoint for catalogues
