cyfronet-fid/marketplace

- CHANGELOG.md
- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/policies/application_policy.rb
[Pundit](https://github.com/varvet/pundit) is used to check if user is allowed to enter concrete application section or to perform specific action.
> Pundit for user authorization

- CHANGELOG.md
- README.md
- config/environments/development.rb
- config/initializers/devise.rb
These variables are useful to push the application into a different place than localhost
> ENV variables to customize checkin and root url

- CHANGELOG.md
- README.md
- bin/setup
- bin/update
- lib/tasks/elasticsearch.rake
Added elasticsearch rake task, incorporated it into setup and update scripts. Added known issues concerning elastic search install on debian based systems
Fixes #16
> [#16] Fix bug with lack of elasticsearch indexes

- CHANGELOG.md
- Gemfile
- Gemfile.lock
With this theme, pagination has bootstrap 4 layout.
> Bootstrap 4 theme for will_paginate

- CHANGELOG.md
- README.md
- config/database.yml
On @michal-szostak request dedicated way to configure PostgreSQL though environment variables was added. Take a look into `README.md` database section for details.
> Configure dev, test database though ENV variables

- app/javascript/stylesheets/_bootstrap-customizations.scss
One color input and button outline & css header bg instead image
> [#59] One color outline & new header bg

- CHANGELOG.md
- app/javascript/stylesheets/_bootstrap-customizations.scss
- app/javascript/stylesheets/_footer.scss
- app/javascript/stylesheets/_variables.scss
- app/views/layouts/_footer.html.haml
- app/views/playground/static-tabs.html.haml
- app/views/services/_description.html.haml
- app/views/services/_opinions.html.haml
- app/views/services/_order.html.haml
- app/views/services/show.html.haml
- spec/features/orders_spec.rb
* tabs styling
* order content styling
> 59 tabs style

- CHANGELOG.md
- app/helpers/service_helper.rb
- app/views/services/_service.html.haml
- db/migrate/20180711132009_add_rating_to_service.rb
- db/schema.rb
- lib/tasks/dev.rake
- spec/helpers/service_helper_spec.rb
add rating field to Service in db, shows value in service list, add service_helper that prints stars based on rating value
fixes #72
> Add rating to Service

- CHANGELOG.md
- app/javascript/stylesheets/_bootstrap-customizations.scss
- app/views/orders/_order.html.haml
- app/views/orders/index.html.haml
> [#153] Style My Services

- CHANGELOG.md
- app/javascript/stylesheets/_bootstrap-customizations.scss
- app/javascript/stylesheets/_variables.scss
- app/views/playground/order-static.html.haml
- app/views/services/_order.html.haml
> [#150] Style Order Placement View

- CHANGELOG.md
- README.md
- db/schema.rb
- db/seeds.rb
fix problems with update and create categories and services
> 175 duplicated categories bugfix

- CHANGELOG.md
- README.md
- app/services/order/ready.rb
- db/data.yml
- db/schema.rb
- db/seeds.rb
- spec/services/order/ready_spec.rb
This PR update services and categories in yaml.
It creates category "Data & Storage" and services for this category.
> [#192] Update services and categories data

- CHANGELOG.md
- app/views/profiles/_newsletter.html.haml
- app/views/profiles/affiliations/_index.html.haml
- app/views/profiles/show.html.haml
Adapt profile view with tabs (affiliations and newsletter)
> [#182] Add tabs in My profile page

- README.md
* JIRA Webhook port should point into default rails port (5000)
* `MP_JIRA_WF_DONE` -> `MP_JIRA_WF_IN_DONE`
> Small jira configuration corrections in REAME.md

- CHANGELOG.md
- app/policies/backoffice/service_policy.rb
- app/services/jira/issue_updated.rb
- app/services/project_item/ready.rb
- app/views/backoffice/services/_form.html.haml
- app/views/backoffice/services/show.html.haml
- app/views/project_items/_project_item_change.html.haml
- db/migrate/20181026063221_add_activate_message_to_service.rb
- db/schema.rb
- spec/features/backoffice/services_spec.rb
- spec/services/jira/issue_updated_spec.rb
- spec/services/project_item/ready_spec.rb
Service owner can define a message which will be shown in the project item change when service becomes active
> Service activate message

- CHANGELOG.md
- app/javascript/stylesheets/_header.scss
- app/javascript/stylesheets/_order.scss
- app/javascript/stylesheets/application.scss
- app/views/layouts/_navbar.html.haml
- app/views/layouts/_order_nav.html.haml
- app/views/layouts/order.html.haml
- app/views/services/configurations/show.html.haml
- app/views/services/offers/index.html.haml
- app/views/services/summaries/show.html.haml
- spec/features/order_spec.rb
What is missing (for @kosmidma):
1. global button styling
2. order navbar styling (in `app/javascript/stylesheets/_order.scss` - in this file ale order specific elements should be palced)
This is how it looks like right now:
> Order layout

- app/models/project_item.rb
- app/policies/project_item_policy.rb
- app/views/services/configurations/show.html.haml
- app/views/services/summaries/show.html.haml
- db/migrate/20181025095231_add_usage_section_to_project_item.rb
- db/schema.rb
- spec/factories/project_items.rb
- spec/features/order_spec.rb
- spec/models/project_item_spec.rb
> [#245] Add to Configuration step Usage section

- CHANGELOG.md
- app/controllers/services/configurations_controller.rb
- app/models/affiliation.rb
- app/models/project_item.rb
- app/models/user.rb
- app/policies/project_item_policy.rb
- app/views/services/configurations/show.html.haml
- db/migrate/20181029181312_add_affiliation_ref_to_project_item.rb
- db/schema.rb
- spec/factories/project_items.rb
- spec/features/order_spec.rb
- spec/models/affiliation_spec.rb
- spec/models/project_item_spec.rb
- spec/models/user_spec.rb
> Select affiliation on service order configuration step

- app/views/services/offers/index.html.haml
This artifact was added during experimenting with the view and was not removed before commit.
> Remove static artifact from offer selection view

- CHANGELOG.md
- app/controllers/concerns/service/searchable.rb
- app/controllers/services_controller.rb
- app/views/services/_filters.html.haml
- app/views/services/index.html.haml
- db/schema.rb
- spec/features/service_spec.rb
Added filter for dedicated_for (backend & UI)
Fixes: #280
> [#280] Add search by "dedicated_for"

- CHANGELOG.md
- app/controllers/projects_controller.rb
- app/policies/project_policy.rb
- app/views/layouts/_modal.html.haml
- app/views/layouts/order.html.haml
- app/views/layouts/show_modal.js.erb
- app/views/projects/_form.html.haml
- app/views/projects/show.js.erb
- app/views/services/configurations/show.html.haml
- config/routes.rb
- spec/features/order_spec.rb
Ajax is used to show modal and created a new project. After a new project is created it is selected in `project_item` project select.
> Create new project on order configuration view

- app/controllers/services/summaries_controller.rb
- app/views/services/summaries/confirmation.html.haml
- config/breadcrumbs.rb
- spec/features/order_spec.rb
> Order congratulations view styles

- CHANGELOG.md
- app/views/project_items/_parameters.html.haml
- app/views/project_items/_project_item_change.html.haml
- app/views/project_items/_project_item_changes.html.haml
- app/views/project_items/_question.html.haml
- app/views/project_items/show.html.haml
- config/locales/en.yml
- spec/features/my_services_spec.rb
> Style service order view and remove mocked data

- CHANGELOG.md
- app/controllers/services/summaries_controller.rb
- app/models/confirmation.rb
- app/views/services/summaries/show.html.haml
- config/locales/simple_form.en.yml
- spec/features/order_spec.rb
> User need to accept terms and services before ordering service

- CHANGELOG.md
- app/views/services/configurations/show.html.haml
- config/initializers/simple_form_bootstrap.rb
Currently, custom class adding condition was added. In the feature, we need to take a look why in `simple_form` classes are not added into `input_field`.
> Fix project validation is not shown

- CHANGELOG.md
- app/controllers/projects_controller.rb
- app/views/projects/index.html.haml
- config/brakeman.ignore
- spec/features/my_services_spec.rb
> [#135] Added filter by status on my services view

- CHANGELOG.md
- app/controllers/concerns/service/searchable.rb
- app/controllers/services_controller.rb
- app/helpers/multicheckbox_helper.rb
- app/javascript/controllers/multicheckbox_controller.js
- app/javascript/stylesheets/_bootstrap-customizations.scss
- app/javascript/stylesheets/_variables.scss
- app/models/provider.rb
- app/views/services/_filters.html.haml
- app/views/services/index.html.haml
- db/schema.rb
- spec/features/service_spec.rb
- yarn.lock
* Style `_filters.html.haml` (sizing and positioning)
* Add multicheckbox widget
* Change providers and dedicated for to be multicheckbox widget
* Modify `searchable.rb` to work with multiselects
All changes are connected to filter sidebar which can be accessed via `/services` path
Fixes: #287
> [#287] Add Multiselect

- CHANGELOG.md
- app/javascript/stylesheets/_bootstrap-customizations.scss
- app/javascript/stylesheets/_order.scss
- app/javascript/stylesheets/_variables.scss
- app/views/layouts/order.html.haml
- app/views/services/configurations/show.html.haml
- app/views/services/offers/_offer.html.haml
- app/views/services/offers/index.html.haml
- app/views/services/summaries/show.html.haml
Zmiany dot. checkoutu zgodnie z prewkami.
> [#317] styling order steps

- app/controllers/categories_controller.rb
- app/views/categories/show.html.haml
- app/views/services/index.html.haml
* Remove description field in `/services`
* Add category description for category in `/categories`
* Add sorting widget to categories + enable sorting in
`categories_controller.rb`
Fixes: #325, #326
> [#325, #326] Service / Category Fix

- app/helpers/service_helper.rb
- app/javascript/stylesheets/_bootstrap-customizations.scss
- app/javascript/stylesheets/application.scss
- app/views/layouts/_footer.html.haml
- app/views/layouts/_navbar.html.haml
- app/views/services/_about.html.haml
- app/views/services/_categorization.html.haml
- app/views/services/_filters.html.haml
- app/views/services/_header.html.haml
- app/views/services/_related.html.haml
- app/views/services/_service.html.haml
- app/views/services/_service_box.html.haml
- app/views/services/_tabs.haml
- app/views/services/show.html.haml
- spec/helpers/service_helper_spec.rb
-  changed links in main navigation and footer
- new size for images
- service detail - new design almost similar to graphic previews
- related services card
- various graphic changes
> 321 service detail design improvement

- CHANGELOG.md
- app/views/project_items/_project_item_changes.html.haml
- app/views/project_items/show.html.haml
> [#328] On project item view show order history in reversed order

- app/javascript/stylesheets/_header.scss
- app/javascript/stylesheets/_variables.scss
- app/views/categories/_subcategories.html.haml
- app/views/categories/show.html.haml
- app/views/layouts/order.html.haml
- app/views/profiles/affiliations/_index.html.haml
- app/views/profiles/show.html.haml
- app/views/services/_categorization.html.haml
- app/views/services/_header.html.haml
- app/views/services/_service.html.haml
- app/views/services/_service_box.html.haml
- app/views/services/index.html.haml
- app/views/services/offers/index.html.haml
headers, some texts (e.g. in service box) have new styles
> - headers, fonts, links

- app/services/affiliation/create.rb
Reverts cyfronet-fid/marketplace#339
> Revert "Force token generation before saving affiliation"

- app/views/services/offers/_offer.html.haml
We should be aware that there is TODO, otherwise, we will forget about it.
> Uncomment offer attribute section

- app/views/services/offers/_offer.html.haml
we decided to remove for now (needed for tomorrow's meeting) the parameters from the offers on the service entry and 1st order step
> Revert "Uncomment offer attribute section"

- db/data.yml
- db/seeds.rb
Add new relations between services
Add placeholders for services which are included in demos,
but there's no information about them.
> New relations between services

- app/views/projects/show.js.erb
Project ajax response created a global variable when trying to add second the project we were trying to define the same variable for the second time. Adding local block fixes problem.
Fixes #372
> Local js variable on ajax response

- app/views/services/_categorization.html.haml
Display dedicated form on service entry view and services list 
Fix: #386
> [#386] Display dedicated for

- app/javascript/stylesheets/_order.scss
wrzuciłem na świeżo definicje nawigacji na checkoucie
> checkout arrows

- CHANGELOG.md
- app/controllers/concerns/service/searchable.rb
- app/helpers/service_helper.rb
- app/models/service.rb
- app/views/services/_about.html.haml
- db/data.yml
- db/migrate/20181003095650_add_details_to_services.rb
- db/migrate/20181102122138_change_dedicated_for_to_array.rb
- db/schema.rb
- spec/models/service_spec.rb
#385 
https://github.com/rails/rails/issues/13127   reasons for changes in searchable.rb
> Conditional display on service details view

- CHANGELOG.md
- app/views/project_items/show.html.haml
> [#369] Add service link to project item view

- app/mailers/affiliation_mailer.rb
- spec/mailers/affiliation_spec.rb
@kmarszalek thx for spotting this issue.
> Fix affiliation confirmation email address

- app/mailers/affiliation_mailer.rb
- db/data.yml
- spec/mailers/affiliation_spec.rb
Add Alien and Invasive Species service
Update WeNMR services
> Service update

- app/services/project_item/create.rb
- app/services/project_item/ready.rb
- spec/services/project_item/create_spec.rb
- spec/services/project_item/ready_spec.rb
> Don't send ready email for open access service

- CHANGELOG.md
- app/controllers/categories_controller.rb
- app/controllers/concerns/service/searchable.rb
- app/controllers/services_controller.rb
- app/models/platform.rb
- app/models/service.rb
- app/models/service_related_platform.rb
- app/policies/backoffice/service_policy.rb
- app/views/backoffice/services/_form.html.haml
- app/views/categories/show.html.haml
- app/views/services/_about.html.haml
- app/views/services/_filters.html.haml
- app/views/services/_index.html.haml
- app/views/services/index.html.haml
- db/data.yml
- db/migrate/20181116084141_create_platforms.rb
- db/migrate/20181116085809_create_service_related_platforms.rb
- db/schema.rb
- db/seeds.rb
- lib/tasks/dev.rake
- spec/factories/platforms.rb
- spec/factories/services.rb
- spec/features/backoffice/services_spec.rb
- spec/features/service_spec.rb
- spec/models/platform_spec.rb
- spec/models/service_related_platform_spec.rb
Service can have many related platforms. 
Its possible to filter services by platform. 
Platform are not displayed anywhere for now.
Fix #410, #411
> 410 related infrastructures and platforms

- db/data.yml
> 418 update database entries

- CHANGELOG.md
- app/views/services/_header.html.haml
- spec/features/order_spec.rb
> Show "Go to the service" for catalog services

- spec/features/service_spec.rb
@michal-szostak please, please, please don't commit puts.
> Remove puts

- app/views/home/_products.html.haml
> Spell correction on landing page

- app/views/project_items/show.html.haml
> Improve ordered service link text

- app/views/projects/index.html.haml
- config/locales/simple_form.en.yml
- spec/features/my_services_spec.rb
> Project item status translation

- CHANGELOG.md
- app/controllers/concerns/service/sortable.rb
- spec/controllers/concerns/sortable_spec.rb
* changed default services ordering to :title :asc
Fixes: #442
> [#442] Default sort order of services

- CHANGELOG.md
- app/controllers/services_controller.rb
- app/models/service.rb
- spec/factories/services.rb
> [#455] Platforms are not mandatory

- CHANGELOG.md
- app/views/layouts/_footer.html.haml
- app/views/layouts/footer/_root_category.html.haml
> Update base url for footer links

- db/data.yml
removal of duplicated services
commenting services not ready for the launch
> cleaning services

- CHANGELOG.md
- README.md
- app/mailers/application_mailer.rb
`FROM_EMAIL` should be set in 100% in the production environment.
> Customizable from email

- app/controllers/concerns/service/searchable.rb
- app/views/services/_filters.html.haml
- spec/features/service_spec.rb
> [#379] Add clear filters button

- CHANGELOG.md
- app/javascript/packs/application.js
- app/javascript/packs/flash.js
- app/javascript/stylesheets/_flash.scss
- app/javascript/stylesheets/application.scss
- app/views/layouts/_flash.html.haml
> Flash fade out after 5 seconds

- app/views/services/_ask_question.html.haml
- db/data.yml
- spec/features/service_spec.rb
change in 'please login to ask a question' button label
removing not specified taglines
removing typo 'reaserchers'
recategorisation of bfaccess
adding relaiton between lrs and b2drop
fixes in clarin entries
> updates for the launch

- app/views/backoffice/services/_service.html.haml
- app/views/home/_products.html.haml
- app/views/home/index.html.haml
- app/views/layouts/_flash.html.haml
- app/views/services/_ask_question.html.haml
- app/views/services/_categorization.html.haml
- app/views/services/_filters.html.haml
- app/views/services/_service_box.html.haml
- app/views/services/configurations/show_normal.html.haml
- config/locales/en.yml
- spec/features/affiliation_confirmations_spec.rb
- spec/features/alerts_spec.rb
- spec/features/service_spec.rb
> Labels improvements

- CHANGELOG.md
- app/views/affiliation_mailer/verification.html.haml
- app/views/affiliation_mailer/verification.text.haml
- app/views/project_item_mailer/created.html.haml
- app/views/project_item_mailer/created.text.haml
- app/views/project_item_mailer/new_message.html.haml
- app/views/project_item_mailer/new_message.text.haml
- app/views/service_mailer/new_question.html.haml
- app/views/service_mailer/new_question.text.haml
- spec/mailers/project_item_spec.rb
Improve wording of service, affiliation and project item related mails.
Fixes: #518.
> [#518] Mail content improvements

- CHANGELOG.md
- app/controllers/categories_controller.rb
- app/controllers/concerns/service/searchable.rb
- app/controllers/services_controller.rb
- app/helpers/service_helper.rb
- app/models/service.rb
- app/models/service_target_group.rb
- app/models/target_group.rb
- app/policies/backoffice/service_policy.rb
- app/views/backoffice/services/_form.html.haml
- app/views/backoffice/services/show.html.haml
- app/views/categories/show.html.haml
- app/views/services/_filters.html.haml
- app/views/services/_index.html.haml
- app/views/services/_service_box.html.haml
- app/views/services/index.html.haml
- db/data.yml
- db/migrate/20181121100702_create_target_groups.rb
- db/migrate/20181121101654_create_service_target_groups.rb
- db/schema.rb
- db/seeds.rb
- lib/tasks/dev.rake
- spec/controllers/concerns/searchable_spec.rb
- spec/factories/target_groups.rb
- spec/features/backoffice/services_spec.rb
- spec/features/service_spec.rb
- spec/models/service_target_group_spec.rb
- spec/models/target_group_spec.rb
> [#277] dedicated for is saved in db

- app/views/services/_ask_question.html.haml
- db/data.yml
- spec/features/service_spec.rb
removal of a dot in 'ask a question' phrase in the service entry.
update or PaN Faas URL
> Ask a question fix

- app/views/layouts/_footer.html.haml
> privacy policy Url change

- CHANGELOG.md
- app/models/jira/checker.rb
- app/models/jira/client.rb
- app/services/project_item/ready.rb
- app/services/project_item/register.rb
- config/jira.yml
- lib/jira/console_checker.rb
- spec/factories/project_items.rb
- spec/lib/jira/console_checker_spec.rb
- spec/models/jira/checker_spec.rb
- spec/models/jira/client_spec.rb
- spec/services/project_item/ready_spec.rb
- spec/services/project_item/register_spec.rb
* Add custom fields mapping for JIRA
* Add custom field checks and suggestions to checked (and
`rake jira:check` task)
Fixes: #466
> [#466] Mapping order (project item) data to JIRA issue

- app/models/jira/client.rb
- config/jira.yml
- spec/models/jira/client_spec.rb
* changed: `CI-DepartamentalWebPage` to `CI-DepartmentalWebPage`
Fixes: #466
> [#466] Fix misspell in attribute name

- CHANGELOG.md
- app/controllers/concerns/service/searchable.rb
- app/models/service.rb
- app/policies/backoffice/service_policy.rb
- app/views/backoffice/services/_form.html.haml
- app/views/backoffice/services/show.html.haml
- spec/controllers/concerns/searchable_spec.rb
- spec/factories/services.rb
- spec/features/backoffice/services_spec.rb
- spec/models/service_spec.rb
Service can be created with categories in backoffice.
Fixed service_count problem which occurred during implementation
Fix #536
> 536 backoffice service category

- app/controllers/project_items/service_opinions_controller.rb
- app/helpers/project_items_helper.rb
- app/models/service_opinion.rb
- app/views/project_items/service_opinions/_form.html.haml
- app/views/project_items/show.html.haml
- app/views/service_opinions/_service_opinion.html.haml
- spec/helpers/project_items_helper_spec.rb
- spec/services/service_opinion/create_spec.rb
#563
#567
#562
- button visible right after service being ready
- added validation of service_opinion uniqueness
> Rating button visibility and uniqueness validation

- CHANGELOG.md
- app/controllers/services/opinions_controller.rb
- app/models/service_opinion.rb
- app/policies/service_opinion_policy.rb
- app/services/service_opinion/update_service.rb
- app/views/project_items/service_opinions/_stars.html.haml
- app/views/project_items/service_opinions/new.haml
- app/views/project_items/show.html.haml
- app/views/service_opinions/_service_opinion.html.haml
- app/views/services/opinions/index.html.haml
- db/migrate/20181205143939_add_order_rating_and_change_rating_to_service_rating_for_service_opinions.rb
- db/schema.rb
- spec/helpers/project_items_helper_spec.rb
- spec/models/service_opinion_spec.rb
- spec/services/service_opinion/create_spec.rb
- spec/services/service_opinion/update_spec.rb
#566
upgraded views for further styling for rating, changed rating to service_rating and added order_rating.
added validation of service_opinion uniqueness per project_item
EDIT:
also waiting for ok for text and wording of hints.
> Change rating style and add service_rating and order_rating

- app/views/home/_products.html.haml
#541 
remove "all" -> "find the services you need"
> Home page text change

- app/javascript/stylesheets/_bootstrap-customizations.scss
- app/views/project_items/service_opinions/_stars.html.haml
- app/views/project_items/service_opinions/new.haml
- app/views/service_opinions/_service_opinion.html.haml
#571 - complete implementation of new graphic design for reviews tab in service detail and review form
> Reviews layout

- app/javascript/stylesheets/_bootstrap-customizations.scss
- app/javascript/stylesheets/_footer.scss
- app/javascript/stylesheets/_header.scss
- app/views/layouts/_breadcrumb.html.haml
- app/views/layouts/_footer.html.haml
- app/views/services/_about.html.haml
- app/views/services/_filters.html.haml
- app/views/services/_header.html.haml
- app/views/services/_index.html.haml
- app/views/services/_offer.html.haml
- app/views/services/_offers.html.haml
- app/views/services/_paginate.haml
Responsive modifications for:
1. Homepage view
2. Services list view
3. Service description page view
Modifications of header and footer.
> RWD modifications

- app/models/jira/client.rb
- spec/models/jira/client_spec.rb
* Add separator `?` between service offer and service parameters
Fixes: #568
> [#568] Add separator to in SO

- CHANGELOG.md
- app/helpers/service_helper.rb
> Fix typos in terms and conditions hint

- CHANGELOG.md
- app/controllers/projects_controller.rb
- app/javascript/controllers/project_item_controller.js
- app/javascript/stylesheets/_bootstrap-customizations.scss
- app/models/jira/checker.rb
- app/models/project.rb
- app/models/project_item.rb
- app/policies/project_item_policy.rb
- app/policies/project_policy.rb
- app/views/projects/_form.html.haml
- app/views/services/configurations/_customer_typology_fields.html.haml
- app/views/services/configurations/_private_company.html.haml
- app/views/services/configurations/show_normal.html.haml
- config/jira.yml
- config/locales/simple_form.en.yml
- db/migrate/20181212102330_add_additional_customer_typology_fields_to_project_item_and_project.rb
- db/schema.rb
- docs/jira_integration.md
- spec/factories/project_items.rb
- spec/factories/projects.rb
- spec/features/order_spec.rb
- spec/models/project_item_spec.rb
Additional fields are added dynamically after selecting customer typology on configuration step or project  creation view.
Fixed: #581
> [#581] Add customer typology connected fields

- CHANGELOG.md
- app/views/services/offers/_offer.html.haml
issue #626 fix for service offer selection RWD
Fixes:  #626
> [#626] service offer selection RWD mods

- CHANGELOG.md
- app/views/services/configurations/show_normal.html.haml
> Fix show research area errors on order configuration view

- CHANGELOG.md
- app/controllers/backoffice/platforms_controller.rb
- app/policies/backoffice/platform_policy.rb
- app/views/backoffice/platforms/_form.html.haml
- app/views/backoffice/platforms/edit.html.haml
- app/views/backoffice/platforms/index.html.haml
- app/views/backoffice/platforms/new.html.haml
- app/views/backoffice/platforms/show.html.haml
- app/views/layouts/backoffice/_navbar.html.haml
- config/breadcrumbs/backoffice.rb
- config/routes.rb
- spec/features/backoffice/platforms_spec.rb
- spec/policies/backoffice/platform_policy_spec.rb
- spec/requests/backoffice/platforms_spec.rb
Views are similar like in #645
Fixes #649 
Fixes #650
> Basic CRUD for backoffice Platforms

- app/javascript/controllers/service_offer_controller.js
- app/views/services/_offer.html.haml
Fixed show more  on service offer view. For now user cannot hide additional text.
> Fixed section show-more on service offert view

- app/controllers/api/webhooks/jiras_controller.rb
- app/mailers/project_item_mailer.rb
- app/views/project_item_mailer/created.html.haml
- app/views/project_item_mailer/created.text.haml
- spec/mailers/project_item_spec.rb
Added new line in project item created layout.
Fixed sanding emails bug. Mails was sanding to emails consisting of name and surname.
> Added new line in emails project_item/created

- CHANGELOG.md
- app/controllers/backoffice/services_controller.rb
- app/models/service.rb
- app/models/service_source.rb
- app/policies/backoffice/service_policy.rb
- app/views/backoffice/services/_form.html.haml
- app/views/backoffice/services/show.html.haml
- db/migrate/20190128132837_create_service_sources.rb
- db/migrate/20190128142124_add_upstream_to_service.rb
- db/schema.rb
- spec/factories/service_sources.rb
- spec/factories/services.rb
- spec/features/backoffice/services_spec.rb
- spec/models/service_source_spec.rb
- spec/models/service_spec.rb
* Add external sources to db schema & migrations
* Modify backoffice service's form to accomodate above data
Fixes #656
> [#656] Add External Sources info to Service

- CHANGELOG.md
- app/mailers/project_item_mailer.rb
- app/views/project_items/show.html.haml
- spec/factories/project_items.rb
- spec/features/my_services_spec.rb
* Fix `ProjectItem` details view crash for open access services
Fixes #668
> [#668] ProjectItem details view crash Fix

- CHANGELOG.md
- db/migrate/20190130130546_change_eid_to_be_string_in_service_sources.rb
- db/schema.rb
- spec/features/backoffice/services_spec.rb
* Change type of Service Sources eid type to string
Fixes: #656
> [#656, HOTFIX] Service Source EID type change

- CHANGELOG.md
- app/models/service.rb
- config/locales/simple_form.en.yml
- spec/models/service_spec.rb
#654 
it was decided that for now i will add hint under the url input and remove leading and trailing spaces before validation.
> #654 backoofice url validation

- README.md
- app/views/layouts/_footer.html.haml
Second link available in Marketplace section
Update Readme.md with information about Marketplace
> Add second link to about page in footer

- .travis.yml
- CHANGELOG.md
- app/models/service.rb
- app/views/backoffice/services/show.html.haml
- app/views/services/_about.html.haml
- config/locales/simple_form.en.yml
- db/data.yml
- db/migrate/20190215073516_update_service_phase_values.rb
- lib/tasks/dev.rake
- spec/features/backoffice/services_spec.rb
Use `keys` instead of enum names.
> Change service phase enum values into keys

- CHANGELOG.md
- app/helpers/formats_helper.rb
- app/models/attribute/date.rb
- app/views/services/configurations/attributes/_date.html.haml
- spec/models/attribute/date_spec.rb
> Date attribute min and max validation

- CHANGELOG.md
- app/mailers/project_item_mailer.rb
- app/services/jira/issue_updated.rb
- app/views/project_item_mailer/aod_voucher_accepted.html.haml
- app/views/project_item_mailer/aod_voucher_accepted.text.haml
- app/views/project_item_mailer/aod_voucher_rejected.html.haml
- app/views/project_item_mailer/aod_voucher_rejected.text.haml
- spec/mailers/previews/project_item_preview.rb
- spec/mailers/project_item_spec.rb
- spec/services/jira/issue_updated_spec.rb
Added new email about aod_rejection
Changed content and subject emails about acceptance
Fix #707
> [#707] Voucher emails update

- CHANGELOG.md
- app/javascript/stylesheets/_bootstrap-customizations.scss
- app/javascript/stylesheets/_variables.scss
- app/views/project_items/_project_item_change.html.haml
- app/views/project_items/_project_item_changes.html.haml
- app/views/project_items/_question.html.haml
- app/views/project_items/show.html.haml
@michal-szostak this branch has a problem with tests.
> Service order detail

- CHANGELOG.md
- app/views/project_items/show.html.haml
- db/schema.rb
- spec/features/my_services_spec.rb
* Show Voucher ID if it's set
* Show `Voucher: Requested` if ID is not present, but voucher has
been requested
> Show Voucher ID in project_item details

- app/javascript/stylesheets/_bootstrap-customizations.scss
- app/views/backoffice/categories/index.html.haml
- app/views/backoffice/platforms/index.html.haml
- app/views/backoffice/providers/index.html.haml
- app/views/backoffice/research_areas/index.html.haml
- app/views/backoffice/research_areas/show.html.haml
- app/views/backoffices/show.html.haml
- spec/features/backoffice/research_areas_spec.rb
One thing - on the list there ae buttons "edit" and "delete" icon. They need to be implemented - now they are static. 
Can anybody add those buttons?
> Back office research areas list

- CHANGELOG.md
- app/controllers/backoffice/services/offers/drafts_controller.rb
- app/controllers/backoffice/services/offers/publishes_controller.rb
- app/controllers/backoffice/services/offers_controller.rb
- app/controllers/services_controller.rb
- app/helpers/backoffice/services_helper.rb
- app/models/offer.rb
- app/policies/backoffice/offer_policy.rb
- app/policies/offer_policy.rb
- app/policies/service_policy.rb
- app/services/offer/draft.rb
- app/services/offer/publish.rb
- app/services/service/draft.rb
- app/views/backoffice/services/offers/_offer.html.haml
- app/views/backoffice/services/offers/_offers.html.haml
- config/routes.rb
- db/migrate/20190121103333_add_status_to_offer.rb
- db/schema.rb
- db/seeds.rb
- spec/factories/offers.rb
- spec/features/backoffice/services_spec.rb
- spec/features/service_spec.rb
- spec/policies/backoffice/offer_policy_spec.rb
- spec/policies/service_policy_spec.rb
- spec/services/service/draft_spec.rb
- spec/services/service/publish_spec.rb
> [#584] Add status to service

- app/views/profiles/affiliations/_affiliation.html.haml
- app/views/project_items/show.html.haml
> service details affiliation fix

- .travis.yml
- CHANGELOG.md
- app/models/attribute/range.rb
- app/views/services/configurations/attributes/_range.html.haml
- config/application.rb
- config/initializers/session_store.rb
- db/data.yml
- spec/features/order_spec.rb
- spec/models/attribute_spec.rb
Fixed services creation from yaml
> Fixed parameters from yaml

- CHANGELOG.md
- app/javascript/controllers/service_controller.js
- app/views/backoffice/services/_form.html.haml
- config/locales/simple_form.en.yml
> [#736] Backoffice service form updated

- app/views/project_item_mailer/changed.html.haml
- app/views/project_item_mailer/changed.text.haml
> [#675] Project item status changed email update

- CHANGELOG.md
- app/models/attribute.rb
- app/models/attribute/range.rb
- app/models/attribute/select.rb
- spec/models/attribute_spec.rb
Fix for #741
There is some strange behavior in Firefox. But as a fix this much is alright. 
More in depth fix / change should be considered in the future.
Fixes: #741
> [#741] Fix server error when validating mistyped integers

- CHANGELOG.md
- README.md
- app/controllers/backoffice/services/offers_controller.rb
- app/views/backoffice/services/offers/_form.html.haml
- app/views/backoffice/services/offers/edit.html.haml
- app/views/backoffice/services/offers/new.html.haml
Add a custom label with link to the tutorial
> Add link to the tutorial of attributes in backoffice

- CHANGELOG.md
- app/helpers/categories_helper.rb
- app/views/backoffice/categories/nav/_category.html.haml
- app/views/backoffice/services/index.html.haml
- app/views/services/_search.html.haml
- app/views/services/nav/_categories.html.haml
- app/views/services/nav/_category.html.haml
> Change filter cleaning strategies

- CHANGELOG.md
- app/views/services/summaries/show_open_access.html.haml
> Show accept terms and conditions only when url is defined

- CHANGELOG.md
- app/models/project_item.rb
- app/models/project_item/attributes.rb
- app/models/project_item/customization.rb
The code was simplified a bit. This change was extracted from a bundled offer push request (#719).
> Project item attributes refactor

- CHANGELOG.md
- app/controllers/profiles/affiliations_controller.rb
> Show 404 error page when affiliation is not found

- CHANGELOG.md
- app/models/jira/client.rb
- spec/models/jira/client_spec.rb
> SO-1 jira field as json

- CHANGELOG.md
- config/environments/production.rb
Fixes #807. See also #807 how to test this.
> Use custom error pages in production environment

- CHANGELOG.md
- app/controllers/backoffice/services_controller.rb
- app/controllers/concerns/service/autocomplete.rb
- app/controllers/services_controller.rb
- app/javascript/controllers/autocomplete_controller.js
- app/javascript/stylesheets/_header.scss
- app/models/service.rb
- app/views/backoffice/services/_search.html.haml
- app/views/services/_search.html.haml
- config/routes.rb
- package-lock.json
- package.json
- spec/features/service_spec.rb
- yarn.lock
Added elasticsearch autocomplete. 
I use https://github.com/afcapel/stimulus-autocomplete but copied to our repository.
> Elasticsearch autocomplete

- db/seeds.rb
Add to seeds.rb creating empty array if parameters are not specified.
> Hotfix for bad working seeds

- CHANGELOG.md
- app/views/services/configurations/_attributes.html.haml
- lib/import/eic.rb
- spec/features/service_spec.rb
- spec/lib/import/eic_spec.rb
- spec/models/service_relationship_spec.rb
- spec/rails_helper.rb
> Remove std out/err from test suite output

- CHANGELOG.md
- app/views/service_opinions/_service_opinion.html.haml
- spec/factories/service_opinion.rb
- spec/features/opinions_spec.rb
> Fix show open access service opinions

- CHANGELOG.md
- app/views/services/_paginate_simple.haml
- app/views/services/nav/_categories.html.haml
- app/views/services/nav/_category.html.haml
- config/brakeman.ignore
Now after change number of items on page, page is reset to 1.
> [#795] Fix reset page after changing number of items on page

- db/schema.rb
I hope that it is a last time I need to create such commit - beware!
> Once again remove non existing model db tables

- CHANGELOG.md
- app/controllers/concerns/service/autocomplete.rb
- app/javascript/controllers/autocomplete_controller.js
It's minor enhancement connected to PR #802
> Autocomplete content are serve only from ajax request

- app/views/services/configurations/_voucher.html.haml
> radio buttons width

- CHANGELOG.md
- app/views/services/index.html.haml
> Unescape service query when showing to the user

- CHANGELOG.md
- app/controllers/concerns/service/categorable.rb
- app/models/categorization.rb
- app/models/category.rb
- app/models/platform.rb
- app/models/provider.rb
- app/models/service.rb
- app/models/target_group.rb
- db/migrate/20190426144042_change_service_category_to_categorization.rb
- db/schema.rb
- spec/models/service_spec.rb
> Rename ServiceCategory to Categorization

- CHANGELOG.md
- app/controllers/concerns/service/searchable.rb
- app/helpers/backoffice/services_helper.rb
- app/helpers/service_helper.rb
- app/javascript/controllers/autocomplete_controller.js
- app/models/service.rb
- app/views/backoffice/services/_search.html.haml
- app/views/backoffice/services/_service.html.haml
- app/views/services/_service.html.haml
- config/routes.rb
Added tagline to elasticsearch index
Setted different weights for elasticsearch fields
Added highlights for tagline
Changed autocomplete routing and fixed autocomplete function
Fix #856
> Elasticsearch index changes

- app/controllers/projects_controller.rb
- app/views/projects/_form.html.haml
- app/views/projects/index.html.haml
- app/views/projects/new.html.haml
- config/breadcrumbs/marketplace.rb
- config/locales/simple_form.en.yml
- spec/features/projects_spec.rb
Project can be created from My projects page.
Fix [#834]
> [#834] Create new project on projects page

- app/javascript/stylesheets/_bootstrap-customizations.scss
> offer select active state fix

- CHANGELOG.md
- app/javascript/packs/application.js
- app/javascript/packs/cookies_policy.js
- app/javascript/stylesheets/_bootstrap-customizations.scss
- app/javascript/stylesheets/application.scss
- app/views/layouts/_footer.html.haml
- package.json
- spec/support/cookies_policy.rb
- yarn.lock
Here we are adding cookies policies consent popup with a link to EOSC policies. 
TODOs:
Fixes #859
> Add cookie policies consent popup

- CHANGELOG.md
- app/controllers/projects_controller.rb
- app/views/project_items/_project_item.html.haml
- app/views/projects/_chat.html.haml
- app/views/projects/_details.html.haml
- app/views/projects/_details_box.html.haml
- app/views/projects/_empty_project.html.haml
- app/views/projects/_project.html.haml
- app/views/projects/_tabs.html.haml
- app/views/projects/new.html.haml
- app/views/projects/show.html.haml
- config/breadcrumbs/marketplace.rb
- config/locales/en.yml
- config/routes.rb
- spec/features/my_services_spec.rb
Added project details view https://kcjh3g.axshare.com/#g=1&p=view_empty_project_-_uj_class_1d
And toggled info box https://kcjh3g.axshare.com/#g=1&p=my-services-list
Affiliation will be removed so it has not been added. 
fix #840
> [#840] Add project details

- app/policies/backoffice/category_policy.rb
- app/policies/backoffice/offer_policy.rb
- app/policies/backoffice/platform_policy.rb
- app/policies/backoffice/provider_policy.rb
- app/policies/backoffice/research_area_policy.rb
- app/policies/backoffice/service_policy.rb
This commit contains check if user exist by checking the role
of user. It's necessary because ruby tries to call not existing
method fo a NilClass.
> Quickfix errors with roles check in the back-end

- CHANGELOG.md
- app/controllers/backoffice/services_controller.rb
- app/controllers/concerns/service/autocomplete.rb
- app/controllers/services_controller.rb
- app/javascript/controllers/order_controller.js
- app/views/backoffice/services/_search.html.haml
- app/views/services/_search.html.haml
- spec/features/service_spec.rb
Fixes #915 
Works like that:
1. Select a service in a search box
2. Be redirected straight to the service
> [#915] Autocomplete redirect

- app/controllers/projects_controller.rb
- app/policies/project_policy.rb
- app/services/project/destroy.rb
- app/services/project/update.rb
- app/views/projects/edit.html.haml
- app/views/projects/show.html.haml
- config/breadcrumbs/marketplace.rb
- config/locales/pundit.en.yml
- config/routes.rb
- spec/features/projects_spec.rb
- spec/policies/project_policy_spec.rb
Added possibility to edit and delete project from project details view
Fix #841
> [841] Edit and delete project

- CHANGELOG.md
- app/javascript/stylesheets/_header.scss
- app/javascript/stylesheets/_variables.scss
- app/views/services/_search.html.haml
- spec/features/service_spec.rb
Related to: https://github.com/cyfronet-fid/marketplace/issues/879
Implemented "Clear search" button
> [#879] Add "Clear search" functionality

- CHANGELOG.md
- app/controllers/projects_controller.rb
- app/javascript/controllers/project_item_controller.js
- app/policies/project_policy.rb
- app/views/projects/_details.html.haml
- app/views/projects/_form.html.haml
- app/views/services/configurations/show_normal.html.haml
- app/views/services/summaries/show_normal.html.haml
- db/migrate/20190614094402_add_additional_information_to_project.rb
- db/migrate/20190614094412_remove_additional_information_from_project_item.rb
- db/schema.rb
- spec/factories/project_items.rb
- spec/factories/projects.rb
- spec/features/order_spec.rb
- spec/features/projects_spec.rb
- spec/models/jira/client_spec.rb
Moved additional_information to project
Name-> Project name
Reason for access -> Reason to request access to the EOSC services
Fix #837
> [#837] Move additional_information to Project

- CHANGELOG.md
- app/controllers/projects_controller.rb
- app/views/projects/index.html.haml
- spec/features/my_services_spec.rb
Project filter was removed from the projects index view.
Fixes #930
> Remove project filter

- app/javascript/stylesheets/_bootstrap-customizations.scss
Fixes #942  - Added width 100% to card offer inner div
> [#942] card offer width fix

- CHANGELOG.md
- Gemfile.lock
- app/controllers/projects_controller.rb
- app/views/projects/_layout.html.haml
- db/schema.rb
- spec/features/projects_spec.rb
User is able to create project duplicate. All form elements are copied except the name.
Fixing #899
> Create new project basing on existing one

- CHANGELOG.md
- app/views/project_item_mailer/aod_voucher_accepted.html.haml
- app/views/project_item_mailer/aod_voucher_accepted.text.haml
- spec/mailers/project_item_spec.rb
Change content of mail template by voucher service order
Fixes #977
To check styling and content please create an order and then visit: 
https://marketplace-12.docker-fid.grid.cyf-kr.edu.pl/rails/mailers/project_item
> [#977] Change the email content for vouchers service

- app/controllers/projects_controller.rb
- app/views/projects/edit.html.haml
- app/views/projects/new.html.haml
- config/locales/en.yml
Add button labels to the locale file
Change close button label on project edit view
> [#973] Change close button labels

- CHANGELOG.md
- app/controllers/services/offers_controller.rb
Add reject condition to check if service offer is draft
Fixes #995
> [#995] Disable draft offers in the offers list in offers controller

- app/javascript/stylesheets/_bootstrap-customizations.scss
- app/javascript/stylesheets/_variables.scss
- app/views/projects/_project_layout.html.haml
> 1002 gui changes

- CHANGELOG.md
- app/controllers/project_items/conversations_controller.rb
- app/controllers/projects/items_controller.rb
- app/helpers/project_items_helper.rb
- app/javascript/stylesheets/_bootstrap-customizations.scss
- app/views/project_items/_attributes.html.haml
- app/views/project_items/_layout.html.haml
- app/views/project_items/conversations/show.html.haml
- app/views/project_items/show.html.haml
- app/views/projects/_layout.html.haml
- config/routes.rb
- spec/features/my_services_spec.rb
Similar structure like for project is used.
> Split project item into details and conversation

- CHANGELOG.md
- app/controllers/projects/adds_controller.rb
- app/controllers/services/cancels_controller.rb
- app/controllers/services/offers_controller.rb
- app/controllers/services/summaries_controller.rb
- app/views/projects/_empty_project.html.haml
- app/views/projects/services/index.html.haml
- config/routes.rb
- spec/features/add_item_to_project_spec.rb
> Auto select project when adding service from project view

- app/javascript/stylesheets/_bootstrap-customizations.scss
- app/views/projects/_customer_typology_fields.html.haml
input fields icons position fix (#981 )
star sign with no bottom dots (#990 )
> 981 990 input syles improvement

- CHANGELOG.md
- lib/jira/project_migrator.rb
- spec/lib/jira/project_migrator_spec.rb
* Now properly handle (ignore) orphaned project items
Closes: #1022
> [#1022] Fix JIRA project migrator

- lib/jira/project_migrator.rb
- spec/lib/jira/project_migrator_spec.rb
> [#1022] Handle JIRA unexpected errors and not initialized project items

- CHANGELOG.md
- app/javascript/stylesheets/_bootstrap-customizations.scss
- app/views/backoffice/services/_form.html.haml
Fix loading choices in owners field
Fix styles in the e-mails field
Fixes #956
> [#956] Change type of multiselect in the Owners field

- CHANGELOG.md
- app/controllers/projects_controller.rb
- app/services/project/create.rb
- spec/features/projects_spec.rb
Save logic was duplicated in controller and service. Now it is available only in the service.
> Move poject create logic from controller to service

- CHANGELOG.md
- app/controllers/projects/archives_controller.rb
> Fix archive project flash type typo

- CHANGELOG.md
- app/models/category.rb
- app/models/platform.rb
- app/models/provider.rb
- app/models/research_area.rb
- db/migrate/20190814112139_change_uniqueness_of_names_in_categories_providers_platforms_and_research_areas.rb
- db/schema.rb
- spec/models/category_spec.rb
- spec/models/platform_spec.rb
- spec/models/provider_spec.rb
- spec/models/research_area_spec.rb
Add uniqueness validation in models:
- provider
- research area
- category
- platform
Fixes #949
> [#949] Add names uniqueness validation in models

- CHANGELOG.md
- app/models/service.rb
- app/policies/backoffice/service_policy.rb
- app/views/backoffice/services/_form.html.haml
- app/views/services/_about.html.haml
- config/locales/simple_form.en.yml
- db/data.yml
- db/migrate/20190816143734_rename_corporate_sla_in_services.rb
- db/schema.rb
- db/seeds.rb
- lib/import/eic.rb
- lib/tasks/dev.rake
- spec/factories/services.rb
- spec/features/backoffice/services_spec.rb
- spec/lib/import/eic_spec.rb
Rename corporate_sla_url in Services table
> [#1040] Rename corporate_sla_url to sla_url

- CHANGELOG.md
- app/controllers/backoffice/services_controller.rb
- app/controllers/services_controller.rb
- app/views/backoffice/services/index.html.haml
- app/views/services/_order.html.haml
- app/views/services/index.html.haml
- spec/controllers/concerns/sortable_spec.rb
Add new service sort order in the backoffice
> [#951] Sort services in the backoffice by their status

- CHANGELOG.md
- app/views/backoffice/categories/index.html.haml
- app/views/backoffice/platforms/index.html.haml
- app/views/backoffice/providers/index.html.haml
- app/views/backoffice/research_areas/index.html.haml
- app/views/backoffice/services/index.html.haml
- app/views/backoffice/services/show.html.haml
- config/locales/en.yml
- spec/features/backoffice/categories_spec.rb
- spec/features/backoffice/platforms_spec.rb
- spec/features/backoffice/providers_spec.rb
- spec/features/backoffice/research_areas_spec.rb
- spec/features/backoffice/services_spec.rb
Rename button labels of creating new:
- categories
- platforms
- providers
Add button labels to the translation file
> [#955] Change names of buttons

- app/views/services/opinions/index.html.haml
#1050 - fix for logotype position on service page
> service logotype position fix

- app/javascript/controllers/home_page_controller.js
- app/javascript/packs/application.js
- app/views/home/_products.html.haml
Remove jQuery function for hide scrolling arrow on mobile devices
Move it to the home_page_controller.js
> Remove jQuery fade out

- CHANGELOG.md
- app/models/user.rb
- db/migrate/20190902135120_remove_uniqueness_from_user_email_index.rb
- db/schema.rb
- spec/models/user_spec.rb
> [#1063] Removed uniqueness constraint on user email

- CHANGELOG.md
- app/controllers/backoffice/services_controller.rb
- app/controllers/concerns/service/filterable.rb
- app/models/filter/upstream_source.rb
- app/models/service.rb
- spec/controllers/concerns/searchable_spec.rb
- spec/models/filter/upstream_source_spec.rb
Add a new filter showing services from external sources
> [#984] Filter via service source

- CHANGELOG.md
- app/javascript/stylesheets/_test.scss
- app/javascript/stylesheets/application.scss
- app/views/layouts/application.html.haml
- spec/features/service_spec.rb
Turn off all css animations in the test environment
> [#897] Disable animations in capybara tests

- CHANGELOG.md
- app/helpers/service_helper.rb
- app/views/home/_carousel-card.html.haml
- app/views/home/index.html.haml
- spec/features/home_spec.rb
> [#1112] Popular services fix

- CHANGELOG.md
- app/controllers/backoffice/services/logo_previews_controller.rb
- app/controllers/backoffice/services_controller.rb
- app/javascript/stylesheets/_preview.scss
- app/javascript/stylesheets/application.scss
- app/policies/backoffice/service_policy.rb
- app/views/backoffice/services/_form.html.haml
- app/views/backoffice/services/preview.html.haml
- app/views/services/_about.html.haml
- app/views/services/_header.html.haml
- app/views/services/_offers.html.haml
- app/views/services/_related.html.haml
- app/views/services/_tabs.haml
- app/views/services/show.html.haml
- config/breadcrumbs/backoffice.rb
- config/routes.rb
- spec/features/backoffice/services_spec.rb
Add preview of service in the marketplace view.
Fixes #1066
> Preview page for a service in the backoffice

- CHANGELOG.md
- app/javascript/controllers/multicheckbox_controller.js
- app/javascript/stylesheets/_bootstrap-customizations.scss
- app/models/filter/ancestry_multiselect.rb
- app/models/filter/multiselect.rb
- app/models/filter/platform.rb
- app/models/filter/provider.rb
- app/models/filter/research_area.rb
- app/views/services/filters/_multiselect.html.haml
- app/views/services/filters/_multiselect_level.html.haml
- package.json
- spec/features/filter_spec.rb
- spec/features/service_spec.rb
- yarn.lock
Fuzzy search is used to filter filter results. The final implementation will be valid for flat and hierarchical multiselect.
Fixes #1088
> Add possibility to filter filter records

- CHANGELOG.md
- app/javascript/controllers/filters_controller.js
- app/views/services/_filters.html.haml
- app/views/services/filters/_multiselect_level.html.haml
- app/views/services/filters/_select.html.haml
- spec/features/service_spec.rb
> Simple version of reload

- CHANGELOG.md
- db/migrate/20191001140915_set_project_creation_date_default.rb
- db/schema.rb
Set default project creation date
> Changed project creation time default

- .travis.yml
- app/javascript/controllers/service_controller.js
- lib/tasks/stimulus_test.rake
- package.json
- spec/javascript/service_spec.js
- spec/javascript/setup.js
- yarn.lock
Initial implementation of stimulus controllers testing with sample.
There is no official approach for stimulus controller test  yet. 
For now I choose  testing in Jest. I think is easy way for this problem. 
I based my choice on the article https://shime.sh/testing-stimulus
> 1046 stilulus tests

- CHANGELOG.md
- app/javascript/controllers/home_page_controller.js
Remove show logs with current window position in home page view
> Fix show logs in js console

- CHANGELOG.md
- config/database.yml
- db/migrate/20191003120324_fix_iid_incrementation.rb
- db/schema.rb
This is a mirror of https://github.com/cyfronet-fid/marketplace/pull/1137
It was created so it can be merged into `2.1.x` branch and released as `2.1.5` version
> [HOTFIX to release] Fix services iid for project

- CHANGELOG.md
- lib/import/eic.rb
- lib/tasks/import.rake
- spec/lib/import/eic_spec.rb
- spec/lib/tasks/import_spec.rb
* Add status to preserved attributes when updating service via import
* Fix bug when Provider name clashed and script failed
Closes: #1122
> [#1122] EIC Import default upstream

- CHANGELOG.md
- app/javascript/controllers/filter_controller.js
- app/javascript/controllers/filters_controller.js
- app/javascript/stylesheets/_bootstrap-customizations.scss
- app/views/services/_filters.html.haml
- app/views/services/filters/_multiselect_level.html.haml
- app/views/services/filters/_select.html.haml
- app/views/services/filters/_wrapper.html.haml
- spec/factories/research_areas.rb
- spec/features/filter_spec.rb
- spec/features/service_spec.rb
The state is stored inside the user cookie
References #1087.
> Store collapsed filter state

- CHANGELOG.md
- app/javascript/stylesheets/_bootstrap-customizations.scss
- app/models/filter.rb
- app/views/services/index.html.haml
- spec/models/filter/research_area_spec.rb
- spec/models/filter_spec.rb
Add filter title to the active filters view in services
Fixes #1126
> [#1126] Add labels to active filters

- CHANGELOG.md
- app/jobs/project/jira_update_job.rb
- app/models/jira/client.rb
- app/services/project/jira_update.rb
- app/services/project/update.rb
- app/views/projects/_form.html.haml
- app/views/projects/edit.html.haml
- spec/models/jira/client_spec.rb
- spec/services/project/jira_update.rb
> After project edit jira issue is updated

- CHANGELOG.md
- app/javascript/stylesheets/_bootstrap-customizations.scss
- app/javascript/stylesheets/_order.scss
- app/views/home/_products.html.haml
- app/views/layouts/order.html.haml
- app/views/projects/services/opinions/new.haml
- app/views/services/_filters.html.haml
- app/views/services/_header.html.haml
- app/views/services/_parameters.html.haml
- app/views/services/_service_box.html.haml
- app/views/services/index.html.haml
- app/views/services/offers/_offer.html.haml
added mods from this list: https://docs.google.com/spreadsheets/d/11tsLPoqmIe_lanDI8flnXNe4917F-rye_faFMy1g_u4/edit#gid=0
> 1091 poprawki ui

- CHANGELOG.md
- app/controllers/projects_controller.rb
- spec/features/projects_spec.rb
> Show first project services on "My projects"

- CHANGELOG.md
- README.md
- app/views/layouts/_navbar.html.haml
- app/views/layouts/_sections.html.haml
- config/application.rb
> Fixed EOSC Portal component titles at the top bar

- CHANGELOG.md
- lib/import/eic.rb
- spec/lib/import/eic_spec.rb
> Rescue Errno::EHOSTUNREACH

- spec/features/service_spec.rb
> Fix failed test that tests the sorting of services by rating

- CHANGELOG.md
- app/views/errors/internal_server_error.html.haml
Change content of message for unexpected error
Fixes #1178
> [#1178] Change message for internal server error

- CHANGELOG.md
- app/views/services/_header.html.haml
- app/views/services/_offer.html.haml
- config/locales/en.yml
- spec/features/order_spec.rb
- spec/features/service_spec.rb
Every service with offer has access button "Access the service" on service entry view.
> Unification access service button

- CHANGELOG.md
- app/mailers/webhook_jira_mailer.rb
- app/services/jira/comment_created.rb
- app/views/layouts/mailer.html.haml
- app/views/webhook_jira_mailer/project_new_message.html.haml
- app/views/webhook_jira_mailer/project_new_message.text.haml
- config/locales/en.yml
- spec/mailers/previews/webhook_jira_preview.rb
- spec/services/jira/comment_created_spec.rb
Eails content  project_new_message added.
You can see emails on page \<pr-link\>/rails/mailers/
Fix #1167
> Add project new comment mail content

- spec/features/order_spec.rb
- spec/services/project_item/create_spec.rb
- changed context in project_item/create_spec
- merged two tests were service order is tested into a loop
> Test improvements to pr [#1205]

- CHANGELOG.md
- app/controllers/services/information_controller.rb
- app/controllers/services/offers_controller.rb
- app/views/layouts/order/_nav.html.haml
- app/views/services/configurations/show.html.haml
- app/views/services/information/show.html.haml
- app/views/services/summaries/show_normal.html.haml
- app/views/services/summaries/show_open_access.html.haml
- config/locales/en.yml
- config/routes.rb
- spec/features/add_item_to_project_spec.rb
- spec/features/order_spec.rb
> Initial information step

- CHANGELOG.md
- app/controllers/services/summaries_controller.rb
- app/javascript/controllers/service_controller.js
- app/models/offer.rb
- app/models/project_item.rb
- app/models/service.rb
- app/services/project_item/create.rb
- app/services/project_item/ready.rb
- app/views/projects/services/_project_item.html.haml
- app/views/services/information/show.html.haml
- app/views/services/summaries/show_orderable.html.haml
- config/jira.yml
- config/locales/en.yml
- db/data.yml
- db/migrate/20191029141900_change_service_and_offer_type_values.rb
- db/seeds.rb
- spec/factories/services.rb
- spec/features/order_spec.rb
- spec/models/offer_spec.rb
- spec/models/service_spec.rb
- spec/services/project_item/create_spec.rb
Change service and offer types to:
- orderable (previously: normal)
- open_access (stay as it was)
- external (previously: catalog)
Fixes #1208
> [#1208] Change service and offer types values

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/custom_template.md
- .github/ISSUE_TEMPLATE/feature_request.md
Introduced automatic labeling for issues as stated in the github help:
https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
> Improved issue templates - default labels

- app/views/layouts/order.html.haml
Added some CSS classes to access wizard header that will take care logo dimmensions.
> 1232 - logo dimmensions

- CHANGELOG.md
- app/javascript/stylesheets/_bootstrap-customizations.scss
- app/views/services/_offer.html.haml
- app/views/services/offers/_offer.html.haml
- config/locales/en.yml
- spec/features/order_spec.rb
Add offer type to the offer selection view
Add offer type to the project item view in projects
Fixes #1220
> [#1220] Show the offer access type on the offer view

- .haml-lint.yml
- CHANGELOG.md
- Gemfile
- Gemfile.lock
- app/javascript/stylesheets/_bootstrap-customizations.scss
- app/views/layouts/_footer.html.haml
- app/views/pages/_help_card.html.haml
- app/views/pages/help.html.haml
- app/views/pages/help/_about.html.haml
- app/views/pages/help/_for_providers.html.haml
- app/views/pages/help/_ordering.html.haml
- app/views/pages/help/_payment.html.haml
- app/views/pages/help/_registration_and_settings.html.haml
- app/views/pages/help/_searching.html.haml
- app/views/pages/help/_services.html.haml
This is an initial version for the help webpage. I used the first 2 bullets from faq and included them as an example. Right now accordion, headers look ugly and this is a field to explore by @jarekzet. 
Fixes #1158
> Help section with example accordion

- CHANGELOG.md
- app/controllers/services/application_controller.rb
- app/controllers/services/configurations_controller.rb
- app/controllers/services/information_controller.rb
- app/controllers/services/summaries_controller.rb
- app/models/project_item/project_validation.rb
- app/models/project_item/wizard.rb
- app/views/layouts/order.html.haml
- app/views/layouts/order/_nav.html.haml
- app/views/services/_offer.html.haml
- app/views/services/configurations/show.html.haml
- app/views/services/information/show.html.haml
- app/views/services/offers/_offer.html.haml
- app/views/services/offers/show.html.haml
- app/views/services/summaries/show.html.haml
- config/locales/en.yml
- spec/features/order_spec.rb
Naming is improved according to #1216. What is more bug with going back when the step is not visible was fixed.
> Improve naming on all order wizard steps

- CHANGELOG.md
- app/controllers/services/summaries_controller.rb
- app/jobs/project_item/ready_job.rb
- app/jobs/project_item/register_job.rb
- app/models/project_item/wizard.rb
- app/services/project_item/create.rb
- app/services/project_item/ready.rb
- app/services/project_item/register.rb
- app/views/services/summaries/show.html.haml
- spec/jobs/project_item/ready_job_spec.rb
- spec/jobs/project_item/register_job_spec.rb
- spec/services/project_item/create_spec.rb
- spec/services/project_item/ready_spec.rb
- spec/services/project_item/register_spec.rb
> Add affitional comment input to summary step

- CHANGELOG.md
- app/views/home/_products.html.haml
> [#1242] Change greeting on the main page

- CHANGELOG.md
- app/helpers/service_helper.rb
- app/views/services/_categorization.html.haml
Fixes bug not apply the filter after click on research area
at a service pane
Fixes #1233
> [#1233] Research area link at a service pane apply a filter

- db/migrate/20191029141900_change_service_and_offer_type_values.rb
> Fix migration change_services_and_offer_type_value

- CHANGELOG.md
- app/javascript/stylesheets/_bootstrap-customizations.scss
- app/javascript/stylesheets/_order.scss
- app/views/layouts/order.html.haml
- app/views/services/configurations/_attributes.html.haml
- app/views/services/summaries/_project_browser.haml
- app/views/services/summaries/_technical_configuration.html.haml
- app/views/services/summaries/show.html.haml
- config/locales/en.yml
Some mods on checkout steps (steps list, content formatting) and RWD fixes.
> Checkout steps css/html mods

- CHANGELOG.md
- app/views/services/_offer.html.haml
- app/views/services/_parameters.html.haml
- app/views/services/offers/_offer.html.haml
- app/views/services/offers/_parameters.html.haml
> Hide technical parameters on offers view

- app/controllers/concerns/project_item/authorize.rb
- app/controllers/projects/services/conversations_controller.rb
- app/controllers/projects/services/timelines_controller.rb
- app/views/projects/services/_layout.html.haml
- app/views/projects/services/timelines/show.html.haml
- config/routes.rb
- spec/features/my_services_spec.rb
- spec/features/project_services_spec.rb
fix #1155 
Additionally labels text will be changed in pr to ticket #1140
> Split conversation and timeline on project service view

- app/views/services/summaries/show.html.haml
- config/locales/simple_form.en.yml
> Explain purpose of additional comment order field

- CHANGELOG.md
- app/views/pages/help/_about.html.haml
- app/views/pages/help/_services.html.haml
Remove duplicate of question in the services section
Remove duplicate of id in the about section
> Remove duplicates in the FAQ section

- CHANGELOG.md
- db/data.yml
- lib/tasks/dev.rake
dev:prime was not updated during the migrations
this commit removes unused fields and adds new added in migrations
> Fix dev:prime task

- app/mailers/project_item_mailer.rb
- app/services/jira/issue_updated.rb
- app/services/project_item/create.rb
- app/services/project_item/ready.rb
- app/services/project_item/register.rb
- app/views/layouts/mailer.html.haml
- app/views/layouts/mailer.text.haml
- app/views/project_item_mailer/added_to_project.html.haml
- app/views/project_item_mailer/added_to_project.text.haml
- app/views/project_item_mailer/approved.html.haml
- app/views/project_item_mailer/approved.text.haml
- app/views/project_item_mailer/changed.html.haml
- app/views/project_item_mailer/changed.text.haml
- app/views/project_item_mailer/closed.html.haml
- app/views/project_item_mailer/closed.text.haml
- app/views/project_item_mailer/created.html.haml
- app/views/project_item_mailer/created.text.haml
- app/views/project_item_mailer/rating_service.html.haml
- app/views/project_item_mailer/ready_to_use.html.haml
- app/views/project_item_mailer/ready_to_use.text.haml
- app/views/project_item_mailer/rejected.html.haml
- app/views/project_item_mailer/rejected.text.haml
- app/views/project_item_mailer/waiting_for_response.html.haml
- app/views/project_item_mailer/waiting_for_response.text.haml
- spec/mailers/previews/project_item_preview.rb
- spec/mailers/project_item_spec.rb
- spec/services/project_item/create_spec.rb
- spec/services/project_item/ready_spec.rb
- spec/services/project_item/register_spec.rb
New e-mails templates specific for the project item status
Fixes #1138
> [#1138] Change e-mails content

- CHANGELOG.md
- db/migrate/20191205113156_remove_description_index_from_service.rb
- db/schema.rb
> Remove service description index from DB

- CHANGELOG.md
- app/controllers/backoffice/services_controller.rb
- app/controllers/services/offers_controller.rb
- app/controllers/services_controller.rb
- app/views/backoffice/services/offers/_offers.html.haml
- app/views/backoffice/services/show.html.haml
> Sort offers by creation date

- CHANGELOG.md
- app/views/projects/services/_rating.html.haml
- app/views/projects/services/opinions/new.haml
- config/locales/en.yml
- spec/features/my_services_spec.rb
Rating questions are now depending on an offer type
Fixes #1136
> [#1136] Customize rating questions

- CHANGELOG.md
- app/controllers/projects/services/timelines_controller.rb
- app/helpers/project_items_helper.rb
- app/mailers/project_item_mailer.rb
- app/models/project_item.rb
- app/policies/project_item_policy.rb
- app/services/jira/issue_updated.rb
- app/services/project_item/create.rb
- app/services/project_item/ready.rb
- app/services/project_item/register.rb
- app/views/messages/_message.html.haml
- app/views/messages/_messages.html.haml
- app/views/project_item_mailer/activate_message.html.haml
- app/views/project_item_mailer/activate_message.text.haml
- app/views/projects/services/timelines/show.html.haml
- app/views/statuses/_status.html.haml
- app/views/statuses/_statuses.html.haml
- config/locales/en.yml
- db/migrate/20191128084224_remove_message_from_status.rb
- db/schema.rb
- spec/features/my_services_spec.rb
- spec/helpers/project_items_helper_spec.rb
- spec/mailers/project_item_spec.rb
- spec/models/project_item_spec.rb
- spec/services/jira/issue_updated_spec.rb
- spec/services/project_item/ready_spec.rb
- spec/services/project_item/register_spec.rb
> Change messages on timeline and conversation view

- CHANGELOG.md
- app/views/pages/help/_services.html.haml
> FAQ section content fixes

- CHANGELOG.md
- app/views/attributes/_index.html.haml
- app/views/services/configurations/_attributes.html.haml
- app/views/services/offers/_parameters.html.haml
- config/locales/en.yml
- spec/features/order_spec.rb
- spec/features/service_spec.rb
Change "technical parameters" label to "parameters"
Fixes #1293
> [#1293] Change "technical parameters" label

- CHANGELOG.md
- app/models/research_area.rb
- app/views/backoffice/services/_form.html.haml
in the backoffice service view added parent's name in research area
> 1089 children research areas view

- CHANGELOG.md
- app/views/projects/services/_details.html.haml
- app/views/projects/services/_layout.html.haml
- app/views/projects/services/conversations/show.html.haml
- config/locales/en.yml
- spec/features/project_services_spec.rb
Change information in the ordered/added to project service in the project item view.
Fixes #1141
> [#1141] change information in service details

- app/javascript/stylesheets/_bootstrap-customizations.scss
- app/views/projects/_project_layout.html.haml
- app/views/projects/services/_details.html.haml
- app/views/projects/services/_layout.html.haml
- app/views/projects/services/_project_item.html.haml
- app/views/statuses/_status.html.haml
- config/locales/en.yml
Status Registered has been changed to New because it will no longer be displayed
fix #1139
> Change displayed project_item status info

- app/javascript/stylesheets/_bootstrap-customizations.scss
- app/views/messages/_messages.html.haml
- app/views/projects/services/conversations/show.html.haml
> service order conversation tab

- CHANGELOG.md
- app/helpers/project_items_helper.rb
Add tooltips in the project view for project items status dot
Fixes #1235
> [#1235] Add tooltip in the project item status dot

- CHANGELOG.md
- app/models/concerns/offerable.rb
- app/models/jira/client.rb
- app/models/offer.rb
- app/models/project_item.rb
- app/views/projects/services/_details.html.haml
- app/views/projects/services/_layout.html.haml
- app/views/projects/services/opinions/new.haml
- db/migrate/20191216141227_add_offer_fields_to_project_item.rb
- db/schema.rb
- spec/features/project_services_spec.rb
> Project item Independence Day

- CHANGELOG.md
- app/views/projects/services/_details.html.haml
- config/locales/en.yml
> Fixed label Order date

- CHANGELOG.md
- app/views/backoffice/services/_service.html.haml
- app/views/backoffice/services/index.html.haml
- app/views/services/_active_filters.html.haml
- app/views/services/_index.html.haml
- app/views/services/_pagination.html.haml
- app/views/services/_service.html.haml
- app/views/services/_service_details.html.haml
- app/views/services/index.html.haml
- config/brakeman.ignore
This PR contains views refactoring and reuses them in the backoffice context.
It makes non-visible changes in services search view, but changes views in the backoffice services view and makes search more similar and consistent with main mp layout.
> Services search view refactoring

- CHANGELOG.md
- app/views/webhook_jira_mailer/project_item_new_message.html.haml
- app/views/webhook_jira_mailer/project_item_new_message.text.haml
- app/views/webhook_jira_mailer/project_new_message.text.haml
- spec/mailers/previews/webhook_jira_preview.rb
Fixed displaying links in conversation mails and emails preview.
> Fix text mails

- README.md
- config/application.rb
New env variable:
CUSTOM_VIEWS_PATH="app/views/custom"  for custom views 
In the folder app/view/custom, add the files you want to overwrite in the same structure as they are in app/view/
> Overriding views

- CHANGELOG.md
- config/application.rb
Add custom path for the i18n locale files
> [#1374] i18n customization

- CHANGELOG.md
- app/javascript/app/index.js
- app/javascript/app/nav.js
- app/javascript/stylesheets/_header.scss
> Fix show nav on small devices

- CHANGELOG.md
- app/views/projects/_project_layout.html.haml
- spec/features/projects_spec.rb
Fix displaying project status after project archivisation
Fix #1393
> Fix displaying project status after project archivisation

- CHANGELOG.md
- app/javascript/stylesheets/_bootstrap-customizations.scss
- app/views/services/offers/_offer.html.haml
- config/locales/views/services/en.yml
Change text content by offer selection from
'Select an offer' to 'Selected offer'
Fixes #1316
> [#1316] Enhancement of the offer selection

- CHANGELOG.md
- app/views/leads/learn_more/_card.html.haml
- app/views/leads/use_case/_card.html.haml
- config/locales/simple_form.en.yml
Trucate long descriptions in leads
Add hints with preferred length of inputs
Add tooltips for long descriptions in leads
> Lead sections improvements

- CHANGELOG.md
- app/views/backoffice/services/show.html.haml
- config/locales/views/backoffice/en.yml
- spec/features/backoffice/services_spec.rb
Fix "Add new Offer" label
Move other labels to the i18n locales
> Fix labels in the backoffice service view

- CHANGELOG.md
- app/javascript/app/controllers/scroller_controller.js
- app/views/messages/_messages.html.haml
- app/views/statuses/_statuses.html.haml
Reverse order of project and services statuses
Scroll always to the last message in messages
Fixes #1372
> [#1372] Fix displaying messages and statuses in projects

- CHANGELOG.md
- app/controllers/backoffice/services_controller.rb
- app/controllers/concerns/service/searchable.rb
- app/controllers/services_controller.rb
- app/helpers/service_helper.rb
- app/javascript/stylesheets/_bootstrap-customizations.scss
- app/models/service.rb
- app/views/backoffice/services/_service.html.haml
- app/views/backoffice/services/index.html.haml
- app/views/services/_index.html.haml
- app/views/services/_offers_box.html.haml
- app/views/services/_service.html.haml
- app/views/services/_service_details.html.haml
- app/views/services/index.html.haml
- spec/controllers/concerns/searchable_spec.rb
- spec/features/backoffice/services_spec.rb
- spec/lib/import/eic_spec.rb
- spec/services/service/draft_spec.rb
Added offers to main search, 
Offers are listed in service box 
Fix #1387
> Search by offers

- app/helpers/backoffice/parameters_helper.rb
- app/javascript/app/controllers/offer_controller.js
- app/javascript/stylesheets/_bootstrap-customizations.scss
- app/views/backoffice/services/offers/_form.html.haml
attributes form tyles 
prevs: https://github.com/cyfronet-fid/marketplace/issues/1430
> Attributes form styles

- CHANGELOG.md
- app/models/service.rb
- app/policies/backoffice/service_policy.rb
- app/views/backoffice/services/_form.html.haml
- app/views/backoffice/services/show.html.haml
- app/views/services/sidebar/_date.html.haml
- app/views/services/sidebar/_plain_text.html.haml
- db/migrate/20200312144537_add_version_to_services.rb
- db/schema.rb
- lib/import/eic.rb
- spec/factories/services.rb
- spec/features/backoffice/services_spec.rb
- spec/lib/import/eic_spec.rb
- spec/policies/backoffice/service_policy_spec.rb
Added import of version from eic. and displaying updatet_at as "last update" 
Fix #1403
> Added version to import eic and display last update date

- CHANGELOG.md
- config/locales/views/services/en.yml
> Changed orderable services description to more accurate

- CHANGELOG.md
- app/controllers/backoffice/services_controller.rb
- app/controllers/comparisons/services_controller.rb
- app/controllers/comparisons_controller.rb
- app/controllers/concerns/service/comparison.rb
- app/controllers/services/opinions_controller.rb
- app/controllers/services_controller.rb
- app/helpers/application_helper.rb
- app/helpers/comparisons_helper.rb
- app/javascript/app/controllers/comparison_controller.js
- app/javascript/stylesheets/_base.scss
- app/javascript/stylesheets/_bootstrap-customizations.scss
- app/views/backoffice/services/index.html.haml
- app/views/comparisons/_bar.html.haml
- app/views/comparisons/_service.html.haml
- app/views/comparisons/show.html.haml
- app/views/layouts/show_bottombar.js.erb
- app/views/services/_header.html.haml
- app/views/services/_index.html.haml
- app/views/services/_service.html.haml
- app/views/services/_service_details.html.haml
- app/views/services/index.html.haml
- app/views/services/opinions/index.html.haml
- app/views/services/show.html.haml
- config/breadcrumbs/marketplace.rb
- config/routes.rb
- spec/features/comparison_spec.rb
Add controller for comparison handling
> [#1404] Add services comparison

- CHANGELOG.md
- lib/import/eic.rb
Add necessary assignment operators in rescue
> Fix eIC error handling

- CHANGELOG.md
- app/javascript/app/controllers/offer_controller.js
- app/javascript/stylesheets/_bootstrap-customizations.scss
> Fix offer parameter moving up and down

- app/views/pages/about_projects.html.haml
- config/locales/views/projects/en.yml
Update information in about projects page
Fixes #1453
> [#1453] Fix about projects page

- CHANGELOG.md
- app/javascript/stylesheets/_ref_designsystem.scss
- app/views/layouts/_navbar.html.haml
- app/views/layouts/_sections.html.haml
- config/application.rb
Add necessary links and unify the font
Fixes #1452
> [#1452] Fix the top menu links in Portal

- CHANGELOG.md
- app/inputs/date_time_picker_input.rb
- app/javascript/stylesheets/_bootstrap-customizations.scss
- app/javascript/stylesheets/_order.scss
- app/views/services/configurations/attributes/_date.html.haml
Add styling for the datepicker including width, font size,
active and old and new month styling
Fixes #1480
> [#1480] Datepicker styling

- CHANGELOG.md
- app/javascript/stylesheets/_base.scss
> report technical problem button css mods

- CHANGELOG.md
- app/views/services/configurations/attributes/_attribute.html.haml
- app/views/services/configurations/attributes/_date.html.haml
- app/views/services/configurations/attributes/_input.html.haml
- app/views/services/configurations/attributes/_multiselect.html.haml
- app/views/services/configurations/attributes/_quantity_price.html.haml
- app/views/services/configurations/attributes/_range.html.haml
- app/views/services/configurations/attributes/_select.html.haml
- spec/features/order_spec.rb
Disable correct validation of empty parameters by ordering form
Fixes #1181
> [#1181] Display empty parameters as not validated

- CHANGELOG.md
- app/controllers/projects_controller.rb
- app/controllers/services/summaries_controller.rb
- app/views/projects/_form.html.haml
- app/views/projects/edit.html.haml
- app/views/projects/new.html.haml
- app/views/services/summaries/show.html.haml
Add recaptcha to project form
Add recaptcha to summary view
> Add recaptcha to project creating and service ordering

- CHANGELOG.md
- app/controllers/services_controller.rb
- app/models/google/analytics.rb
- app/models/service.rb
- app/services/analytics/page_views_and_redirects.rb
- app/services/analytics/total_services_views.rb
- app/views/services/_about.html.haml
- db/migrate/20200518084242_add_popularity_ratio_to_service.rb
- db/schema.rb
- docs/upgrade/2.11.0.md
- lib/tasks/update_popularity_ratio.rake
Refactoring of GA client
Add popularity_ratio to the service updated once a day
Fixes #1494
> [#1494] Popular services fix

- CHANGELOG.md
- app/controllers/projects_controller.rb
- app/controllers/services/summaries_controller.rb
- app/models/project.rb
- app/models/project_item/wizard.rb
- app/views/projects/_form.html.haml
- app/views/services/summaries/show.html.haml
- spec/models/project_spec.rb
Added email validation, project field length checking and recaptcha error display.
> Added length validation form project fields

- CHANGELOG.md
- app/views/layouts/_footer.html.haml
Fix links to categories in services & resources section
> [#1518] Fix broken links in the footer

- CHANGELOG.md
- app/javascript/app/badge.js
- app/javascript/app/index.js
- app/javascript/stylesheets/_ref_designsystem.scss
- app/javascript/stylesheets/_variables.scss
- app/views/layouts/_badge.html.haml
- app/views/layouts/application.html.haml
- config/locales/views.yml
- docs/upgrade/2.10.3.md
By setting `MP_INSTANCE` environmental variable
with proper value badge should be visible.
Values for `MP_INSTANCE` variable:
- `pr` for pr instances
- `master` for master instance
- `staging` for staging instance
It's important to not set `MP_INSTANCE` on production
> [#1506] Instance badges

- CHANGELOG.md
- app/controllers/home_controller.rb
- app/helpers/application_helper.rb
- app/views/layouts/_head.html.haml
- config/environments/development.rb
- config/environments/production.rb
- config/robots.development.txt
- config/robots.production.txt
- config/routes.rb
- public/robots.txt
Add controller for managing robots.txt file
depending on instance
Add meta tags for robots
Fixes #1517
> [#1517] Manage search robots

- CHANGELOG.md
- app/views/errors/internal_server_error.html.haml
- app/views/errors/not_found.html.haml
- app/views/errors/unprocessable.html.haml
- app/views/layouts/admin.html.haml
- app/views/layouts/backoffice.html.haml
- app/views/layouts/executive.html.haml
- app/views/layouts/order.html.haml
- config/locales/views.yml
- config/locales/views/backoffice/en.yml
Add displaying bagdes in backoffice, admin and executive layouts.
> Instance badge display fix

- CHANGELOG.md
- app/mailers/service_mailer.rb
- app/services/service/mailer/send_to_subscribers.rb
- app/services/service/publish.rb
- app/views/layouts/mailer.html.haml
- app/views/service_mailer/new_question.html.haml
- app/views/service_mailer/new_service.html.haml
- app/views/service_mailer/new_service.text.haml
- spec/factories/users.rb
- spec/mailers/previews/service_preview.rb
- spec/mailers/service_spec.rb
- spec/services/service/publish_spec.rb
Add email notification for subscribers
in categories and research areas
Fixes #1498
> [#1498] email for subscribers

- app/services/service/pc_create_or_update.rb
Save the first provider if message contains a providers list
> Save first provider from list from EIC message

- CHANGELOG.md
- app/javascript/stylesheets/_bootstrap-customizations.scss
- app/views/messages/_messages.html.haml
- app/views/projects/conversations/show.html.haml
- app/views/projects/services/conversations/show.html.haml
Contact tab layout mods according to #1448
> contact tab improvements

- bin/jms-subscriber
- config/stomp.yml
- lib/tasks/import.rake
Changed default import url for providers.
> Change default for jms import url

- CHANGELOG.md
- app/views/errors/internal_server_error.html.haml
- app/views/errors/not_found.html.haml
- app/views/errors/unprocessable.html.haml
- app/views/layouts/admin.html.haml
- app/views/layouts/backoffice.html.haml
- app/views/layouts/executive.html.haml
- app/views/layouts/order.html.haml
- config/locales/views.yml
- config/locales/views/backoffice/en.yml
Add displaying badge in different layouts:
- backoffice
- admin
- executive
Add missing title translations
> Add displaying instance badge in the different layouts

- CHANGELOG.md
- app/javascript/stylesheets/_bootstrap-customizations.scss
- app/views/messages/_messages.html.haml
- app/views/projects/conversations/show.html.haml
- app/views/projects/services/conversations/show.html.haml
contact tab improvements
contact provider form mods
changelog update
> Improve project conversation view

- CHANGELOG.md
- app/models/service.rb
- app/policies/backoffice/service_policy.rb
- app/services/service/pc_create_or_update.rb
- app/views/backoffice/services/_form.html.haml
- app/views/comparisons/show.html.haml
- db/data.yml
- db/migrate/20200612095339_change_languages_type_to_array.rb
- db/migrate/20200615120733_change_languages_to_language_availability.rb
- db/schema.rb
- docs/upgrade/2.12.0.md
- lib/import/eic.rb
- lib/tasks/dev.rake
- lib/tasks/rdt.rake
- spec/factories/eic_services_response.rb
- spec/factories/services.rb
- spec/features/backoffice/services_spec.rb
- spec/fixtures/files/eic_import_output.json
- spec/lib/import/eic_spec.rb
- spec/policies/backoffice/service_policy_spec.rb
- spec/services/service/pc_create_or_update_spec.rb
Change field `languages`:
- type from `string` to `string[ ]`
- name `languages` to `language_availability`
Fixes #1544
> [#1544] change languages to language availability

- app/models/funding_body.rb
- app/models/funding_program.rb
- app/models/service.rb
- app/models/service_vocabulary.rb
- app/models/vocabulary.rb
- app/policies/backoffice/service_policy.rb
- app/services/service/pc_create_or_update.rb
- app/views/backoffice/services/_form.html.haml
- app/views/backoffice/services/show.html.haml
- db/data.yml
- db/migrate/20200619150640_create_vocabulary.rb
- db/migrate/20200619153511_create_service_vocabulary.rb
- db/schema.rb
- db/seeds.rb
- db/vocabulary.yml
- docs/upgrade/2.12.0.md
- lib/import/eic.rb
- lib/tasks/dev.rake
- lib/tasks/rdt.rake
- spec/factories/funding_bodies.rb
- spec/factories/funding_programs.rb
- spec/factories/jms_service.rb
- spec/features/backoffice/services_spec.rb
- spec/models/funding_body_spec.rb
- spec/models/funding_program_spec.rb
- spec/models/service_spec.rb
- spec/policies/backoffice/service_policy_spec.rb
- spec/services/service/pc_create_or_update_spec.rb
Add new associations mentioned as API vocabularies:
- FundingBody
- FundingProgram
Fixes #1559
> [#1559] New associations in service

- db/migrate/20200703124752_remove_phase_from_service.rb
- lib/tasks/rdt.rake
Fixed migration witch destroys deployment
> Fixed migration with phase deletion

- CHANGELOG.md
- app/controllers/concerns/service/autocomplete.rb
- app/controllers/services_controller.rb
- app/models/offer.rb
- app/views/services/_offers_box.html.haml
- app/views/services/autocomplete/_offer_item.html.haml
- app/views/services/autocomplete/_service_item.html.haml
- app/views/services/autocomplete/list.html.haml
Fixed displaying services in autocomplete. Additionally fixed service fort by name
> Fix autocomplete displaying

- CHANGELOG.md
- app/models/service.rb
- app/views/services/sidebar/_array.html.haml
Add nested option for a specific field
#1546
> Fix languages and geographical_availabilities

- app/controllers/backoffice/services_controller.rb
Forgotten backoffice name service sorting fixes
> Fixed service sorting by name in backoffice

- CHANGELOG.md
- app/controllers/services/application_controller.rb
- app/views/layouts/order.html.haml
Remove offer title if there's just one offer
Fixes #1572
> [#1572] Remove tagline and offer title in ordering form

- CHANGELOG.md
- config/locales/views/services/en.yml
Change content for information page in service ordering form
Fixes #1573
> [#1573] Change information page content

- CHANGELOG.md
- app/javascript/app/index.js
- app/javascript/stylesheets/_ref_designsystem.scss
- app/javascript/stylesheets/application.scss
- app/views/layouts/_sections.html.haml
- package.json
- yarn.lock
Add links to EOSC Portal twitter and youtube.
Fixes #1575
> [#1575] include social media in marketplace

- CHANGELOG.md
- app/controllers/backoffice/services_controller.rb
- app/views/backoffice/services/preview.html.haml
Fixed service preview by add to backoffice controller
missing analytics variable
Fixes #1557
> [#1557] Fix service preview

- CHANGELOG.md
- app/views/helps/show.html.haml
- app/views/pages/about.html.haml
- app/views/pages/communities.html.haml
- app/views/pages/providers.html.haml
- config/breadcrumbs/marketplace.rb
- config/locales/views/pages/en.yml
Add missing breadcrumbs and titles for:
- help
- communities
- providers
- about
Fixes #1563
> [#1563] Add missing breadcrumbs and titles

- CHANGELOG.md
- app/controllers/concerns/service/searchable.rb
How to test:
1. search e.g.: "gpu" 
2. choose in case "gpu" category compute
> Fix displaying offers mached to query

- app/views/comparisons/show.html.haml
Change field name in comparison view
> Change field name from access type to order type

- CHANGELOG.md
- app/controllers/admin/features_controller.rb
- app/controllers/home_controller.rb
- app/views/admin/features/show.html.haml
- app/views/home/index.html.haml
- app/views/layouts/admin/_navbar.html.haml
- config/routes.rb
- db/migrate/20200717142450_add_welcome_popup_to_user.rb
- db/schema.rb
- spec/factories/users.rb
- spec/features/home_spec.rb
Showing welcome popup depends on user db variable now.
Changed from cookies variable
Fixes #1561
> [#1561] Improve welcome popup

- CHANGELOG.md
- app/javascript/stylesheets/_bootstrap-customizations.scss
- app/views/home/index.html.haml
- app/views/layouts/application.html.haml
This is a fix for an issue on homepage on windows, where main tabs were not clickable.
> fix for home page on windows

- CHANGELOG.md
- app/javascript/app/index.js
- app/javascript/stylesheets/_ref_designsystem.scss
- app/javascript/stylesheets/application.scss
- app/views/layouts/_sections.html.haml
- package.json
- yarn.lock
Include links to twitter and youtube of EOSC Portal
social links css mods
social links left panel
Remove links from top navbar
Add email to social media section
> [#1575] Include social media links in the top navbar

- app/services/service/pc_create_or_update.rb
all providers are saving via jms
> Saving all providers

- app/services/service/pc_create_or_update.rb
- lib/import/eic.rb
- spec/factories/jms_service.rb
- spec/services/service/pc_create_or_update_spec.rb
* Respect upstream in JMS subscription
* Fix JMS import error (out of date API expectation)
* Add new mapped fields to import task
Closes: #1638, #1639, #1637
> [#1638, #1639, #1637] EIC integration fixes

- CHANGELOG.md
- app/models/service.rb
- app/views/services/details/_array.html.haml
- lib/import/eic.rb
* Language concatenation
* Date styling
* Change Multimedia to Marketing in header
* UPCASE languages in rest importer
> [HOTFIX] Service Details

- app/javascript/stylesheets/_bootstrap-customizations.scss
- app/views/services/_categorization.html.haml
- app/views/services/_header.html.haml
- app/views/services/sidebar/_classification.html.haml
> 1643 new service page improvement

- app/javascript/stylesheets/_bootstrap-customizations.scss
- app/views/projects/_project_layout.html.haml
Some CSS mods according to #1650
> Fix broken views on the Project page

- CHANGELOG.md
- app/models/service.rb
- app/views/services/_about.html.haml
- app/views/services/sidebar/_array.html.haml
- config/locales/simple_form.en.yml
- config/locales/views/services/en.yml
Fix `translation missing` tooltip in service sidebar titles
Fix `translation missing` tooltip in service details view
> Fix displaying categories in the sidebar as tree

- CHANGELOG.md
- bin/jms-subscriber
- config/stomp.yml
- lib/jms/subscriber.rb
- spec/lib/jms/subscriber_spec.rb
Set `MP_STOMP_SSL` to `true` for ssl secured connection
> Allow to ssl connection in jms

- CHANGELOG.md
- app/policies/backoffice/service_policy.rb
- app/views/backoffice/services/_form.html.haml
- app/views/backoffice/services/_public_contact_fields.html.haml
- spec/policies/backoffice/service_policy_spec.rb
Add phone input in the forms in front
> Add missing phone in contact forms

- CHANGELOG.md
- app/helpers/backoffice/services_helper.rb
- app/javascript/stylesheets/_base.scss
- app/javascript/stylesheets/_variables.scss
- app/views/backoffice/services/_form.html.haml
- spec/features/backoffice/services_spec.rb
Sort resource form similar to the PC component
> Sort resource form fields in the backoffice

- app/services/service/pc_create_or_update.rb
- bin/jms-subscriber
- lib/import/eic.rb
- spec/lib/import/eic_spec.rb
- spec/services/service/pc_create_or_update_spec.rb
Removed /api/ from the address - this will be moved to the ENV variable
> Update API url baseline

- CHANGELOG.md
- app/controllers/concerns/service/searchable.rb
- app/services/service/create.rb
- spec/factories/services.rb
- spec/features/backoffice/services_spec.rb
- spec/features/comparison_spec.rb
- spec/lib/import/eic_spec.rb
- spec/services/service/create_spec.rb
- spec/services/service/pc_create_or_update_spec.rb
- spec/services/service/update_spec.rb
Add missing tests for: 
- comparison view
- creating and updating default offers for the resource
> Add missing tests

- CHANGELOG.md
- app/helpers/service_helper.rb
- app/views/services/_header.html.haml
- app/views/services/_service_box.html.haml
- app/views/services/_service_details.html.haml
> [#542] Default logo for resource if no one attached

- CHANGELOG.md
- README.md
- app/javascript/stylesheets/_jira_collector.scss
- app/javascript/stylesheets/application.scss
- app/views/layouts/_jira_collector.html.haml
- app/views/layouts/application.html.haml
* JIRA collector integration
Closes #1677
> [#1677] JIRA collector integration

- app/views/layouts/tours/_modal_content.html.haml
- config/tours/details/index.en.yml
- config/tours/profiles/edit.en.yml
- config/tours/services/show.en.yml
Some fixes in the description of the steps
> Tour guides content improvements

- CHANGELOG.md
- app/controllers/api/services_controller.rb
Try to get {root_adress}/api/services and check if api responds and emails are visible
> Fix services api

- CHANGELOG.md
- app/javascript/stylesheets/_bootstrap-customizations.scss
- app/views/backoffice/categories/_form.html.haml
- app/views/backoffice/categories/edit.html.haml
- app/views/backoffice/categories/index.html.haml
- app/views/backoffice/categories/show.html.haml
- app/views/backoffice/platforms/_form.html.haml
- app/views/backoffice/platforms/edit.html.haml
- app/views/backoffice/platforms/index.html.haml
- app/views/backoffice/platforms/show.html.haml
- app/views/backoffice/providers/_form.html.haml
- app/views/backoffice/providers/edit.html.haml
- app/views/backoffice/providers/index.html.haml
- app/views/backoffice/providers/show.html.haml
- app/views/backoffice/scientific_domains/_form.html.haml
- app/views/backoffice/scientific_domains/edit.html.haml
- app/views/backoffice/scientific_domains/index.html.haml
- app/views/backoffice/scientific_domains/show.html.haml
- app/views/backoffices/show.html.haml
a lot of modifications in all backoffice views - start page , list views, edit forms etc.
> 950 improve front in backoffice

- CHANGELOG.md
- app/controllers/home_controller.rb
Add unverified and published resources to popular resources query
> Fix popular resources

- CHANGELOG.md
- app/controllers/application_controller.rb
- app/controllers/projects/services_controller.rb
- app/helpers/tour_helper.rb
- app/views/layouts/_tour.erb
Check behavior in master: 
1. clear cookies, 
2. go to My projects 
3. get any ProjectItem.
You should see welcome modal for details tour
then make the same steps on this instance - modal should't be visible
> Disable tour in ProjectItem details page

- CHANGELOG.md
- app/helpers/forms_helper.rb
- app/inputs/array_input.rb
- app/javascript/app/controllers/service_controller.js
- app/models/service.rb
- app/views/backoffice/services/_array_field.html.haml
- app/views/backoffice/services/_form.html.haml
- config/locales/simple_form.en.yml
Commit to fixes branch, copy of PR #1675 
Also
Fixes #1690
> Add `remove array element` in forms

- README.md
> Add aditional information to readme

- CHANGELOG.md
- app/helpers/backoffice/parameters_helper.rb
- app/views/backoffice/services/offers/_form.html.haml
- app/views/backoffice/services/offers/_one_offer_edit_form.html.haml
- app/views/parameters/_template.html.haml
- db/schema.rb
- spec/features/backoffice/services_spec.rb
Fix removing parameters from default offer
Fixes #1722
> [#1722] Fix parameters updates in default offer

- CHANGELOG.md
- spec/features/filter_spec.rb
Fix test with filter storing by breadcrumbs navigation
> [HOTFIX] Fix filter test

- CHANGELOG.md
- app/models/filter/location.rb
- app/models/service/search.rb
- spec/controllers/concerns/searchable_spec.rb
- spec/features/filter_spec.rb
- spec/models/filter/location_rspec.rb
- change to use geographical_availabilities
- fix filter
Closes #1711 .
> [#1711] Fix filtering by country

- CHANGELOG.md
- app/helpers/service_helper.rb
- app/views/services/details/_array.html.haml
- spec/features/service_spec.rb
- spec/helpers/service_helper_spec.rb
- change trl field to upcase on service details view
- add tooltip to the field with description
Closes #1717
> [#1717] Trl field improvement

- CHANGELOG.md
- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/controllers/backoffice/platforms_controller.rb
- app/controllers/backoffice/providers_controller.rb
- app/controllers/backoffice/services_controller.rb
- app/controllers/services_controller.rb
- app/helpers/application_helper.rb
- app/views/backoffice/platforms/index.html.haml
- app/views/backoffice/providers/index.html.haml
- app/views/backoffice/services/index.html.haml
- app/views/services/_index.html.haml
- app/views/services/_paginate.haml
- app/views/services/_pagination.html.haml
- app/views/services/index.html.haml
- config/initializers/pagy.rb
- config/locales/en.yml
Pagy implemented in services view
and platforms, providers and services in backoffice layout
Fixes #1754
> [#1754] Replace will_paginate with pagy gem

- app/views/services/_offer.html.haml
> offer card equal height

- CHANGELOG.md
- README.md
- app/serializers/recommender/service_serializer.rb
- app/serializers/recommender/user_serializer.rb
- lib/recommender/serialize_db.rb
- lib/tasks/recommender.rake
- spec/lib/recommender/serialize_db_spec.rb
- spec/serializers/recommender/service_serializer_spec.rb
- spec/serializers/recommender/user_serializer_spec_spec.rb
> [#1758] DB recommender serializer

- CHANGELOG.md
> Changelog stylistic changes

- CHANGELOG.md
- app/helpers/provider_helper.rb
- app/helpers/service_helper.rb
- app/javascript/app/controllers/map_controller.js
- app/javascript/stylesheets/_bootstrap-customizations.scss
- app/models/country.rb
- app/views/providers/_coverage.html.haml
- spec/models/usage_report_spec.rb
- used in provider and resource views
- fixed map view for UK and EL (Greece)
Resource view:
https://marketplace-11.docker-fid.grid.cyf-kr.edu.pl/services/100-percent-it-trusted-cloud
Provider view:
https://marketplace-11.docker-fid.grid.cyf-kr.edu.pl/providers/55
Closes #1799
> [#1799] Highcharts scalability

- CHANGELOG.md
- app/controllers/executive/statistics_controller.rb
- app/models/usage_report.rb
- app/views/executive/statistics/_statistic.html.haml
- app/views/executive/statistics/index.html.haml
- spec/features/executive/statistics_spec.rb
Change logic of statisctics to `MP orddering` and `No MP ordering`
Add counters for all access types
Closes #1771
> [#1771] Review statistics in executive panel

- app/services/importers/service.rb
- db/migrate/20210226164811_migrate_services_to_published_status.rb
- db/schema.rb
Add migration for changing status value
Change default in importers mapping
Fixes #1797
> [#1797] Migrate `unverified` services to `published` status

- CHANGELOG.md
- app/controllers/backoffice/services_controller.rb
- app/controllers/services/ordering_configurations_controller.rb
- app/controllers/services_controller.rb
- app/models/offer.rb
- app/services/offer/destroy.rb
- db/migrate/20210302061137_migrate_offers_to_deleted.rb
- show only published offers
- change the status of the offer when deleting to deleted if there is an order
- migrate drafts to deleted
Closes #1796
> [#1796] Differences in the behaviour of the offer UI and API

- app/controllers/concerns/service/recommendable.rb
- app/javascript/app/index.js
- app/javascript/app/user-action.js
- app/services/recommender/simple_recommender.rb
- app/views/comparisons/_service.html.haml
- app/views/comparisons/show.html.haml
- app/views/services/_active_filters.html.haml
- app/views/services/_offers_box.html.haml
- app/views/services/_search.html.haml
- app/views/services/_service.html.haml
- app/views/services/filters/_multiselect_level.html.haml
- app/views/services/sidebar/_simple_links.html.haml
- spec/features/comparison_spec.rb
- spec/features/recommended_spec.rb
- spec/features/user_action_spec.rb
Based on @Marcelinna comments in #1814 
- [Fix] Single user action should be recorded once (prevent HTML bubbling) 
- Add attributes to not mentioned items in ['Recommendation's probe placement ...'](https://docs.cyfronet.pl/display/FID/Recommendation%27s+probe+placement+and+specification+in+MP) to keep consistency
- Track user typing in catalog search, add listener to it
> [#1782] Fixes of probe system

- CHANGELOG.md
- app/controllers/admin/tour_feedbacks_controller.rb
- app/controllers/tour_feedbacks_controller.rb
- app/javascript/stylesheets/_bootstrap-customizations.scss
- app/javascript/stylesheets/_tours.scss
- app/views/admin/tour_feedbacks/_rating.html.haml
- app/views/admin/tour_feedbacks/index.html.haml
- app/views/layouts/admin/_navbar.html.haml
- config/breadcrumbs/admin.rb
- config/routes.rb
Add tour feedback view in admin section
> [#1805] Tour feedback view

- CHANGELOG.md
- app/helpers/service/details_helper.rb
- app/helpers/service/header_helper.rb
- app/javascript/stylesheets/_bootstrap-customizations.scss
- app/views/providers/_header.html.haml
- app/views/providers/header/_list.html.haml
- config/locales/views/providers/en.yml
- added legal status to header
- added life cycle to header
- change order in details tab
Local view:
Closes #1832
> [#1832] Improved Providers details view

- app/models/category.rb
- lib/tasks/rdt.rake
Add to task rdt:add_vocabularies slug repair
Change slug generating based on parent
Fixes #1904
> [#1904] Fix categories slugs

- app/services/service/pc_create_or_update.rb
- spec/services/service/pc_create_or_update_spec.rb
Add upstream set by resource create and update
Fixes #1902
> [#1902] Fix upstream set for resources from jms

- Gemfile
- Gemfile.lock
- spec/rails_helper.rb
- repeat test cases 3 times until they pass or return failure
> Temporary fix for Capybara random tests failure

- CHANGELOG.md
- Gemfile.lock
- db/vocabulary.yml
- lib/tasks/rdt.rake
Merge missing commits from released v3.9.0
> 3.9.0 backport to master

- app/helpers/project_items_helper.rb
- link to resources that filters by provider uses id
> [HOTFIX] Fix links on project view

- CHANGELOG.md
- app/helpers/markdown_helper.rb
- app/services/importers/service.rb
- docs/upgrade/3.10.0.md
- spec/helpers/markdown_helper_spec.rb
> [#1935] Fix bad markdown import from EIC

- app/models/concerns/eventable.rb
- app/models/event.rb
- app/models/message.rb
- app/models/project.rb
- app/models/project_item.rb
- db/migrate/20210406133857_create_events.rb
- db/schema.rb
- spec/models/event_spec.rb
- spec/models/message_spec.rb
- spec/models/project_item_spec.rb
- spec/models/project_spec.rb
> [#1882] Events implementation and gathering

- app/mailers/service_mailer.rb
- app/models/category.rb
- app/models/scientific_domain.rb
- app/views/backoffice/categories/index.html.haml
- app/views/backoffice/categories/show.html.haml
- app/views/backoffice/scientific_domains/index.html.haml
- app/views/backoffice/scientific_domains/show.html.haml
- app/views/home/products/_cards.html.haml
- app/views/leads/use_case/_card.html.haml
Fix logo validation
in Category & ScientificDomain model
Fix error with rendering broken logo
Fixes #1958
> [#1958] Fix logo validation

- app/controllers/api/v1/oms/events_controller.rb
- app/models/event.rb
- app/models/oms.rb
- app/policies/api/v1/oms/event_policy.rb
- app/serializers/ordering_api/v1/event_serializer.rb
- spec/requests/api/v1/oms/events_controller_spec.rb
- spec/serializers/ordering_api/v1/event_serializer_spec.rb
> [#1963] Implement events endpoint

- CHANGELOG.md
- app/models/concerns/importable.rb
Fixes error with "eid must exist"
> [HOTFIX] Fix provider mapping in importers

- CHANGELOG.md
- README.md
- app/models/provider.rb
- app/services/provider/pc_create_or_update.rb
- db/migrate/20210401095458_add_upstream_to_provider.rb
- db/schema.rb
- lib/import/providers.rb
- lib/tasks/import.rake
- spec/lib/import/providers_spec.rb
- spec/services/provider/pc_create_or_update_spec.rb
Fixes REST and JMS importers should set upstream for providers
exactly like it is in the services
> [HOTFIX] Fix set upstream for providers

- app/controllers/api/v1/oms/projects/project_items_controller.rb
- app/helpers/project_items_helper.rb
- app/models/concerns/eventable.rb
- app/models/event.rb
- app/models/message.rb
- app/models/project.rb
- app/models/project_item.rb
- app/policies/api/v1/oms/project_item_policy.rb
- app/serializers/ordering_api/v1/event_serializer.rb
- app/serializers/ordering_api/v1/project_item_serializer.rb
- db/migrate/20210415114249_remove_action_delete_from_events.rb
- db/schema.rb
- spec/features/order_spec.rb
- spec/models/event_spec.rb
- spec/models/message_spec.rb
- spec/models/project_item_spec.rb
- spec/models/project_spec.rb
- spec/requests/api/v1/oms/project/project_items_controller_spec.rb
- spec/serializers/ordering_api/v1/event_serializer_spec.rb
- spec/serializers/ordering_api/v1/project_item_serializer_spec.rb
- swagger/v1/ordering/project/project_item/project_item_update.json
- swagger/v1/ordering/swagger.json
The user_secrets hash values are obfuscated, excluding the ones which
were updated by the call (i.e. in method update).
Setting `user_secrets: {}` in policy's permitted_attributes allows any
key.
Ensure user_secrets are obfuscated in events.
API-key: `ck_B7F_WxbZQ9MghtdPm`
oms_id: `1`
1. Log in as a user under https://pr-1992.docker-fid.grid.cyf-kr.edu.pl/.
2. Create a project with a voucherable project_item (for service EC3).
3. Navigate to the Ordering API Swagger-UI: https://pr-1992.docker-fid.grid.cyf-kr.edu.pl/api_docs/swagger/index.html?urls.primaryName=Ordering%20API%20V1%20Docs and authorize with the API-key above.
4. Determine the created project_item_id and project_id (for example using /events? endpoint). All the urls are assumed to be prefixed with `/oms/{oms_id}`.
5. `GET …
> [#1966] Expose user_secrets in ordering API

- app/controllers/admin/help_items_controller.rb
- app/controllers/admin/help_sections_controller.rb
- app/controllers/admin/lead_sections_controller.rb
- app/controllers/admin/leads_controller.rb
- app/controllers/backoffice/categories_controller.rb
- app/controllers/backoffice/platforms_controller.rb
- app/controllers/backoffice/providers_controller.rb
- app/controllers/backoffice/scientific_domains_controller.rb
- app/controllers/backoffice/services_controller.rb
- app/controllers/projects/services/opinions_controller.rb
- app/controllers/projects_controller.rb
- app/controllers/services/summaries_controller.rb
- app/mailers/project_item_mailer.rb
- app/models/project_item/wizard.rb
- app/views/projects/_form.html.haml
- app/views/services/summaries/show.html.haml
- spec/services/project_item/ready_spec.rb
@Marcelinna: the only place which may fail somehow is recaptcha validation in project and project_item creation. Please click through the ordering process to verify that it's not the case.
> Typos correction

- CHANGELOG.md
- app/models/service.rb
- db/migrate/20210422132539_change_resource_organisation_not_null.rb
- db/schema.rb
Field Resource Organisation is required, so this PR fixes this problem in BO create Resource form.
Closes #2020
> [#2020] Fix Field Resource Organisation is required

- CHANGELOG.md
- app/models/service.rb
- db/migrate/20210422132539_change_resource_organisation_not_null.rb
- db/schema.rb
- field requirement in Resource creation view
- migration for resource_organisation_id
> [#2020] Fix Resource Organisation field requirement (forward port to master)

- CHANGELOG.md
- app/controllers/favourites/services_controller.rb
> [#1873] Fix popup text for logged user

- app/helpers/order_nav_helper.rb
- config/robots.production.txt
- db/data.yml
- lib/tasks/dev.rake
- spec/rails_helper.rb
- Add resource mock with offers of different type
- Submit selected offer on navigating with steps bar
- Increase re-run of failed Capybara tests
- Change Crawl Delay to max acceptable by bots
> [#1960] fix change offer with step bar, increase Capybara failed tests re-run, setup max acceptable bots Crawl Delay

- CHANGELOG.md
- app/helpers/backoffice/providers_helper.rb
- app/policies/backoffice/provider_policy.rb
- app/views/backoffice/providers/_data_administrator_fields.html.haml
- app/views/backoffice/providers/_form.html.haml
- app/views/backoffice/providers/form/_admins.html.haml
- app/views/backoffice/providers/form/_basic.html.haml
- app/views/backoffice/providers/form/_classification.html.haml
- app/views/backoffice/providers/form/_contact.html.haml
- app/views/backoffice/providers/form/_location.html.haml
- app/views/backoffice/providers/form/_marketing.html.haml
- app/views/backoffice/providers/form/_maturity.html.haml
- app/views/backoffice/providers/form/_other.html.haml
- app/views/backoffice/providers/form/_public_contact_fields.html.haml
- spec/features/backoffice/providers_spec.rb
Provider in BO should not be editable when upstream is set to MP.
Closing #1997
> [#1997] Editorial rights for providers

- app/controllers/users/auth_mock_controller.rb
- Add privileges to Auth Mock endpoint
- admin
- data admin
- service portfolio manager
- executive
> Auth mock extension

- .github/workflows/ci.yml
- .github/workflows/e2e.yml
- README.md
see readme here. https://github.com/cyfronet-fid/marketplace/tree/read-me
change badge to show gh-action status for Build workflow
added badge for integration test (e2e) workflow
change name for ci.yml, build workflow from CI to Build
> Change travis to GH-Actions badge on README.md

- app/javascript/stylesheets/_base.scss
- app/javascript/stylesheets/_bootstrap-customizations.scss
- app/javascript/stylesheets/_header.scss
- app/javascript/stylesheets/_order.scss
- app/javascript/stylesheets/_ref_mobile.scss
- app/views/backoffice/providers/_form.html.haml
- app/views/backoffice/providers/form/_admins.html.haml
- app/views/backoffice/providers/form/_basic.html.haml
- app/views/backoffice/providers/form/_classification.html.haml
- app/views/backoffice/providers/form/_contact.html.haml
- app/views/backoffice/providers/form/_location.html.haml
- app/views/backoffice/providers/form/_marketing.html.haml
- app/views/backoffice/providers/form/_maturity.html.haml
- app/views/backoffice/providers/form/_other.html.haml
- app/views/backoffice/providers/new.html.haml
- app/views/backoffice/services/_form.html.haml
- app/views/backoffice/services/_search.html.haml
- app/views/backoffice/services/index.html.haml
- app/views/backoffice/services/offers/_form.html.haml
- app/views/layouts/backoffice/_navbar.html.haml
Pack of CSS and haml mods according to #2106.
> 2106 RWD problems 1

- CHANGELOG.md
- app/javascript/app/controllers/filter_controller.js
- app/javascript/app/controllers/form_controller.js
- spec/features/filter_spec.rb
Remove empty filter parameters in resource search
Closes #1931
> [#1931] Remove unwanted search parameters in url

- app/views/home/communities/_card.html.haml
- app/views/home/products/_cards.html.haml
- app/views/home/providers/_card.html.haml
- app/views/pages/communities.html.haml
- app/views/pages/target_users.html.haml
- app/views/providers/_header.html.haml
- app/views/providers/index.html.haml
- app/views/services/_active_filters.html.haml
- test/system/cypress/integration/regression_tests/home-page/communities_infrastructures.spec.ts
- test/system/cypress/integration/regression_tests/home-page/providers.spec.ts
- test/system/cypress/integration/regression_tests/home-page/scientific-domain_categories.spec.ts
- test/system/cypress/integration/regression_tests/home-page/target_user.spec.ts
- test/system/package.json
Add E2E test for home page
Add test for providers, dedicated for and platforms list.
Add test for scientific domain and categories boxes.
> E2E tests for home page 

- README.md
- lib/tasks/recommender.rake
> [#2183] Recommender update task

- Gemfile
- Gemfile.lock
- spec/features/api_docs_spec.rb
- spec/features/backoffice/providers_spec.rb
- spec/features/comparison_spec.rb
- spec/features/favourite_spec.rb
- spec/features/service_recommendations_spec.rb
- spec/features/service_spec.rb
- spec/models/oms_spec.rb
- spec/rails_helper.rb
- spec/support/helpers/website_helper.rb
remove Repeat from gemfile
https://docs.cyfronet.pl/display/FID/MP+-+Rails+-+Async+JS+Tests
Closes #2049
> [#2049] Capybara failing tests

- app/controllers/concerns/service/recommendable.rb
> [#2209] Recommendations disappearing for certain view options

- app/views/comparisons/_bar.html.haml
- app/views/comparisons/_service.html.haml
- app/views/comparisons/show.html.haml
- app/views/services/_header.html.haml
- app/views/services/_service.html.haml
- app/views/services/index.html.haml
- app/views/services/show.html.haml
- test/system/cypress/integration/regression_tests/servce-page/comparison/comparison.spec.ts
- test/system/cypress/support/index.ts
Add tests for adding and removing services from comparison.
Hide cookies policy box and tour guide.
> add e2e tests for comparison

- app/controllers/concerns/recommendation/followable.rb
- app/controllers/concerns/service/recommendable.rb
- app/helpers/validation_helper.rb
- Changed TTL for client_uid to 1 week
- Regenerate client_uid if it has a wrong format
Closes #2215
> [2215] Fix problems with client_uid cookie format

- CHANGELOG.md
- app/controllers/backoffice/services_controller.rb
- app/controllers/concerns/service/autocomplete.rb
- app/controllers/services_controller.rb
- app/javascript/app/controllers/autocomplete_controller.js
- app/javascript/app/controllers/search_controller.js
- app/models/provider.rb
- app/views/backoffice/services/_search.html.haml
- app/views/services/_search.html.haml
- app/views/services/autocomplete/_offer_item.html.haml
- app/views/services/autocomplete/_provider_item.html.haml
- app/views/services/autocomplete/_service_item.html.haml
- app/views/services/autocomplete/list.html.haml
- spec/features/home_spec.rb
- spec/features/search_spec.rb
- spec/spec_helper.rb
Change link in autocomplete for providers
to the provider_path
Fixes #1999
> [#1999] Provider search links to the provider page

- CHANGELOG.md
- README.md
- app/controllers/users/omniauth_callbacks_controller.rb
- app/controllers/users/sessions_controller.rb
- app/javascript/app/autologin.js
- app/javascript/app/index.js
- config/application.rb
- config/routes.rb
- docs/autologin_intergration.md
> [#2190] SSO Autlogin POC

- CHANGELOG.md
- app/controllers/backoffice/providers_controller.rb
- app/models/provider.rb
- app/policies/backoffice/provider_policy.rb
- spec/requests/backoffice/providers_spec.rb
- trim the form values before validation (issue nr 1)
- permit the attributes on provider update from params instead of current record (issue nr 2)
> [#2203] Fix the provider backoffice form

- app/javascript/app/controllers/search_controller.js
- app/views/backoffice/services/_search.html.haml
Fix search form redirections to `/null` route
Fixes #2242
> [#2242] Fix autocomplete redirections

- CHANGELOG.md
- app/controllers/projects_controller.rb
- app/javascript/app/choices.js
- app/javascript/app/controllers/offer_controller.js
- app/javascript/app/index.js
- app/views/layouts/show_modal.js.erb
- app/views/projects/_form.html.haml
- app/views/services/summaries/_project_browser.haml
- config/locales/views/services/en.yml
- db/data.yml
- spec/features/order_spec.rb
> [#2083] Fix choices field in modals

- CHANGELOG.md
- app/serializers/api/v1/project_serializer.rb
- spec/serializers/api/v1/project_serializer_spec.rb
- swagger/v1/project/project_read.json
> [#2271] Extend project API with first and last name

- CHANGELOG.md
- app/javascript/stylesheets/_bootstrap-customizations.scss
- app/javascript/stylesheets/_ref_designsystem.scss
- app/javascript/stylesheets/_ref_mobile.scss
- app/javascript/stylesheets/designsystem.scss
- app/views/backoffice/services/_header.html.haml
- app/views/leads/learn_more/_card.html.haml
- app/views/services/ordering_configurations/_header.html.haml
first fixes  #2030 (points 1,3,4)
> graphics fixes

- CHANGELOG.md
- app/views/services/filters/_multiselect_level.html.haml
- db/data.yml
- db/migrate/20210817055554_update_scientific_domains.rb
- db/schema.rb
[The source documentation](https://confluence.egi.eu/pages/viewpage.action?pageId=64914897#EOSCResourceProfile-ResourceScientificDomain)
Fetching emails list
---
```SQL
WITH
domains_ids AS (
WITH ids AS (
SELECT id
FROM scientific_domains
WHERE name = ANY(ARRAY[
'Natural Sciences',
'Engineering & Technology',
'Medical & Health Sciences',
'Agricultural Sciences',
'Social Sciences',
'Humanities',
'Generic',
'Other',
'Mathematics',
'Computer & Information Sciences',
'Physical Sciences',
'Chemical Sciences',
'Earth & Related Environmental Sciences',
'Biological Sciences',
'Other Natural Sciences',
'Electrical, Electronic & Information Engineering',
'Mechanical Engineering',
'Chemical Engineering',
'Materials Engineering',
'Medical Engineering',
'Environmental Engineering',
'Environmental …
```
> [#2138] Migrate scientific domains

- app/views/services/_search.html.haml
- test/system/cypress/integration/regression_tests/home-page/scientific-domain_categories.spec.ts
- test/system/cypress/integration/regression_tests/servce-page/mainsearch/mainsearch.spec.ts
Add e2e tests for searchbar
Add tests for searching items in the searchbar
> Add e2e tests for searchbar

- CHANGELOG.md
- app/javascript/stylesheets/_bootstrap-customizations.scss
- app/javascript/stylesheets/_header.scss
- app/javascript/stylesheets/_ref_mobile.scss
- app/javascript/stylesheets/_shepherd.scss
- app/views/admin/ab_tests/show.html.haml
- app/views/admin/features/show.html.haml
- app/views/admin/leads/index.html.haml
- app/views/admin/tour_feedbacks/index.html.haml
- app/views/layouts/_navbar.html.haml
- app/views/layouts/admin/_navbar.html.haml
- app/views/pages/communities.html.haml
- app/views/pages/target_users.html.haml
- app/views/providers/_related.html.haml
- app/views/providers/index.html.haml
RWD Admin panel mods according to #2117 
Fix for #2292 
commit:
[#2117 #2292] Fixed drop-down menu and RWD CSS styles
> [#2292, #2117] rwd problems 2

- app/views/services/_active_filters.html.haml
Add query parameter to the link
to "Clear all filters" in the resources page
Closes #2295
> [#2295] Store query parameter by clearing filters

- app/helpers/tour_helper.rb
- app/javascript/app/index.js
- app/javascript/app/tours.js
- app/javascript/stylesheets/_test.scss
- app/views/layouts/_tour.erb
- app/views/profiles/_form.html.haml
- config/tours/services/show.en.yml
- spec/features/service_recommendations_spec.rb
- spec/features/tours/profile_spec.rb
- spec/features/tours/service_spec.rb
- spec/support/helpers/cookie_helper.rb
> Refactor tours

- CHANGELOG.md
- app/javascript/stylesheets/_shepherd.scss
- app/javascript/stylesheets/_tours.scss
- app/views/home/_communities.haml
- app/views/home/_info.html.haml
- app/views/home/_products.html.haml
- app/views/layouts/_tour.erb
- app/views/services/_filters.html.haml
- app/views/services/_index.html.haml
- app/views/services/_search.html.haml
- app/views/services/_service.html.haml
- app/views/services/_service_details.html.haml
- app/views/services/nav/_categories.html.haml
- app/views/services/show.html.haml
- config/routes.rb
- config/tours.yml
- config/tours/home/index.en.yml
- config/tours/services/index.en.yml
- config/tours/services/show.en.yml
- spec/features/tours/overview_spec.rb
Create a virtual tour for new users named `overview`.
Create a direct route to handle transitioning from the service list to a
concrete service.
Closes: #2274.
Navigate to https://pr-2311.docker-fid.grid.cyf-kr.edu.pl?tour=overview and take the tour.
>  [#2274] Virtual tour for new users

- CHANGELOG.md
- app/controllers/services/application_controller.rb
- app/controllers/services/configurations_controller.rb
- app/controllers/services/offers_controller.rb
- app/controllers/services/summaries_controller.rb
- app/models/customizable_project_item.rb
- app/models/offer.rb
- app/models/project_item/customization.rb
- app/models/project_item/offer_values.rb
- app/models/project_item/part.rb
- app/models/project_item/project_validation.rb
- app/models/project_item/wizard.rb
- app/services/project_item/create.rb
- app/views/projects/services/_layout.html.haml
- app/views/projects/show.js.erb
- app/views/services/_bundle_box.html.haml
- app/views/services/_offer.html.haml
- app/views/services/summaries/_bundle_technical.html.haml
- app/views/services/summaries/show.html.haml
- spec/factories/customizable_project_items.rb
- spec/features/add_item_to_project_spec.rb
- spec/features/order_spec.rb
- spec/services/project_item/create_spec.rb
- test/system/cypress/integration/offers.spec.ts
Add a validation of bundled parameters
in the configuration step of the service ordering form
Fixes #2342
> Bundle configuration form validation

- CHANGELOG.md
- app/controllers/backoffice/providers_controller.rb
- app/jobs/provider/delete_job.rb
- app/services/importers/provider.rb
- app/services/jms/manage_message.rb
- app/services/provider/delete.rb
- spec/services/jms/manage_message_spec.rb
Add possibility to delete a provider via JMS
Closes #2372
> [#2372] Handle provider deletion in JMS

- CHANGELOG.md
- app/javascript/stylesheets/_header.scss
- app/javascript/stylesheets/_ref_mobile.scss
Fixed 992px issue when no main menu was displayed (mobile and desktop nav).
> [#2321]  Set mobile nav until 991px

- CHANGELOG.md
move entry 'Fix RWD CSS Styles (@jarekzet)' to the proper place
> Fix changelog for 3.26.0-milestone

- CHANGELOG.md
- app/controllers/projects_controller.rb
- spec/features/projects_spec.rb
Fix copying scientific_domains
by duplicating a Project
Fixes #2387
> [#2387] Fix duplicating a project

- CHANGELOG.md
- app/controllers/services/configurations_controller.rb
> [#2398] Move auth to last step of the Access Wizard

- app/helpers/url_helper.rb
- app/views/backoffice/providers/_form.html.haml
- app/views/backoffice/providers/form/_location.html.haml
- app/views/backoffice/providers/index.html.haml
- app/views/backoffice/services/_search.html.haml
- app/views/services/filters/_multiselect.html.haml
- test/system/cypress/factories/provider.factory.ts
- test/system/cypress/integration/regression_tests/backoffice/providers/providers.spec.ts
- test/system/cypress/integration/regression_tests/backoffice/scientific-domain/scientific-domain.spec.ts
- test/system/cypress/support/category.ts
- test/system/cypress/support/index.ts
- test/system/cypress/support/providers.ts
- test/system/cypress/support/resources.ts
- test/system/cypress/support/scientific-domain.ts
Add test for adding, editing and deleting provider without resources
Handle exception Failed to open TCP connection from Faraday
> Test e2e for provider in backoffice

- CHANGELOG.md
- config/locales/en.yml
- spec/features/order_spec.rb
> [#2393] Update the Wizzard Access error msg

- CHANGELOG.md
- app/javascript/stylesheets/_bootstrap-customizations.scss
- app/javascript/stylesheets/_ref_mobile.scss
- app/javascript/stylesheets/_variables.scss
- app/models/service_opinion.rb
- app/views/projects/services/_rating.html.haml
- app/views/projects/services/opinions/_stars.html.haml
- app/views/projects/services/opinions/_stars_template.html.haml
- app/views/projects/services/opinions/new.haml
- spec/features/opinions_spec.rb
- spec/models/service_opinion_spec.rb
Change rating minimum value from 0 to 1
Saved clicked value of rating
after wrong validation is visible now
by page reload
Closes #2386
https://projects.invisionapp.com/share/JXOZKC8WMDU#/screens/461056259_Review_Form_V2_Error_Handler
https://projects.invisionapp.com/share/JXOZKC8WMDU#/screens/461041194_Review_Form_V2
> [#2386] Improve review functionality

- CHANGELOG.md
- app/controllers/projects/services_controller.rb
- app/helpers/project_items_helper.rb
- app/javascript/stylesheets/_bootstrap-customizations.scss
- app/javascript/stylesheets/_ref_mobile.scss
- app/javascript/stylesheets/_status.scss
- app/javascript/stylesheets/_variables.scss
- app/views/projects/_empty_project.html.haml
- app/views/projects/_project_description.html.haml
- app/views/projects/_project_layout.html.haml
- app/views/projects/nav/_projects.html.haml
- app/views/projects/services/_layout.html.haml
- app/views/projects/services/_project_item.html.haml
- app/views/projects/services/index.html.haml
- spec/factories/offers.rb
- spec/features/my_services_spec.rb
Closes #2388 
@wujuu:
- Added separation of project items in project view, based on their order type
@jarekzet:
- Project styling overhaul
> [#2388] Enhance user project view

- CHANGELOG.md
- app/javascript/stylesheets/_bootstrap-customizations.scss
- app/javascript/stylesheets/_ref_designsystem.scss
- app/javascript/stylesheets/_ref_mobile.scss
- app/views/comparisons/_bar.html.haml
- app/views/home/_carousel-card.html.haml
- app/views/projects/nav/_projects.html.haml
- app/views/services/_offer.html.haml
This PR resolves issues due to: #2294 , #2238 , #1840 and "create new project" button styling according to prev: https://projects.invisionapp.com/share/JXOZKC8WMDU#/screens/460826934
> Layout mods

- README.md
> Add information about ImageMagick in the README.md

- CHANGELOG.md
- app/javascript/app/controllers/parameter_controller.js
- app/javascript/stylesheets/_bootstrap-customizations.scss
- app/views/layouts/common_parts/services/_parameters.html.haml
- app/views/services/_offer.html.haml
- app/views/services/offers/_description.html.haml
- app/views/services/offers/_parameters.html.haml
Fix for extra paragraph in description area.
https://github.com/cyfronet-fid/marketplace/pull/2439#issuecomment-986770764
> resource offers description fix

- CHANGELOG.md
- app/helpers/service/header_helper.rb
- app/views/services/_header.html.haml
> [#2452] Fix redirect to PC

- db/data_e2e.yml
- lib/tasks/dev.rake
- test/system/cypress.json
- test/system/cypress/integration/offers.spec.ts
- test/system/cypress/integration/regression_tests/backoffice/providers/providers.spec.ts
- test/system/cypress/integration/regression_tests/backoffice/resources/owned_resources.spec.ts
Adjust data_e2e.yml
Add test for delete provider in BO
Change test for Preview mode in BO
> Add e2e tests for provider and resources in BO

- app/views/backoffice/platforms/_form.html.haml
- app/views/backoffice/platforms/index.html.haml
- test/system/cypress/factories/platform.factory.ts
- test/system/cypress/integration/regression_tests/backoffice/category/category.spec.ts
- test/system/cypress/integration/regression_tests/backoffice/platforms/platforms.spec.ts
- test/system/cypress/support/index.ts
- test/system/cypress/support/platforms.ts
Add e2e tests for platforms in backoffice
Add tests for create, delete, edit platform in BO
> Add e2e tests for platforms in backoffice

- README.md
- config/initializers/devise.rb
> [#2462] Add configurable checking scopes env

- .github/workflows/ci.yml
- .github/workflows/e2e.yml
- .tool-versions
- Gemfile
- README.md
- config/database.yml
- docker-compose.yml
> [#2465] Add docker-compose.yml to manage services

- app/services/jms/do_publish.rb
- app/services/jms/publisher.rb
- spec/services/jms/publisher_spec.rb
> [#2418] Add Jms::Publisher tests

- CHANGELOG.md
- app/helpers/service/header_helper.rb
- app/views/backoffice/services/_header.html.haml
- app/views/services/_header.html.haml
- app/views/services/ordering_configurations/_header.html.haml
Fix singularization when a resource has 1 review
Closes #2266
> [#2266] Fix Resource reviews counters

- CHANGELOG.md
- app/controllers/home_controller.rb
- app/helpers/service_helper.rb
- app/jobs/provider/pc_create_or_update_job.rb
- app/models/filter/provider.rb
- app/models/provider.rb
- app/models/usage_report.rb
- app/policies/provider_policy.rb
- app/services/jms/manage_message.rb
- app/services/provider/pc_create_or_update.rb
- spec/services/jms/manage_message_spec.rb
- spec/services/provider/pc_create_or_update_spec.rb
> [#2445] Provider draft status

- app/services/jms/manage_message.rb
- spec/factories/jms_xml_provider.rb
- spec/services/jms/manage_message_spec.rb
notyfications: create / update / delete
we use update and delete -> deleted
in update notifications there are: 
1. active approved -> published
2. non-active approved -> draft
Closes #2490
> 2490 fix provider statuses

- CHANGELOG.md
- app/helpers/backoffice/services_helper.rb
- app/javascript/stylesheets/_bootstrap-customizations.scss
- app/javascript/stylesheets/_ref_mobile.scss
- app/views/backoffice/providers/index.html.haml
- app/views/backoffice/providers/show.html.haml
- test/system/cypress/integration/regression_tests/backoffice/providers/providers.spec.ts
added provider status label on BO providers list and provider details view according to #2468
> [#2468] Visual representation of statuses for providers in BO

- CHANGELOG.md
- app/controllers/backoffice/scientific_domains_controller.rb
- app/views/backoffice/platforms/index.html.haml
- app/views/backoffice/scientific_domains/index.html.haml
Fixes bad redirection for scientific domain after deletion in backoffice
Close #2348
> [#2348] Fixes bad redirect in backoffice

- CHANGELOG.md
- app/models/offer.rb
- app/services/service/update.rb
- app/views/backoffice/services/offers/_one_offer_edit_form.html.haml
- db/data.yml
- db/data_e2e.yml
- spec/factories/offers.rb
- spec/features/add_item_to_project_spec.rb
- spec/features/backoffice/services_spec.rb
- spec/features/my_services_spec.rb
- spec/features/order_spec.rb
- spec/features/project_services_spec.rb
- spec/features/projects_spec.rb
- spec/lib/import/resources_spec.rb
- spec/models/offer_spec.rb
- spec/models/usage_report_spec.rb
- spec/requests/api/v1/resources/offers_controller_spec.rb
- spec/services/project_item/create_spec.rb
- spec/services/project_item/ready_spec.rb
Fixes posibility of setting different order types
for offer and resource if that resource has
only one offer
Fixes #2322
> [#2322] Fix various types for service with one offer

- CHANGELOG.md
- app/javascript/app/choices.js
- app/models/attribute/select.rb
- app/models/parameter/values.rb
- package.json
- spec/models/parameter/select_spec.rb
- test/system/cypress/support/offers.ts
- test/system/cypress/support/providers.ts
- test/system/cypress/support/resources.ts
- yarn.lock
Update choices.js to 10.0.0
Fix problem with casting numerical strings
Fix escaping html in parameter values
Fixes #1459
> [#1459] Fix validation of parameters

- config/locales/simple_form.en.yml
- db/data.yml
- db/data_e2e.yml
- lib/tasks/dev.rake
Add missing fields to seed database with providers
Add missing associations seeded as samples
Fixes #1810
> [#1810] Add new fields to providers in dev:prime

- .github/workflows/e2e.yml
- app/views/projects/edit.html.haml
- app/views/projects/nav/_projects.html.haml
- app/views/projects/new.html.haml
- app/views/projects/services/_rating.html.haml
- app/views/projects/services/opinions/new.haml
- app/views/services/summaries/_project_browser.haml
- config/environments/development.rb
- db/data_e2e.yml
- test/system/cypress.json
- test/system/cypress/integration/offers.spec.ts
- test/system/cypress/integration/regression_tests/backoffice/providers/providers.spec.ts
- test/system/cypress/integration/regression_tests/backoffice/resources/owned_resources.spec.ts
- test/system/cypress/integration/regression_tests/servce-page/my_eosc_marketplace/my-profile.spec.ts
- test/system/cypress/integration/regression_tests/servce-page/my_eosc_marketplace/my-project.spec.ts
- test/system/cypress/integration/regression_tests/servce-page/resources/resources.spec.ts
- test/system/cypress/plugins/index.js
- test/system/cypress/support/auth.ts
- test/system/cypress/support/index.ts
- test/system/cypress/support/project.ts
- test/system/cypress/support/utilities.ts
- test/system/package-lock.json
- test/system/package.json
Add e2e tests for projects and resources
Update cypress 9.3.1 and add fail-fast dependencie
> Add e2e tests for projects and resources

- CHANGELOG.md
- app/models/provider.rb
- app/models/service.rb
Apply strip to name for jms and rest update for Provider and Resource
Fixes #2529
> [#2529] Strip whitespaces in name for Provider and Resource

- .github/workflows/e2e.yml
- app/views/providers/_tabs.haml
- app/views/taggable/_details_section.html.haml
- db/data_e2e.yml
- docker-compose-e2e.yml
- test/system/cypress/factories/provider.factory.ts
- test/system/cypress/integration/integration_JIRA.spec.ts
- test/system/cypress/integration/regression_tests/backoffice/providers/providers.spec.ts
- test/system/cypress/support/index.ts
- test/system/cypress/support/providers.ts
- test/system/package-lock.json
- test/system/package.json
- test/system/tsconfig.json
Add e2e test for draft provider and provider created by fully filled form
Add docker compose file for e2e and cypress-grep dependency
> Add e2e test for draft provider and provider created by fully filled form

- CHANGELOG.md
- app/views/projects/services/_project_item.html.haml
> [#2492] Fix lack of "new message" icon in bundles

- CHANGELOG.md
- app/models/project_item.rb
- app/views/projects/services/_layout.html.haml
- app/views/projects/services/_project_item.html.haml
- app/views/projects/services/show.html.haml
- app/views/services/configurations/_attributes.html.haml
- app/views/services/configurations/_bundled_offers.html.haml
- app/views/services/configurations/_voucher.html.haml
- app/views/services/configurations/show.html.haml
- app/views/services/summaries/_bundled_services.html.haml
- app/views/services/summaries/_project_browser.haml
- app/views/services/summaries/_technical_configuration.html.haml
- app/views/services/summaries/show.html.haml
- spec/features/order_spec.rb
Also, change the names from project_item to step in wizard to avoid
confusion.
Fixes: #2573.
> [#2573] Don't depend on offer for project_item bundle

- app/controllers/concerns/service/recommendable.rb
closes #2588 
- New tests have not been added because in the searchable_spec file there are tests that test even more extensive functionality of the same feature that has been added here,
- merge of this feature does not collide with the lack of handling of this field in the RS. It can be merged and it won't spoil anything on the recommender's side.
> [#2588] Pass ElasticSearch's services id to the RS

- .run/Import providers.run.xml
- .run/Import resources.run.xml
- .run/Start app.run.xml
- .run/Start containers.run.xml
- CHANGELOG.md
- README.md
- app/services/importers/token.rb
- config/initializers/devise.rb
- lib/import/providers.rb
- lib/import/resources.rb
- lib/tasks/import.rake
- spec/lib/import/providers_spec.rb
- spec/lib/import/resources_spec.rb
**IMPORTANT!!!**
Today (24.03.2022) the service hasn't worked. AAI successfully delivered an access token, but the provider service throw 404.
---
For testing purposes:
go to: https://aai.eosc-portal.eu/providers-api/
ENV:
MP_IMPORT_EIC_URL=https://beta.providers.eosc-portal.eu/api
UPSTREAM=eic
IMPORTER_AAI_REFRESH_TOKEN=<AS AT IMAGE>
IMPORTER_AAI_BASE_URL=aai.eosc-portal.eu
IMPORTER_AAI_CLIENT_ID=<AS AT IMAGE>
> [#2596] Fetch JWT token using refresh token

- README.md
- app/controllers/user_action_controller.rb
- app/jobs/jms/publish_job.rb
- app/services/jms/publish.rb
- config/application.rb
- config/stomp_publisher.yml
- spec/controllers/user_action_controller_spec.rb
> [#2537] Integrate user_actions with JMS

- CHANGELOG.md
- config/breadcrumbs/backoffice.rb
> [#2580] Fix nested category breadcrumb in BO

- CHANGELOG.md
- app/models/country.rb
- spec/features/order_spec.rb
- spec/features/projects_spec.rb
> [#2613] Fix country order on edit provider view in BO

- CHANGELOG.md
- lib/import/resources.rb
- spec/lib/import/resources_spec.rb
> [#2641] Customize REST Resource importer to new endpoint

- CHANGELOG.md
- app/models/provider.rb
- db/migrate/20220421084638_remove_unique_from_name_in_providers.rb
- db/schema.rb
- lib/import/providers.rb
- spec/lib/import/providers_spec.rb
- spec/models/provider_spec.rb
Hotfix to production version 3.36.0.
fix import for situation when there are two providers with the same name but diff ids
Fixes #2646.
> [#2646] Fix providers import

- app/components/presentable/header_component.html.haml
- app/views/favourites/_empty_box.html.haml
- app/views/favourites/_service.html.haml
- app/views/layouts/_navbar.html.haml
- app/views/layouts/_popup.html.haml
- app/views/services/_service.html.haml
- test/system/cypress/integration/regression_tests/servce-page/favourites/favourites.spec.ts
Add tests for adding and removing services from favouriries.
> Add e2e tests for favourities

- CHANGELOG.md
- app/helpers/forms_helper.rb
- app/javascript/app/controllers/filter_controller.js
- app/javascript/stylesheets/_bootstrap-customizations.scss
- app/models/filter.rb
- app/models/filter/ancestry_multiselect.rb
- app/views/home/_products.html.haml
- app/views/layouts/backoffice.html.haml
- app/views/services/filters/_multiselect.html.haml
- app/views/services/filters/_multiselect_level.html.haml
- spec/models/filter/scientific_domain_spec.rb
- test/system/cypress/integration/regression_tests/servce-page/filters/all_filters.spec.ts
Add indeterminate state for multilevel checkboxes
Closes #2558
> [#2558] Improve multicheckbox filters

- CHANGELOG.md
- app/helpers/presentable/details_helper.rb
- app/policies/backoffice/service_policy.rb
- app/services/importers/service.rb
- app/views/backoffice/services/_form.html.haml
- config/locales/views/components/en.yml
- db/migrate/20220517202141_add_catalogue_to_service.rb
- db/schema.rb
- spec/policies/backoffice/service_policy_spec.rb
Add catalogue field in the dependencies section for Resource form
Closes #2659
> [#2659] Catalogue for Resource Profile 4.0

- app/services/service/ess/add.rb
added slug and description to payload in rest to ESS
Fixes #2674
> Add 'Resource' slug and description to payload for ESS

- CHANGELOG.md
- app/components/presentable/header_component.html.haml
- app/components/presentable/header_component.rb
- app/javascript/stylesheets/_bootstrap-customizations.scss
- app/policies/backoffice/service_policy.rb
- app/services/importers/service.rb
- app/views/backoffice/services/_form.html.haml
- app/views/backoffice/services/preview.html.haml
- app/views/backoffice/services/show.html.haml
- app/views/services/_service_details.html.haml
- app/views/services/show.html.haml
- db/migrate/20220514101619_add_abbreviation_to_service.rb
- db/schema.rb
- spec/policies/backoffice/service_policy_spec.rb
Add abbreviation string input to the Service model
Closes #2636
> [#2636] Abbreviation for Resource Profile 4.0

- app/javascript/stylesheets/_bootstrap-customizations.scss
border bottom removed from resource view in FO and BO
> abbreviation border bottom fix

- app/services/service/ess/add.rb
Change payload to properly show tree structure for
categories, scientific_domains, target_users
Fixes #2682
> Solr payload

- app/components/presentable/details_component.rb
- app/components/presentable/sidebar_component.rb
- app/helpers/presentable/details_helper.rb
- app/helpers/presentable/details_style_helper.rb
- app/jobs/catalogue/pc_create_or_update_job.rb
- app/models/catalogue.rb
- app/models/concerns/importable.rb
- app/models/provider.rb
- app/models/provider_catalogue.rb
- app/models/service.rb
- app/models/service_catalogue.rb
- app/services/catalogue/pc_create_or_update.rb
- app/services/importers/catalogue.rb
- app/services/importers/provider.rb
- app/services/importers/service.rb
- app/services/jms/manage_message.rb
- app/views/backoffice/providers/form/_dependencies.html.haml
- app/views/backoffice/services/_form.html.haml
- config/locales/views/components/en.yml
- db/data.yml
- db/data_e2e.yml
- db/migrate/20220519094804_create_catalogue.rb
- db/migrate/20220519095130_create_service_catalogue.rb
- db/migrate/20220519095145_create_provider_catalogue.rb
- db/migrate/20220519095301_remove_catalogue_from_service_and_provider.rb
- db/migrate/20220520071847_add_synchronized_at_to_catalogue.rb
- db/schema.rb
- lib/import/catalogues.rb
- lib/tasks/dev.rake
- lib/tasks/import.rake
> #2672 catalogue

- CHANGELOG.md
- app/helpers/backoffice/services_helper.rb
- app/helpers/presentable/details_helper.rb
- app/models/concerns/importable.rb
- app/models/platform.rb
- app/services/importers/service.rb
- app/views/backoffice/services/_form.html.haml
- db/migrate/20220527114805_extend_platforms.rb
- db/schema.rb
- lib/import/vocabularies.rb
- spec/features/backoffice/services_spec.rb
Add vocabulary fields to the Platforms table
Change displaying platforms field depending
on PROFILE_4_ENABLED value
Closes #2660
> [#2660] Extend platforms

- CHANGELOG.md
- app/models/concerns/importable.rb
- app/services/importers/service.rb
Removed try to import Provider via REST
when Resource is updated via JMS
Closes #2446
> [#2446] Fix providers import on JMS Resource update

- app/views/backoffice/vocabularies/_form.html.haml
- app/views/backoffice/vocabularies/index.html.haml
- app/views/backoffices/show.html.haml
- db/data_e2e.yml
- lib/tasks/dev.rake
- test/system/cypress/factories/vocabulary.factory.ts
- test/system/cypress/fixtures/messages.js
- test/system/cypress/integration/regression_tests/backoffice/vocabularies/vocabularies.spec.ts
- test/system/cypress/support/index.ts
- test/system/cypress/support/vocabulary.ts
Add test for adding, deleting and editing vocabulary  in backoffice
> Add e2e test for vocabularies in backoffice

- spec/factories/catalogue.rb
- spec/factories/jms_catalogue_response.rb
- spec/factories/jms_xml_catalogue.rb
- spec/services/catalogue/pc_create_or_update_spec.rb
- spec/services/importers/catalogue_spec.rb
- spec/services/jms/manage_message_spec.rb
> [#2687] Catalogue rest and jms tests

- CHANGELOG.md
- app/controllers/home_controller.rb
> [#2708] Fixed Communities section on the home page

- CHANGELOG.md
- app/views/backoffice/services/_form.html.haml
Add sorting of providers list
in the backoffice service form
Fixes #2619
> [#2619] Alphabetical sorting of providers list

- CHANGELOG.md
- app/helpers/categories_helper.rb
- app/javascript/stylesheets/_bootstrap-customizations.scss
- app/javascript/stylesheets/_ref_mobile.scss
- app/views/admin/helps/_section.html.haml
- app/views/admin/helps/show.html.haml
- app/views/backoffice/categories/_form.html.haml
- app/views/backoffice/categories/index.html.haml
- app/views/backoffice/platforms/_form.html.haml
- app/views/backoffice/platforms/index.html.haml
- app/views/backoffice/scientific_domains/_form.html.haml
- app/views/backoffice/scientific_domains/index.html.haml
- app/views/backoffice/vocabularies/_form.html.haml
- app/views/backoffice/vocabularies/index.html.haml
- app/views/backoffices/show.html.haml
- app/views/layouts/_navbar.html.haml
- app/views/layouts/_popup.html.haml
- app/views/layouts/executive/_navbar.html.haml
- app/views/profiles/_form.html.haml
- app/views/services/offers/_description.html.haml
Bugfixes for #2449 , https://github.com/cyfronet-fid/marketplace/issues/2741
> 2449, 2741 style problems

- app/controllers/backoffice/services_controller.rb
- app/controllers/concerns/service/recommendable.rb
- app/controllers/services/details_controller.rb
- app/controllers/services_controller.rb
- app/views/backoffice/services/show.html.haml
- app/views/services/show.html.haml
Allow to show similar services for unlogged users
> Update similar services request

- CHANGELOG.md
- README.md
- app/controllers/concerns/service/recommendable.rb
- app/models/catalogue.rb
- app/services/importers/provider.rb
- app/services/importers/service.rb
- lib/import/catalogues.rb
- lib/import/providers.rb
- lib/import/resources.rb
- lib/tasks/import.rake
- spec/features/service_question_spec.rb
- spec/lib/import/providers_spec.rb
- Add logs for catalogues import
- Fix assigning catalogue_id to the service
> fix:[HOTFIX] Import `catalogue_id` on REST import

- CHANGELOG.md
- README.md
- app/controllers/concerns/service/recommendable.rb
- app/models/catalogue.rb
- app/services/importers/provider.rb
- app/services/importers/service.rb
- lib/import/catalogues.rb
- lib/import/providers.rb
- lib/import/resources.rb
- lib/tasks/import.rake
- spec/features/service_question_spec.rb
- spec/lib/import/providers_spec.rb
- Add logs for catalogues import
- Fix assigning catalogue_id to the service
>  fix:[HOTFIX] Import `catalogue_id` on REST import

- app/models/service.rb
- app/policies/backoffice/service_policy.rb
- app/services/importers/service.rb
- app/services/provider/pc_create_or_update.rb
- app/services/service/pc_create_or_update.rb
- app/views/backoffice/services/_form.html.haml
- docs/upgrade/3.43.0.md
- lib/tasks/migration.rake
- spec/policies/backoffice/service_policy_spec.rb
PR with task migrating old PC ids to new version, eg. from "egi-foundation" to "eosc.egi-foundation"
> Id migration tasks

- app/controllers/concerns/service/recommendable.rb
> [#2769] Adjust recommendations request to changes in the recommender

- CHANGELOG.md
- app/helpers/presentable_helper.rb
- app/views/home/_info.html.haml
- app/views/home/_products.html.haml
- config/application.rb
- config/tours/home/index.en.yml
- docs/upgrade/3.43.0.md
- test/system/cypress/integration/regression_tests/backoffice/category/category.spec.ts
- test/system/cypress/integration/regression_tests/backoffice/scientific-domain/scientific-domain.spec.ts
- test/system/cypress/integration/regression_tests/home-page/scientific-domain_categories.spec.ts
- test/system/cypress/integration/sanity.spec.ts
#2791 - mods of texts and link on home page
> mp home page mods

- CHANGELOG.md
- app/controllers/concerns/service/searchable.rb
- app/models/filter.rb
- app/models/filter/ancestry_multiselect.rb
- app/models/filter/research_category.rb
- app/models/service/search.rb
- spec/factories/vocabularies/research_category.rb
- spec/models/filter/research_category_spec.rb
Add research category filter to the service search
> Add research category filter

- CHANGELOG.md
- app/helpers/eosc_explore_banner_helper.rb
- app/views/home/_info.html.haml
- config/eosc_explore_banner.yml
Fixes creation of link generated by `EOSC::` tag
> fix:[HOTFIX] Fix EOSC Explore links

- app/javascript/stylesheets/customization.scss
- app/views/home/_info.html.haml
- app/views/layouts/_flash.html.haml
- db/schema.rb
https://github.com/cyfronet-fid/marketplace/issues/2821
> 2821 explanation of the new navigation

- app/helpers/presentable_helper.rb
Fix links to scientific domain filter
in search service including
hierarchical names
> fix: Fix scientific domain links

- app/views/home/_info.html.haml
- app/views/layouts/_flash.html.haml
Add link to the search service notice
in the mp
> fix: Add link to search service

- db/schema.rb
Revert changes in schema.rb
made by mistake in #2823
> chore: Revert schema changes

- app/models/concerns/importable.rb
- app/services/importers/datasource.rb
- app/services/importers/service.rb
- app/services/jms/manage_message.rb
Fix importing reseach steps
and horizontal flag
via JMS subscriber
Closes #2811
> fix:[#2811] Fix importing datasource extras

- CHANGELOG.md
- app/components/presentable/header_component.html.haml
- app/javascript/stylesheets/_bootstrap-customizations.scss
- app/views/components/presentable/header_component/_backoffice_datasource_buttons.html.haml
- app/views/components/presentable/header_component/_datasource_drop_down_menu.html.haml
CSS and styling mods for datasources according to #2808
> 2808 style for datasource

- app/javascript/stylesheets/_bootstrap-customizations.scss
- app/views/projects/services/_layout.html.haml
Globally fixed font-weight: bold issue
Closes #2854
> titles font weight

- app/controllers/backoffice/services_controller.rb
- app/views/components/presentable/sidebar_component/_monitoring.html.haml
- config/locales/views/components/en.yml
- spec/features/service_question_spec.rb
Fix error caused by not fetching monitoring data
in the backoffice controller
Change texts in the monitoring data tooltips
> fix:[HOTFIX] Fix displaying service in backoffice

- README.md
- app/helpers/application_helper.rb
- app/views/layouts/_navbar.html.haml
- app/views/layouts/_sections.html.haml
- config/application.rb
- spec/features/backoffice_spec.rb
- spec/features/profile_spec.rb
- test/system/cypress/integration/regression_tests/backoffice/category/category.spec.ts
- test/system/cypress/integration/regression_tests/backoffice/platforms/platforms.spec.ts
- test/system/cypress/integration/regression_tests/backoffice/providers/providers.spec.ts
- test/system/cypress/integration/regression_tests/backoffice/resources/owned_resources.spec.ts
- test/system/cypress/integration/regression_tests/backoffice/scientific-domain/scientific-domain.spec.ts
- test/system/cypress/integration/regression_tests/backoffice/vocabularies/vocabularies.spec.ts
- test/system/cypress/integration/regression_tests/service-page/favourites/favourites.spec.ts
- test/system/cypress/integration/regression_tests/service-page/my_eosc_marketplace/my-profile.spec.ts
- test/system/cypress/integration/regression_tests/service-page/my_eosc_marketplace/my-project.spec.ts
> feat: [#2884] Update blue bar and commons

- app/serializers/recommender/service_serializer.rb
- spec/features/api_docs_spec.rb
- test/system/cypress/support/auth.ts
> Delete duplicated pid in service serializer

- app/controllers/user_action_controller.rb
> [#2652] Add server-side user actions timestamp

- app/controllers/services/summaries_controller.rb
> [#2896] Send user action to the databus on project addition

- app/views/services/show.html.haml
> fix: [#2920] Compare bar is visible in service

- CHANGELOG.md
- app/javascript/stylesheets/_bootstrap-customizations.scss
- app/javascript/stylesheets/_variables.scss
- app/views/services/_bundle_box.html.haml
https://github.com/cyfronet-fid/marketplace/issues/2937
> feat:[#2937] Update primary css color

- app/views/layouts/_eosc_commons_footer.haml
- app/views/layouts/admin.html.haml
- app/views/layouts/application.html.haml
- app/views/layouts/backoffice.html.haml
- app/views/layouts/clear.html.haml
- app/views/layouts/executive.html.haml
- app/views/layouts/order.html.haml
- app/views/layouts/ordering_configuration.html.haml
ENV variable should be set to:
```
EOSC_COMMONS_BASE_URL=https://s3.cloud.cyfronet.pl/eosc-portal-common/pr-229-add-possibility-to-customize-privacy-policy-and-term-of-use-in-the-footer-per-service/
```
> feat: add search service terms of use and privacy policy

- CHANGELOG.md
- app/helpers/landing_page_helper.rb
- app/views/components/presentable/header_component/_provider_drop_down_menu.html.haml
- app/views/components/presentable/header_component/_service_drop_down_menu.html.haml
- app/views/layouts/_navbar.html.haml
- app/views/pages/landing_page.html.haml
- app/views/projects/nav/_projects.html.haml
- config/application.rb
Add link in "My projects" page
to the user dashboard
Closes https://github.com/cyfronet-fid/marketplace/issues/2947
> [#2947] Fix flow between MP and UD

- CHANGELOG.md
- app/controllers/services/offers_controller.rb
- app/javascript/stylesheets/_bootstrap-customizations.scss
- app/views/layouts/order.html.haml
- app/views/layouts/order/_nav.html.haml
- app/views/services/information/_bundle.html.haml
- app/views/services/information/show.html.haml
- app/views/services/offers/_bundle_box.html.haml
- app/views/services/offers/_bundle_description.html.haml
- app/views/services/offers/_offer.html.haml
- app/views/services/offers/show.html.haml
- spec/features/order_spec.rb
- spec/models/publishable.rb
> 2952 offer selection

- CHANGELOG.md
- README.md
- app/helpers/presentable/details_helper.rb
- app/helpers/search_links_helper.rb
- app/models/guideline.rb
- app/models/service.rb
- app/models/service_guideline.rb
- app/views/components/presentable/details_component/_links.html.haml
- db/migrate/20230422003902_create_guideline.rb
- db/migrate/20230422004536_connect_guidelines.rb
- db/schema.rb
- lib/import/guidelines.rb
- lib/tasks/import.rake
To test this PR run a rake task:
```
rake import:guidelines
```
Details:
* Add interoperability guidelines schema
* Add importer
* Show guidelines on service details page
Closes #2962
> feat: [#2962] Import interoperability guidelines

- app/components/presentable/details_component.rb
- app/controllers/application_controller.rb
- app/controllers/services/guidelines_controller.rb
- app/helpers/landing_page_helper.rb
- app/helpers/presentable/details_helper.rb
- app/models/guideline.rb
- app/models/service.rb
- app/services/importers/request.rb
- app/views/services/_tabs.haml
- app/views/services/guidelines/index.html.haml
- config/routes.rb
- lib/import/guidelines.rb
Add tab for guidelines in the service view
Closes #2986
> feat:[#2986] Move IG to the separate tab

- app/helpers/landing_page_helper.rb
- app/javascript/stylesheets/_bootstrap-customizations.scss
- app/views/pages/landing_page.html.haml
> links under search box fix

- db/schema.rb
This PR just reverts unexpected schema changes.
> Revert mistaken schema changes

- app/views/services/offers/_bundle_box.html.haml
- app/views/services/offers/_bundle_description.html.haml
Fix calling unitialized `bundle` variable
> fix:[] Fix ViewError in the offer's step

- .github/workflows/pr-instance-comment.yml
Add GH-Action with PR instance URL comment
> chore: Add auto comment with pr instance URL

- CHANGELOG.md
- app/controllers/concerns/service/recommendable.rb
Change the path and parsing data coming from the new endpoints
in similar services recommender
Closes #2890
> [#2890] Adapt to the new version of SimilarServices

- CHANGELOG.md
- Gemfile
- Gemfile.lock
- app/controllers/admin/features_controller.rb
- app/javascript/app/controllers/ordering_controller.js
- app/policies/backoffice/bundle_policy.rb
- app/views/admin/features/show.html.haml
- app/views/backoffice/services/bundles/_form.html.haml
- app/views/services/filters/_multiselect_level.html.haml
- db/internal_vocabulary.yml
- db/vocabulary.yml
- lib/tasks/rdt.rake
- package.json
- yarn.lock
Add a field to get capabilities of bundle goals suggestions
The field is visible when someone chooses "Other"
Suggestions are available for an admin 
in the [admin/features](https://pr-3044.docker-fid.grid.cyf-kr.edu.pl/admin/features) section.
Closes #2970
> [#2970] Capabilities of goals suggestion in the bundle form

- CHANGELOG.md
- app/controllers/backoffice/services/bundles/drafts_controller.rb
- app/controllers/backoffice/services/bundles/publishes_controller.rb
- app/controllers/services/ordering_configuration/bundles/drafts_controller.rb
- app/controllers/services/ordering_configuration/bundles/publishes_controller.rb
- app/helpers/forms_helper.rb
- app/models/bundle.rb
- app/services/bundle/publish.rb
- app/services/bundle/update.rb
- app/views/backoffice/services/bundles/_form.html.haml
- db/migrate/20230905135312_add_index_to_bundle_offers.rb
- db/schema.rb
- spec/models/bundle_spec.rb
Fixes validation before updating a bundle.
It causes checking if offers which are connected
to the bundle, are published
Add tests for Bundle::Publish service
Closes #3054
> fix:[#3054] Fix validation when publishing a bundle

- app/models/bundle.rb
- spec/models/bundle_spec.rb
- spec/services/offer/draft_spec.rb
Add validation for main offer status.
Now it rejects publishing bundle
with main offer which isn't published
Add test cases to the rspec
Closes #3058
> fix:[#3058] Publishing bundle with drafted main offer

- app/controllers/datasources_controller.rb
- app/helpers/landing_page_helper.rb
- app/models/datasource.rb
Update datasources collection name
from "data-source" to "data_source"
It fixes redirect to the search
> HOTFIX: Change datasources collection name

- app/javascript/stylesheets/_bootstrap-customizations.scss
> Fix bundles links

- app/models/concerns/viewable.rb
- lib/import/resources.rb
- lib/tasks/counter_cache.rake
- spec/lib/import/resources_spec.rb
Add counter cache fix for bundles in services
Add check for returned analytics is a number
Change services endpoint for PC
Closes #3100
> [#3100] Add fixing counter cache for bundles

- app/models/concerns/viewable.rb
- app/models/google/analytics.rb
- app/serializers/application_serializer.rb
Now store_analytics casts Google API response to integer 
Change serializing catalogue as pid instead of name
> HOTFIX:[] Fix views cache uploading and CatalogueSerializer

- CHANGELOG.md
- app/javascript/app/user_action.js
- app/views/layouts/_recommendation.html.haml
Tested on localdev. For more e2e testing it needs to be deployed to beta
> [SS#688] Fix 'back to search' button user action

- app/jobs/datasource/pc_create_or_update_job.rb
- app/services/datasource/pc_create_or_update.rb
- app/services/importers/datasource.rb
- app/services/jms/manage_message.rb
- app/services/service/pc_create_or_update.rb
- lib/import/datasources.rb
- Add `service_category`
- Change name from `research_step` to `marketplace_location`
- Add alternative_identifiers to providers and services
- Change `EOSC Explore` banner text
Closes #3131
> feat:[#3131] Add new fields to the providers and services

- CHANGELOG.md
- README.md
- app/components/presentable/sidebar_component.rb
- app/controllers/services_controller.rb
- app/helpers/presentable/details_helper.rb
- app/helpers/presentable/sidebar_helper.rb
- app/models/service.rb
- app/views/components/presentable/sidebar_component/_monitoring.html.haml
- config/application.rb
- docs/upgrade/3.52.0.md
- lib/import/datasources.rb
- lib/tasks/friendly_id.rake
- lib/tasks/migration.rake
Unified sidebar for services and datasources
Now monitoring data and statistics are displayed
Closes #3123
> fix:[#3123] Fix displaying monitoring data in datasources

- .gitignore
- app/views/common_parts/_research_product_table.html.haml
- app/views/projects/research_products/_research_product_table.html.haml
- app/views/projects/services/_research_product.html.haml
Fix research peoducts view
without best_access_right field
> fix:[HOTFIX] Access right displaying

- app/controllers/concerns/service/categorable.rb
- app/policies/backoffice/datasource_policy.rb
- app/policies/backoffice/service_policy.rb
- app/services/datasource/pc_create_or_update.rb
- app/services/importers/datasource.rb
- app/views/backoffice/services/form/_datasource_content.html.haml
- db/migrate/20231211000114_add_harvestable_to_services.rb
- db/schema.rb
- spec/policies/backoffice/service_policy_spec.rb
https://github.com/cyfronet-fid/marketplace/issues/3143
> 3143 fix jms and import

- CHANGELOG.md
- app/controllers/concerns/service/recommendable.rb
- config/application.rb
Change request from direct
similar services endpoint
to RS Facade
Closes #3132
> feat:[#3132] Similar services through RS Facade

- app/controllers/services/ordering_configuration/bundles/drafts_controller.rb
- app/controllers/services/ordering_configuration/bundles/publishes_controller.rb
- app/controllers/services/ordering_configuration/bundles_controller.rb
- app/controllers/services/ordering_configuration/offers_controller.rb
- app/controllers/services/ordering_configurations_controller.rb
- app/helpers/backoffice/services_helper.rb
- app/helpers/service_helper.rb
- app/models/bundle.rb
- app/policies/ordering_configuration/offer_policy.rb
- app/views/backoffice/providers/index.html.haml
- app/views/backoffice/providers/show.html.haml
- app/views/backoffice/services/bundles/_form.html.haml
- app/views/backoffice/services/offers/_form.html.haml
- app/views/backoffice/services/show.html.haml
- app/views/layouts/common_parts/services/_bundle_box.html.haml
- app/views/layouts/common_parts/services/_offers.html.haml
- config/locales/simple_form.en.yml
- config/routes.rb
- spec/features/backoffice/services/bundles_spec.rb
- spec/features/backoffice/services_spec.rb
- test/system/cypress/e2e/regression_tests/backoffice/providers/providers.spec.ts
- test/system/cypress/e2e/regression_tests/backoffice/resources/owned_resources.spec.ts
Add creating bundles to the
ordering_configuration panel
Fix parameters sending in offers
Closes #3163
> feat:[#3163] Add bundles to ordering_configuration

- .github/workflows/pr-instance-comment.yml
Change GH action from bubkoo/auto-comment
to wow-actions/autocomment
> chore: Update auto-comment GH Action

- app/components/presentable/description_component.html.haml
- app/components/presentable/details_component.html.haml
- app/components/presentable/provider_info_component.html.haml
- app/helpers/presentable/details_helper.rb
- app/helpers/presentable/links_helper.rb
- app/javascript/stylesheets/_bootstrap-customizations.scss
- app/views/components/presentable/header_component/_provider_buttons.html.haml
- app/views/components/presentable/sidebar_component/_classification.html.haml
- app/views/providers/_related.html.haml
- app/views/providers/_service_box.html.haml
- app/views/providers/_tabs.haml
- app/views/providers/details/index.html.haml
- app/views/providers/show.html.haml
- spec/features/provider_question_spec.rb
- spec/features/provider_spec.rb
Fix provider landing page 
Closes #3186 
https://marketplace-11.docker-fid.grid.cyf-kr.edu.pl/
> 3186 privider landing page

- app/models/catalogue.rb
- app/serializers/ess/catalogue_serializer.rb
- app/services/importers/catalogue.rb
- swagger/v1/ess/catalogue/catalogue_read.json
This PR contains fixes for Catalogue REST import merged to the master.
Should be merged before other Pull Requests.
> Merge master to 3.55.2

- CHANGELOG.md
- app/javascript/images/chevron-up.svg
- app/javascript/stylesheets/_bootstrap-customizations.scss
- app/views/helps/_item.html.haml
- app/views/helps/_section.html.haml
- app/views/helps/_toc.html.haml
- app/views/helps/show.html.haml
- config/routes.rb
> faq page styling

- CHANGELOG.md
- app/javascript/stylesheets/_bootstrap-customizations.scss
- app/views/services/bundles/_offer.html.haml
- app/views/services/bundles/show.html.haml
Fix bundle view for bundles with
offers containing more than 4 parameters
> Fix bundle view

- CHANGELOG.md
- app/models/project.rb
- app/views/projects/_details.html.haml
- config/brakeman.ignore
- config/locales/simple_form.en.yml
- spec/features/order_spec.rb
- spec/features/projects_spec.rb
- spec/models/project_spec.rb
> fix: alter a field for new project form

- CHANGELOG.md
- app/javascript/stylesheets/_bootstrap-customizations.scss
- app/javascript/stylesheets/_ref_mobile.scss
- app/javascript/stylesheets/_variables.scss
- app/views/layouts/_navbar.html.haml
- app/views/pages/landing_page.html.haml
- config/brakeman.ignore
> Suspension top information

- app/javascript/stylesheets/_bootstrap-customizations.scss
- app/views/layouts/_navbar.html.haml
- app/views/pages/landing_page.html.haml
Added new text due to Figma: https://www.figma.com/file/FtUWM7XIQklFKAoabpt4ta/Baner-EOSC?node-id=9124%3A100&mode=dev
> Suspension text mod

- CHANGELOG.md
- app/helpers/backoffice/parameters_helper.rb
- app/javascript/app/choices.js
- app/javascript/app/controllers/offer_controller.js
- app/javascript/images/help-circle.svg
- app/javascript/stylesheets/_bootstrap-customizations.scss
- app/views/backoffice/services/offers/_form.html.haml
- app/views/backoffice/services/offers/steps/_offer_parameters.html.haml
- app/views/backoffice/services/offers/steps/_offer_type.html.haml
- app/views/backoffice/services/offers/steps/_order_parameters.html.haml
- app/views/backoffice/services/offers/steps/_summary.html.haml
- app/views/parameters/_parameters_button.html.haml
- config/offer_parameters.yml
- db/internal_vocabulary.yml
Fixes:
- Disable and gray out empty choices fields
- Fix button tag to "Own Ordering System"
- Fix default parameters' units
- Add links to the provider's guide and helpdesk
Closes #3254
> fix:[#3254] Fixes for offers feature

- CHANGELOG.md
- app/assets/stylesheets/_bootstrap-customizations.scss
- app/assets/stylesheets/_variables.scss
- app/views/services/_bundle_box.html.haml
- app/views/services/_bundled_offer.html.haml
- app/views/services/_offers.html.haml
- app/views/services/bundles/_description.html.haml
- app/views/services/offers/_bundle_links.html.haml
- app/views/services/offers/_bundle_parameters.html.haml
Adapt style changes to rails 7
Closes #3235
> styles:[#3235] new design for bundles in rails 7

- CHANGELOG.md
- app/assets/stylesheets/_bootstrap-customizations.scss
- app/views/backoffice/services/new.html.haml
> fix:[#3299] overflow accordion fix

- .github/workflows/ci_backend.yml
- .github/workflows/ci_frontend_manager.yml
- .github/workflows/ci_frontend_user.yml
- .github/workflows/e2e.yml
- CHANGELOG.md
- app/models/offer.rb
> fix offer type validator

- CHANGELOG.md
- app/views/backoffice/services/offers/_form.html.haml
- app/views/backoffice/services/offers/edit.html.haml
- app/views/backoffice/services/offers/new.html.haml
> add exit button

- CHANGELOG.md
- app/assets/stylesheets/_bootstrap-customizations.scss
- app/assets/stylesheets/_variables.scss
- app/controllers/backoffice/services/offers_controller.rb
- app/inputs/custom_input.rb
- app/javascript/controllers/exit_controller.js
- app/javascript/controllers/index.js
- app/models/attribute.rb
- app/models/offer.rb
- app/models/offer/parameters.rb
- app/services/offer/create_as_draft.rb
- app/services/offer/update_as_draft.rb
- app/views/backoffice/services/offers/_exit_modal.html.haml
- app/views/backoffice/services/offers/_form.html.haml
- app/views/backoffice/services/offers/steps/_description.html.haml
- spec/models/attribute/quantity_price_spec.rb
- spec/models/attribute_spec.rb
> save as draft

- CHANGELOG.md
- README.md
Added readme section about manual development setup
> chore: added readme section about manual dev setup guide

- app/views/pages/landing_page.html.haml
closes: https://github.com/cyfronet-fid/eosc-search-service/issues/1526
> style: [#] change landing page title

- CHANGELOG.md
- app/controllers/services/offers_controller.rb
- app/helpers/order_nav_helper.rb
- app/views/layouts/order.html.haml
- spec/features/order_spec.rb
Fix redirect to login when
user is trying to order a service
Closes #3337
> fix:[#3337] Fix login in ordering

- app/javascript/app/cookies_policy.js
New link and styling in cookies banner:
> new privacy link

- app/helpers/application_helper.rb
- app/services/catalogue/pc_create_or_update.rb
- app/services/importers/catalogue.rb
- app/services/importers/datasource.rb
- app/services/importers/logo.rb
- app/services/importers/provider.rb
- app/services/importers/service.rb
- app/services/jms/manage_message.rb
- app/services/provider/pc_create_or_update.rb
- app/services/service/pc_create_or_update.rb
- lib/import/catalogues.rb
- lib/import/datasources.rb
- lib/import/providers.rb
- lib/import/resources.rb
Temporary disable import and conversion
of logos for catalogues, providers,
and services
> chore: Disable image processing

- CHANGELOG.md
- README.md
Fix changelog
Add `--no-install-recommends` option to the libvips
> chore: Release 3.59.0

- CHANGELOG.md
- app/controllers/services/choose_offers_controller.rb
- app/controllers/services/configurations_controller.rb
- app/views/layouts/order.html.haml
- app/views/layouts/order/_submit_button.html.haml
- app/views/services/choose_offers/show.html.haml
- app/views/services/configurations/show.html.haml
- app/views/services/information/show.html.haml
- app/views/services/summaries/show.html.haml
Change login redirect to the beginning
of ordering process
> fix: Fix signing in for ordering scope

- .tool-versions
- app/helpers/application_helper.rb
- app/views/layouts/_sections.html.haml
> feat:[3480] Apply new tab feature to header
